-- Verwijder alle bestaande WK spelers
DELETE FROM "Speler" WHERE soort = 'wk';

-- ============================================================
-- GROEP A: MEX, ZAF, KOR, CZE
-- ============================================================

-- Mexico (MEX)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Guillermo Ochoa', 'MEX', 'DOE', 'wk'),
(gen_random_uuid(), 'Carlos Acevedo', 'MEX', 'DOE', 'wk'),
(gen_random_uuid(), 'Raul Rangel', 'MEX', 'DOE', 'wk'),
(gen_random_uuid(), 'Edson Alvarez', 'MEX', 'VER', 'wk'),
(gen_random_uuid(), 'Cesar Montes', 'MEX', 'VER', 'wk'),
(gen_random_uuid(), 'Johan Vasquez', 'MEX', 'VER', 'wk'),
(gen_random_uuid(), 'Jesus Gallardo', 'MEX', 'VER', 'wk'),
(gen_random_uuid(), 'Jorge Sanchez', 'MEX', 'VER', 'wk'),
(gen_random_uuid(), 'Israel Reyes', 'MEX', 'VER', 'wk'),
(gen_random_uuid(), 'Luis Chavez', 'MEX', 'MID', 'wk'),
(gen_random_uuid(), 'Alvaro Fidalgo', 'MEX', 'MID', 'wk'),
(gen_random_uuid(), 'Orbelin Pineda', 'MEX', 'MID', 'wk'),
(gen_random_uuid(), 'Luis Romo', 'MEX', 'MID', 'wk'),
(gen_random_uuid(), 'Erik Lira', 'MEX', 'MID', 'wk'),
(gen_random_uuid(), 'Obed Vargas', 'MEX', 'MID', 'wk'),
(gen_random_uuid(), 'Brian Gutierrez', 'MEX', 'MID', 'wk'),
(gen_random_uuid(), 'Gilberto Mora', 'MEX', 'MID', 'wk'),
(gen_random_uuid(), 'Mateo Chavez', 'MEX', 'MID', 'wk'),
(gen_random_uuid(), 'Raul Jimenez', 'MEX', 'AAN', 'wk'),
(gen_random_uuid(), 'Santiago Gimenez', 'MEX', 'AAN', 'wk'),
(gen_random_uuid(), 'Julian Quinones', 'MEX', 'AAN', 'wk'),
(gen_random_uuid(), 'Roberto Alvarado', 'MEX', 'AAN', 'wk'),
(gen_random_uuid(), 'Alexis Vega', 'MEX', 'AAN', 'wk'),
(gen_random_uuid(), 'Cesar Huerta', 'MEX', 'AAN', 'wk'),
(gen_random_uuid(), 'Guillermo Martinez', 'MEX', 'AAN', 'wk'),
(gen_random_uuid(), 'Armando Gonzalez', 'MEX', 'AAN', 'wk');

-- Zuid-Afrika (ZAF)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Ronwen Williams', 'ZAF', 'DOE', 'wk'),
(gen_random_uuid(), 'Veli Mothwa', 'ZAF', 'DOE', 'wk'),
(gen_random_uuid(), 'Bruce Bvuma', 'ZAF', 'DOE', 'wk'),
(gen_random_uuid(), 'Reeve Frosler', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Siyanda Xulu', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Teboho Mokoena', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Njabulo Ngcobo', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Terrence Mashego', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Siyabonga Ngezana', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Sifiso Hlanti', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Grant Kekana', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Khuliso Mudau', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Ethan Chrispin', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Bongani Zungu', 'ZAF', 'MID', 'wk'),
(gen_random_uuid(), 'Ethan Nurick', 'ZAF', 'MID', 'wk'),
(gen_random_uuid(), 'Sphelele Sithole', 'ZAF', 'MID', 'wk'),
(gen_random_uuid(), 'Yusuf Maart', 'ZAF', 'MID', 'wk'),
(gen_random_uuid(), 'Nkosinathi Sibisi', 'ZAF', 'MID', 'wk'),
(gen_random_uuid(), 'Themba Zwane', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Percy Tau', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Lyle Foster', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Tashreeq Morris', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Evidence Makgopa', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Elias Mokwana', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Relebohile Mofokeng', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Oswin Appollis', 'ZAF', 'AAN', 'wk');

-- Zuid-Korea (KOR)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Kim Seung-gyu', 'KOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Song Bum-keun', 'KOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Jo Hyeon-woo', 'KOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Kim Moon-hwan', 'KOR', 'VER', 'wk'),
(gen_random_uuid(), 'Kim Min-jae', 'KOR', 'VER', 'wk'),
(gen_random_uuid(), 'Kim Tae-hyeon', 'KOR', 'VER', 'wk'),
(gen_random_uuid(), 'Park Jin-seop', 'KOR', 'VER', 'wk'),
(gen_random_uuid(), 'Seol Young-woo', 'KOR', 'VER', 'wk'),
(gen_random_uuid(), 'Jens Castrop', 'KOR', 'VER', 'wk'),
(gen_random_uuid(), 'Lee Ki-hyeok', 'KOR', 'VER', 'wk'),
(gen_random_uuid(), 'Lee Tae-seok', 'KOR', 'VER', 'wk'),
(gen_random_uuid(), 'Lee Han-beom', 'KOR', 'VER', 'wk'),
(gen_random_uuid(), 'Cho Yu-min', 'KOR', 'VER', 'wk'),
(gen_random_uuid(), 'Kim Jin-gyu', 'KOR', 'MID', 'wk'),
(gen_random_uuid(), 'Bae Jun-ho', 'KOR', 'MID', 'wk'),
(gen_random_uuid(), 'Paik Seung-ho', 'KOR', 'MID', 'wk'),
(gen_random_uuid(), 'Yang Hyun-jun', 'KOR', 'MID', 'wk'),
(gen_random_uuid(), 'Eom Ji-sung', 'KOR', 'MID', 'wk'),
(gen_random_uuid(), 'Lee Kang-in', 'KOR', 'MID', 'wk'),
(gen_random_uuid(), 'Lee Dong-gyeong', 'KOR', 'MID', 'wk'),
(gen_random_uuid(), 'Lee Jae-sung', 'KOR', 'MID', 'wk'),
(gen_random_uuid(), 'Hwang In-beom', 'KOR', 'MID', 'wk'),
(gen_random_uuid(), 'Hwang Hee-chan', 'KOR', 'MID', 'wk'),
(gen_random_uuid(), 'Son Heung-min', 'KOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Oh Hyeon-gyu', 'KOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Cho Gue-sung', 'KOR', 'AAN', 'wk');

-- Tsjechië (CZE)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Jindřich Staněk', 'CZE', 'DOE', 'wk'),
(gen_random_uuid(), 'Matěj Kovář', 'CZE', 'DOE', 'wk'),
(gen_random_uuid(), 'Aleš Mandous', 'CZE', 'DOE', 'wk'),
(gen_random_uuid(), 'Vladimír Coufal', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Jakub Brabec', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Tomáš Holeš', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'David Jurásek', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Ladislav Krejčí', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Martin Vitík', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Robin Hranáč', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Lukáš Provod', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Ondřej Zelený', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Tomáš Souček', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Lukáš Sadílek', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Antonín Barák', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Marek Sojka', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Jan Kuchta', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Michal Sadílek', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Václav Sejk', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Adam Hložek', 'CZE', 'AAN', 'wk'),
(gen_random_uuid(), 'Tomáš Chorý', 'CZE', 'AAN', 'wk'),
(gen_random_uuid(), 'Patrik Schick', 'CZE', 'AAN', 'wk'),
(gen_random_uuid(), 'Lukáš Červ', 'CZE', 'AAN', 'wk'),
(gen_random_uuid(), 'David Jurečka', 'CZE', 'AAN', 'wk'),
(gen_random_uuid(), 'Matěj Jurásek', 'CZE', 'AAN', 'wk'),
(gen_random_uuid(), 'Ondřej Lingr', 'CZE', 'AAN', 'wk');

-- ============================================================
-- GROEP B: CAN, BIH, QAT, SUI
-- ============================================================

-- Canada (CAN)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Maxime Crépeau', 'CAN', 'DOE', 'wk'),
(gen_random_uuid(), 'Dayne St. Clair', 'CAN', 'DOE', 'wk'),
(gen_random_uuid(), 'Owen Goodman', 'CAN', 'DOE', 'wk'),
(gen_random_uuid(), 'Alphonso Davies', 'CAN', 'VER', 'wk'),
(gen_random_uuid(), 'Moïse Bombito', 'CAN', 'VER', 'wk'),
(gen_random_uuid(), 'Derek Cornelius', 'CAN', 'VER', 'wk'),
(gen_random_uuid(), 'Luc de Fougerolles', 'CAN', 'VER', 'wk'),
(gen_random_uuid(), 'Alistair Johnston', 'CAN', 'VER', 'wk'),
(gen_random_uuid(), 'Alfie Jones', 'CAN', 'VER', 'wk'),
(gen_random_uuid(), 'Richie Laryea', 'CAN', 'VER', 'wk'),
(gen_random_uuid(), 'Niko Sigur', 'CAN', 'VER', 'wk'),
(gen_random_uuid(), 'Joel Waterman', 'CAN', 'VER', 'wk'),
(gen_random_uuid(), 'Stephen Eustáquio', 'CAN', 'MID', 'wk'),
(gen_random_uuid(), 'Ali Ahmed', 'CAN', 'MID', 'wk'),
(gen_random_uuid(), 'Mathieu Choinière', 'CAN', 'MID', 'wk'),
(gen_random_uuid(), 'Marcelo Flores', 'CAN', 'MID', 'wk'),
(gen_random_uuid(), 'Ismaël Koné', 'CAN', 'MID', 'wk'),
(gen_random_uuid(), 'Liam Millar', 'CAN', 'MID', 'wk'),
(gen_random_uuid(), 'Jonathan Osorio', 'CAN', 'MID', 'wk'),
(gen_random_uuid(), 'Nathan Saliba', 'CAN', 'MID', 'wk'),
(gen_random_uuid(), 'Jacob Shaffelburg', 'CAN', 'MID', 'wk'),
(gen_random_uuid(), 'Jonathan David', 'CAN', 'AAN', 'wk'),
(gen_random_uuid(), 'Promise David', 'CAN', 'AAN', 'wk'),
(gen_random_uuid(), 'Cyle Larin', 'CAN', 'AAN', 'wk'),
(gen_random_uuid(), 'Tani Oluwaseyi', 'CAN', 'AAN', 'wk'),
(gen_random_uuid(), 'Tajon Buchanan', 'CAN', 'AAN', 'wk');

-- Bosnië en Herzegovina (BIH)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Nikola Vasilj', 'BIH', 'DOE', 'wk'),
(gen_random_uuid(), 'Martin Zlomislić', 'BIH', 'DOE', 'wk'),
(gen_random_uuid(), 'Osman Hadžikić', 'BIH', 'DOE', 'wk'),
(gen_random_uuid(), 'Sead Kolašinac', 'BIH', 'VER', 'wk'),
(gen_random_uuid(), 'Amar Dedić', 'BIH', 'VER', 'wk'),
(gen_random_uuid(), 'Nihad Mujakić', 'BIH', 'VER', 'wk'),
(gen_random_uuid(), 'Nikola Katić', 'BIH', 'VER', 'wk'),
(gen_random_uuid(), 'Tarik Muharemović', 'BIH', 'VER', 'wk'),
(gen_random_uuid(), 'Stjepan Radeljić', 'BIH', 'VER', 'wk'),
(gen_random_uuid(), 'Dennis Hadžikadunić', 'BIH', 'VER', 'wk'),
(gen_random_uuid(), 'Nidal Čelik', 'BIH', 'VER', 'wk'),
(gen_random_uuid(), 'Benjamin Tahirović', 'BIH', 'MID', 'wk'),
(gen_random_uuid(), 'Amir Hadžiahmetović', 'BIH', 'MID', 'wk'),
(gen_random_uuid(), 'Ivan Šunjić', 'BIH', 'MID', 'wk'),
(gen_random_uuid(), 'Ivan Bašić', 'BIH', 'MID', 'wk'),
(gen_random_uuid(), 'Dženis Burnić', 'BIH', 'MID', 'wk'),
(gen_random_uuid(), 'Ermin Mahmić', 'BIH', 'MID', 'wk'),
(gen_random_uuid(), 'Amar Memić', 'BIH', 'MID', 'wk'),
(gen_random_uuid(), 'Armin Gigović', 'BIH', 'MID', 'wk'),
(gen_random_uuid(), 'Kerim Alajbegović', 'BIH', 'MID', 'wk'),
(gen_random_uuid(), 'Esmir Bajraktarević', 'BIH', 'MID', 'wk'),
(gen_random_uuid(), 'Edin Džeko', 'BIH', 'AAN', 'wk'),
(gen_random_uuid(), 'Ermedin Demirović', 'BIH', 'AAN', 'wk'),
(gen_random_uuid(), 'Jovo Lukić', 'BIH', 'AAN', 'wk'),
(gen_random_uuid(), 'Samed Baždar', 'BIH', 'AAN', 'wk'),
(gen_random_uuid(), 'Haris Tabaković', 'BIH', 'AAN', 'wk');

-- Qatar (QAT)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Meshaal Barsham', 'QAT', 'DOE', 'wk'),
(gen_random_uuid(), 'Mahmoud Abunada', 'QAT', 'DOE', 'wk'),
(gen_random_uuid(), 'Salah Zakaria', 'QAT', 'DOE', 'wk'),
(gen_random_uuid(), 'Ahmed Al-Janhi', 'QAT', 'VER', 'wk'),
(gen_random_uuid(), 'Ahmed Fathi', 'QAT', 'VER', 'wk'),
(gen_random_uuid(), 'Ahmed Alaa', 'QAT', 'VER', 'wk'),
(gen_random_uuid(), 'Tahseen Mohammed', 'QAT', 'VER', 'wk'),
(gen_random_uuid(), 'Pedro Miguel', 'QAT', 'VER', 'wk'),
(gen_random_uuid(), 'Boualem Khoukhi', 'QAT', 'VER', 'wk'),
(gen_random_uuid(), 'Ayoub Al-Aloui', 'QAT', 'VER', 'wk'),
(gen_random_uuid(), 'Al-Hashmi Al-Hussein', 'QAT', 'VER', 'wk'),
(gen_random_uuid(), 'Assim Madibo', 'QAT', 'MID', 'wk'),
(gen_random_uuid(), 'Sultan Al-Braik', 'QAT', 'MID', 'wk'),
(gen_random_uuid(), 'Jassem Jaber', 'QAT', 'MID', 'wk'),
(gen_random_uuid(), 'Mohamed Al-Mannai', 'QAT', 'MID', 'wk'),
(gen_random_uuid(), 'Lucas Mendes', 'QAT', 'MID', 'wk'),
(gen_random_uuid(), 'Karim Boudiaf', 'QAT', 'MID', 'wk'),
(gen_random_uuid(), 'Issa Lai', 'QAT', 'MID', 'wk'),
(gen_random_uuid(), 'Abdulaziz Hatem', 'QAT', 'MID', 'wk'),
(gen_random_uuid(), 'Yusuf Abdurisag', 'QAT', 'MID', 'wk'),
(gen_random_uuid(), 'Homam Ahmed', 'QAT', 'MID', 'wk'),
(gen_random_uuid(), 'Hassan Al-Haydos', 'QAT', 'AAN', 'wk'),
(gen_random_uuid(), 'Almoez Ali', 'QAT', 'AAN', 'wk'),
(gen_random_uuid(), 'Akram Afif', 'QAT', 'AAN', 'wk'),
(gen_random_uuid(), 'Edmilson Junior', 'QAT', 'AAN', 'wk'),
(gen_random_uuid(), 'Mohammed Muntari', 'QAT', 'AAN', 'wk');

-- Zwitserland (SUI)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Gregor Kobel', 'SUI', 'DOE', 'wk'),
(gen_random_uuid(), 'Marvin Keller', 'SUI', 'DOE', 'wk'),
(gen_random_uuid(), 'Yvon Mvogo', 'SUI', 'DOE', 'wk'),
(gen_random_uuid(), 'Manuel Akanji', 'SUI', 'VER', 'wk'),
(gen_random_uuid(), 'Aurèle Amenda', 'SUI', 'VER', 'wk'),
(gen_random_uuid(), 'Eray Cömert', 'SUI', 'VER', 'wk'),
(gen_random_uuid(), 'Nico Elvedi', 'SUI', 'VER', 'wk'),
(gen_random_uuid(), 'Luca Jaquez', 'SUI', 'VER', 'wk'),
(gen_random_uuid(), 'Miro Muheim', 'SUI', 'VER', 'wk'),
(gen_random_uuid(), 'Ricardo Rodríguez', 'SUI', 'VER', 'wk'),
(gen_random_uuid(), 'Silvan Widmer', 'SUI', 'VER', 'wk'),
(gen_random_uuid(), 'Granit Xhaka', 'SUI', 'MID', 'wk'),
(gen_random_uuid(), 'Michel Aebischer', 'SUI', 'MID', 'wk'),
(gen_random_uuid(), 'Remo Freuler', 'SUI', 'MID', 'wk'),
(gen_random_uuid(), 'Ardon Jashari', 'SUI', 'MID', 'wk'),
(gen_random_uuid(), 'Fabian Rieder', 'SUI', 'MID', 'wk'),
(gen_random_uuid(), 'Djibril Sow', 'SUI', 'MID', 'wk'),
(gen_random_uuid(), 'Denis Zakaria', 'SUI', 'MID', 'wk'),
(gen_random_uuid(), 'Christian Fassnacht', 'SUI', 'MID', 'wk'),
(gen_random_uuid(), 'Johan Manzambi', 'SUI', 'MID', 'wk'),
(gen_random_uuid(), 'Rubén Vargas', 'SUI', 'MID', 'wk'),
(gen_random_uuid(), 'Breel Embolo', 'SUI', 'AAN', 'wk'),
(gen_random_uuid(), 'Noah Okafor', 'SUI', 'AAN', 'wk'),
(gen_random_uuid(), 'Dan Ndoye', 'SUI', 'AAN', 'wk'),
(gen_random_uuid(), 'Zeki Amdouni', 'SUI', 'AAN', 'wk'),
(gen_random_uuid(), 'Cedric Itten', 'SUI', 'AAN', 'wk');

-- ============================================================
-- GROEP C: BRA, MAR, HAI, SCO
-- ============================================================

-- Brazilië (BRA)
-- Let op: "Éderson" (met accent) = keeper Fenerbahçe, "Ederson" (zonder accent) = middenvelder Atalanta
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Alisson', 'BRA', 'DOE', 'wk'),
(gen_random_uuid(), 'Éderson', 'BRA', 'DOE', 'wk'),
(gen_random_uuid(), 'Weverton', 'BRA', 'DOE', 'wk'),
(gen_random_uuid(), 'Marquinhos', 'BRA', 'VER', 'wk'),
(gen_random_uuid(), 'Gabriel Magalhães', 'BRA', 'VER', 'wk'),
(gen_random_uuid(), 'Bremer', 'BRA', 'VER', 'wk'),
(gen_random_uuid(), 'Ibañez', 'BRA', 'VER', 'wk'),
(gen_random_uuid(), 'Léo Pereira', 'BRA', 'VER', 'wk'),
(gen_random_uuid(), 'Danilo', 'BRA', 'VER', 'wk'),
(gen_random_uuid(), 'Alex Sandro', 'BRA', 'VER', 'wk'),
(gen_random_uuid(), 'Douglas Santos', 'BRA', 'VER', 'wk'),
(gen_random_uuid(), 'Casemiro', 'BRA', 'MID', 'wk'),
(gen_random_uuid(), 'Bruno Guimarães', 'BRA', 'MID', 'wk'),
(gen_random_uuid(), 'Fabinho', 'BRA', 'MID', 'wk'),
(gen_random_uuid(), 'Danilo Santos', 'BRA', 'MID', 'wk'),
(gen_random_uuid(), 'Lucas Paquetá', 'BRA', 'MID', 'wk'),
(gen_random_uuid(), 'Ederson', 'BRA', 'MID', 'wk'),
(gen_random_uuid(), 'Vinícius Jr', 'BRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Raphinha', 'BRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Matheus Cunha', 'BRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Luiz Henrique', 'BRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Igor Thiago', 'BRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Endrick', 'BRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Gabriel Martinelli', 'BRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Rayan', 'BRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Neymar', 'BRA', 'AAN', 'wk');

-- Marokko (MAR)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Yassine Bounou', 'MAR', 'DOE', 'wk'),
(gen_random_uuid(), 'Munir El Kajoui', 'MAR', 'DOE', 'wk'),
(gen_random_uuid(), 'El Mehdi Al Harrar', 'MAR', 'DOE', 'wk'),
(gen_random_uuid(), 'Achraf Hakimi', 'MAR', 'VER', 'wk'),
(gen_random_uuid(), 'Noussair Mazraoui', 'MAR', 'VER', 'wk'),
(gen_random_uuid(), 'Nayef Aguerd', 'MAR', 'VER', 'wk'),
(gen_random_uuid(), 'Chadi Riad', 'MAR', 'VER', 'wk'),
(gen_random_uuid(), 'Zakaria El Ouahdi', 'MAR', 'VER', 'wk'),
(gen_random_uuid(), 'Anass Salah-Eddine', 'MAR', 'VER', 'wk'),
(gen_random_uuid(), 'Youssef Belammari', 'MAR', 'VER', 'wk'),
(gen_random_uuid(), 'Redouane Halhal', 'MAR', 'VER', 'wk'),
(gen_random_uuid(), 'Issa Diop', 'MAR', 'VER', 'wk'),
(gen_random_uuid(), 'Sofyan Amrabat', 'MAR', 'MID', 'wk'),
(gen_random_uuid(), 'Azzedine Ounahi', 'MAR', 'MID', 'wk'),
(gen_random_uuid(), 'Bilal El Khannouss', 'MAR', 'MID', 'wk'),
(gen_random_uuid(), 'Ismael Saibari', 'MAR', 'MID', 'wk'),
(gen_random_uuid(), 'Ayyoub Bouaddi', 'MAR', 'MID', 'wk'),
(gen_random_uuid(), 'Neil El Aynaoui', 'MAR', 'MID', 'wk'),
(gen_random_uuid(), 'Samir El Mourabet', 'MAR', 'MID', 'wk'),
(gen_random_uuid(), 'Brahim Díaz', 'MAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Ayoub El Kaabi', 'MAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Soufiane Rahimi', 'MAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Abde Ezzalzouli', 'MAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Chemsdine Talbi', 'MAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Yassine Gessime', 'MAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Ayoube Amaimouni', 'MAR', 'AAN', 'wk');

-- Haïti (HAI)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Johny Placide', 'HAI', 'DOE', 'wk'),
(gen_random_uuid(), 'Hervé Arcus', 'HAI', 'DOE', 'wk'),
(gen_random_uuid(), 'Michaël Thermoncy', 'HAI', 'DOE', 'wk'),
(gen_random_uuid(), 'Andrew Ade', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Mechack Jérôme', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Carlens Arcus', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Zachary Brault-Guillard', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Kevin Lafrance', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Orlens Delcroix', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Duke Lacroix', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Frantzdy Pierrot', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Nicolas Penneteau', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Pascal Comminges', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Steeven Sala', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Mathurin Miragot', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Duckens Nazon', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Wilde-Donald Guerrier', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Jean-Marc Alexandre', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Frantz Bernier', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Kervens Belfort', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Dario Céus', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Steeven Makiese', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Corentin Jean', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Josué Fortune', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Kevin Denaud', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Etzer Bayens', 'HAI', 'AAN', 'wk');

-- Schotland (SCO)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Craig Gordon', 'SCO', 'DOE', 'wk'),
(gen_random_uuid(), 'Angus Gunn', 'SCO', 'DOE', 'wk'),
(gen_random_uuid(), 'Liam Kelly', 'SCO', 'DOE', 'wk'),
(gen_random_uuid(), 'Andy Robertson', 'SCO', 'VER', 'wk'),
(gen_random_uuid(), 'Kieran Tierney', 'SCO', 'VER', 'wk'),
(gen_random_uuid(), 'Grant Hanley', 'SCO', 'VER', 'wk'),
(gen_random_uuid(), 'Jack Hendry', 'SCO', 'VER', 'wk'),
(gen_random_uuid(), 'Aaron Hickey', 'SCO', 'VER', 'wk'),
(gen_random_uuid(), 'Dom Hyam', 'SCO', 'VER', 'wk'),
(gen_random_uuid(), 'Scott McKenna', 'SCO', 'VER', 'wk'),
(gen_random_uuid(), 'Nathan Patterson', 'SCO', 'VER', 'wk'),
(gen_random_uuid(), 'Anthony Ralston', 'SCO', 'VER', 'wk'),
(gen_random_uuid(), 'John Souttar', 'SCO', 'VER', 'wk'),
(gen_random_uuid(), 'John McGinn', 'SCO', 'MID', 'wk'),
(gen_random_uuid(), 'Scott McTominay', 'SCO', 'MID', 'wk'),
(gen_random_uuid(), 'Ryan Christie', 'SCO', 'MID', 'wk'),
(gen_random_uuid(), 'Lewis Ferguson', 'SCO', 'MID', 'wk'),
(gen_random_uuid(), 'Ben Doak', 'SCO', 'MID', 'wk'),
(gen_random_uuid(), 'Tyler Fletcher', 'SCO', 'MID', 'wk'),
(gen_random_uuid(), 'Kenny McLean', 'SCO', 'MID', 'wk'),
(gen_random_uuid(), 'Findlay Curtis', 'SCO', 'MID', 'wk'),
(gen_random_uuid(), 'Lawrence Shankland', 'SCO', 'AAN', 'wk'),
(gen_random_uuid(), 'Lyndon Dykes', 'SCO', 'AAN', 'wk'),
(gen_random_uuid(), 'Ché Adams', 'SCO', 'AAN', 'wk'),
(gen_random_uuid(), 'Ross Stewart', 'SCO', 'AAN', 'wk'),
(gen_random_uuid(), 'George Hirst', 'SCO', 'AAN', 'wk');

-- ============================================================
-- GROEP D: USA, PAR, AUS, TUR
-- ============================================================

-- Verenigde Staten (USA)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Matt Turner', 'USA', 'DOE', 'wk'),
(gen_random_uuid(), 'Patrick Schulte', 'USA', 'DOE', 'wk'),
(gen_random_uuid(), 'Ethan Horvath', 'USA', 'DOE', 'wk'),
(gen_random_uuid(), 'Sergino Dest', 'USA', 'VER', 'wk'),
(gen_random_uuid(), 'Tim Ream', 'USA', 'VER', 'wk'),
(gen_random_uuid(), 'Chris Richards', 'USA', 'VER', 'wk'),
(gen_random_uuid(), 'Antonee Robinson', 'USA', 'VER', 'wk'),
(gen_random_uuid(), 'Miles Robinson', 'USA', 'VER', 'wk'),
(gen_random_uuid(), 'Joe Scally', 'USA', 'VER', 'wk'),
(gen_random_uuid(), 'John Tolkin', 'USA', 'VER', 'wk'),
(gen_random_uuid(), 'Mark McKenzie', 'USA', 'VER', 'wk'),
(gen_random_uuid(), 'Walker Zimmerman', 'USA', 'VER', 'wk'),
(gen_random_uuid(), 'Weston McKennie', 'USA', 'MID', 'wk'),
(gen_random_uuid(), 'Tyler Adams', 'USA', 'MID', 'wk'),
(gen_random_uuid(), 'Gio Reyna', 'USA', 'MID', 'wk'),
(gen_random_uuid(), 'Luca de la Torre', 'USA', 'MID', 'wk'),
(gen_random_uuid(), 'Yunus Musah', 'USA', 'MID', 'wk'),
(gen_random_uuid(), 'Johnny Chang', 'USA', 'MID', 'wk'),
(gen_random_uuid(), 'Christian Pulisic', 'USA', 'AAN', 'wk'),
(gen_random_uuid(), 'Ricardo Pepi', 'USA', 'AAN', 'wk'),
(gen_random_uuid(), 'Folarin Balogun', 'USA', 'AAN', 'wk'),
(gen_random_uuid(), 'Tim Weah', 'USA', 'AAN', 'wk'),
(gen_random_uuid(), 'Brenden Aaronson', 'USA', 'AAN', 'wk'),
(gen_random_uuid(), 'Josh Sargent', 'USA', 'AAN', 'wk'),
(gen_random_uuid(), 'Malik Tillman', 'USA', 'AAN', 'wk'),
(gen_random_uuid(), 'Cade Cowell', 'USA', 'AAN', 'wk');

-- Paraguay (PAR)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Gatito Fernández', 'PAR', 'DOE', 'wk'),
(gen_random_uuid(), 'Orlando Gill', 'PAR', 'DOE', 'wk'),
(gen_random_uuid(), 'Gastón Olveira', 'PAR', 'DOE', 'wk'),
(gen_random_uuid(), 'Gustavo Gómez', 'PAR', 'VER', 'wk'),
(gen_random_uuid(), 'Júnior Alonso', 'PAR', 'VER', 'wk'),
(gen_random_uuid(), 'Fabián Balbuena', 'PAR', 'VER', 'wk'),
(gen_random_uuid(), 'Omar Alderete', 'PAR', 'VER', 'wk'),
(gen_random_uuid(), 'Juan José Cáceres', 'PAR', 'VER', 'wk'),
(gen_random_uuid(), 'Gustavo Velázquez', 'PAR', 'VER', 'wk'),
(gen_random_uuid(), 'José Canale', 'PAR', 'VER', 'wk'),
(gen_random_uuid(), 'Alexandro Maidana', 'PAR', 'VER', 'wk'),
(gen_random_uuid(), 'Miguel Almirón', 'PAR', 'MID', 'wk'),
(gen_random_uuid(), 'Kaku', 'PAR', 'MID', 'wk'),
(gen_random_uuid(), 'Andrés Cubas', 'PAR', 'MID', 'wk'),
(gen_random_uuid(), 'Ramón Sosa', 'PAR', 'MID', 'wk'),
(gen_random_uuid(), 'Diego Gómez', 'PAR', 'MID', 'wk'),
(gen_random_uuid(), 'Damián Bobadilla', 'PAR', 'MID', 'wk'),
(gen_random_uuid(), 'Braian Ojeda', 'PAR', 'MID', 'wk'),
(gen_random_uuid(), 'Matías Galarza', 'PAR', 'MID', 'wk'),
(gen_random_uuid(), 'Maurício', 'PAR', 'MID', 'wk'),
(gen_random_uuid(), 'Antonio Sanabria', 'PAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Julio Enciso', 'PAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Gabriel Ávalos', 'PAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Álex Arce', 'PAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Isidro Pitta', 'PAR', 'AAN', 'wk'),
(gen_random_uuid(), 'Gustavo Caballero', 'PAR', 'AAN', 'wk');

-- Australië (AUS)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Mathew Ryan', 'AUS', 'DOE', 'wk'),
(gen_random_uuid(), 'Joe Gauci', 'AUS', 'DOE', 'wk'),
(gen_random_uuid(), 'Danny Vukovic', 'AUS', 'DOE', 'wk'),
(gen_random_uuid(), 'Milos Degenek', 'AUS', 'VER', 'wk'),
(gen_random_uuid(), 'Fran Karacic', 'AUS', 'VER', 'wk'),
(gen_random_uuid(), 'Kye Rowles', 'AUS', 'VER', 'wk'),
(gen_random_uuid(), 'Harry Souttar', 'AUS', 'VER', 'wk'),
(gen_random_uuid(), 'Bailey Wright', 'AUS', 'VER', 'wk'),
(gen_random_uuid(), 'Aziz Behich', 'AUS', 'VER', 'wk'),
(gen_random_uuid(), 'Nathaniel Atkinson', 'AUS', 'VER', 'wk'),
(gen_random_uuid(), 'Thomas Deng', 'AUS', 'VER', 'wk'),
(gen_random_uuid(), 'Osher Dvir', 'AUS', 'VER', 'wk'),
(gen_random_uuid(), 'Tyrese Français', 'AUS', 'VER', 'wk'),
(gen_random_uuid(), 'Jackson Irvine', 'AUS', 'MID', 'wk'),
(gen_random_uuid(), 'Riley McGree', 'AUS', 'MID', 'wk'),
(gen_random_uuid(), 'Ajdin Hrustic', 'AUS', 'MID', 'wk'),
(gen_random_uuid(), 'Cameron Devlin', 'AUS', 'MID', 'wk'),
(gen_random_uuid(), 'Connor Metcalfe', 'AUS', 'MID', 'wk'),
(gen_random_uuid(), 'Aiden O''Neill', 'AUS', 'MID', 'wk'),
(gen_random_uuid(), 'Mathew Leckie', 'AUS', 'AAN', 'wk'),
(gen_random_uuid(), 'Awer Mabil', 'AUS', 'AAN', 'wk'),
(gen_random_uuid(), 'Nestory Irankunda', 'AUS', 'AAN', 'wk'),
(gen_random_uuid(), 'Cristian Volpato', 'AUS', 'AAN', 'wk'),
(gen_random_uuid(), 'Tete Yengi', 'AUS', 'AAN', 'wk'),
(gen_random_uuid(), 'Kusini Yengi', 'AUS', 'AAN', 'wk'),
(gen_random_uuid(), 'Mohamed Toure', 'AUS', 'AAN', 'wk');

-- Turkije (TUR)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Altay Bayındır', 'TUR', 'DOE', 'wk'),
(gen_random_uuid(), 'Mert Günok', 'TUR', 'DOE', 'wk'),
(gen_random_uuid(), 'Uğurcan Çakır', 'TUR', 'DOE', 'wk'),
(gen_random_uuid(), 'Abdülkerim Bardakcı', 'TUR', 'VER', 'wk'),
(gen_random_uuid(), 'Çağlar Söyüncü', 'TUR', 'VER', 'wk'),
(gen_random_uuid(), 'Eren Elmalı', 'TUR', 'VER', 'wk'),
(gen_random_uuid(), 'Ferdi Kadıoğlu', 'TUR', 'VER', 'wk'),
(gen_random_uuid(), 'Merih Demiral', 'TUR', 'VER', 'wk'),
(gen_random_uuid(), 'Mert Müldür', 'TUR', 'VER', 'wk'),
(gen_random_uuid(), 'Ozan Kabak', 'TUR', 'VER', 'wk'),
(gen_random_uuid(), 'Samet Akaydın', 'TUR', 'VER', 'wk'),
(gen_random_uuid(), 'Zeki Çelik', 'TUR', 'VER', 'wk'),
(gen_random_uuid(), 'Hakan Çalhanoğlu', 'TUR', 'MID', 'wk'),
(gen_random_uuid(), 'İsmail Yüksek', 'TUR', 'MID', 'wk'),
(gen_random_uuid(), 'Kaan Ayhan', 'TUR', 'MID', 'wk'),
(gen_random_uuid(), 'Orkun Kökçü', 'TUR', 'MID', 'wk'),
(gen_random_uuid(), 'Salih Özcan', 'TUR', 'MID', 'wk'),
(gen_random_uuid(), 'Arda Güler', 'TUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Kenan Yıldız', 'TUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Kerem Aktürkoglu', 'TUR', 'AAN', 'wk'),
(gen_random_uuid(), 'İrfan Can Kahveci', 'TUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Barış Alper Yılmaz', 'TUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Yunus Akgün', 'TUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Oğuz Aydın', 'TUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Deniz Gül', 'TUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Can Uzun', 'TUR', 'AAN', 'wk');
