-- Delete all existing WK players and insert correct data
DELETE FROM "Speler" WHERE soort = 'wk';

-- Group A: Qatar, Ecuador, Senegal, Netherlands
INSERT INTO "Speler" (id, naam, positie, team, soort) VALUES
(gen_random_uuid(), 'Meshaal Barsham', 'DOE', 'QAT', 'wk'),
(gen_random_uuid(), 'Saad Al-Sheeb', 'DOE', 'QAT', 'wk'),
(gen_random_uuid(), 'Yousuf Hassan', 'DOE', 'QAT', 'wk'),
(gen_random_uuid(), 'Pedro Miguel', 'VER', 'QAT', 'wk'),
(gen_random_uuid(), 'Bassam Al-Rawi', 'VER', 'QAT', 'wk'),
(gen_random_uuid(), 'Abdelkarim Hassan', 'VER', 'QAT', 'wk'),
(gen_random_uuid(), 'Homam Ahmed', 'VER', 'QAT', 'wk'),
(gen_random_uuid(), 'Tarek Salman', 'VER', 'QAT', 'wk'),
(gen_random_uuid(), 'Boualem Khoukhi', 'VER', 'QAT', 'wk'),
(gen_random_uuid(), 'Assim Madibo', 'MID', 'QAT', 'wk'),
(gen_random_uuid(), 'Karim Boudiaf', 'MID', 'QAT', 'wk'),
(gen_random_uuid(), 'Abdullah Al-Ahrak', 'MID', 'QAT', 'wk'),
(gen_random_uuid(), 'Ismail Mohamad', 'MID', 'QAT', 'wk'),
(gen_random_uuid(), 'Ahmed Alaaeldin', 'MID', 'QAT', 'wk'),
(gen_random_uuid(), 'Akram Afif', 'AAN', 'QAT', 'wk'),
(gen_random_uuid(), 'Almoez Ali', 'AAN', 'QAT', 'wk'),
(gen_random_uuid(), 'Mohammed Muntari', 'AAN', 'QAT', 'wk'),
(gen_random_uuid(), 'Hasan Al-Haydos', 'AAN', 'QAT', 'wk'),
(gen_random_uuid(), 'Yusuf Abdurisag', 'AAN', 'QAT', 'wk'),
(gen_random_uuid(), 'Salem Al-Hajri', 'AAN', 'QAT', 'wk'),

-- Ecuador
(gen_random_uuid(), 'Hernán Galíndez', 'DOE', 'ECU', 'wk'),
(gen_random_uuid(), 'Alexander Domínguez', 'DOE', 'ECU', 'wk'),
(gen_random_uuid(), 'Moisés Ramírez', 'DOE', 'ECU', 'wk'),
(gen_random_uuid(), 'Piero Hincapié', 'VER', 'ECU', 'wk'),
(gen_random_uuid(), 'Félix Torres', 'VER', 'ECU', 'wk'),
(gen_random_uuid(), 'Diego Palacios', 'VER', 'ECU', 'wk'),
(gen_random_uuid(), 'Angelo Preciado', 'VER', 'ECU', 'wk'),
(gen_random_uuid(), 'William Pacho', 'VER', 'ECU', 'wk'),
(gen_random_uuid(), 'Jackson Porozo', 'VER', 'ECU', 'wk'),
(gen_random_uuid(), 'Moisés Caicedo', 'MID', 'ECU', 'wk'),
(gen_random_uuid(), 'Carlos Gruezo', 'MID', 'ECU', 'wk'),
(gen_random_uuid(), 'Jeremy Sarmiento', 'MID', 'ECU', 'wk'),
(gen_random_uuid(), 'Kendry Páez', 'MID', 'ECU', 'wk'),
(gen_random_uuid(), 'Alan Minda', 'MID', 'ECU', 'wk'),
(gen_random_uuid(), 'Gonzalo Plata', 'AAN', 'ECU', 'wk'),
(gen_random_uuid(), 'Enner Valencia', 'AAN', 'ECU', 'wk'),
(gen_random_uuid(), 'Kevin Rodríguez', 'AAN', 'ECU', 'wk'),
(gen_random_uuid(), 'Djorkaeff Reasco', 'AAN', 'ECU', 'wk'),
(gen_random_uuid(), 'Jordan Rezabala', 'AAN', 'ECU', 'wk'),

-- Senegal
(gen_random_uuid(), 'Edouard Mendy', 'DOE', 'SEN', 'wk'),
(gen_random_uuid(), 'Seny Dieng', 'DOE', 'SEN', 'wk'),
(gen_random_uuid(), 'Alfred Gomis', 'DOE', 'SEN', 'wk'),
(gen_random_uuid(), 'Kalidou Koulibaly', 'VER', 'SEN', 'wk'),
(gen_random_uuid(), 'Abdou Diallo', 'VER', 'SEN', 'wk'),
(gen_random_uuid(), 'Youssouf Sabaly', 'VER', 'SEN', 'wk'),
(gen_random_uuid(), 'Formose Mendy', 'VER', 'SEN', 'wk'),
(gen_random_uuid(), 'Ismail Jakobs', 'VER', 'SEN', 'wk'),
(gen_random_uuid(), 'Pape Abou Cissé', 'VER', 'SEN', 'wk'),
(gen_random_uuid(), 'Idrissa Gueye', 'MID', 'SEN', 'wk'),
(gen_random_uuid(), 'Nampalys Mendy', 'MID', 'SEN', 'wk'),
(gen_random_uuid(), 'Cheikhou Kouyaté', 'MID', 'SEN', 'wk'),
(gen_random_uuid(), 'Pathé Ciss', 'MID', 'SEN', 'wk'),
(gen_random_uuid(), 'Lamine Camara', 'MID', 'SEN', 'wk'),
(gen_random_uuid(), 'Sadio Mané', 'AAN', 'SEN', 'wk'),
(gen_random_uuid(), 'Ismaila Sarr', 'AAN', 'SEN', 'wk'),
(gen_random_uuid(), 'Boulaye Dia', 'AAN', 'SEN', 'wk'),
(gen_random_uuid(), 'Nicolas Jackson', 'AAN', 'SEN', 'wk'),
(gen_random_uuid(), 'Habib Diallo', 'AAN', 'SEN', 'wk'),

-- Netherlands
(gen_random_uuid(), 'Bart Verbruggen', 'DOE', 'NED', 'wk'),
(gen_random_uuid(), 'Mark Flekken', 'DOE', 'NED', 'wk'),
(gen_random_uuid(), 'Remko Pasveer', 'DOE', 'NED', 'wk'),
(gen_random_uuid(), 'Virgil van Dijk', 'VER', 'NED', 'wk'),
(gen_random_uuid(), 'Matthijs de Ligt', 'VER', 'NED', 'wk'),
(gen_random_uuid(), 'Jurriën Timber', 'VER', 'NED', 'wk'),
(gen_random_uuid(), 'Denzel Dumfries', 'VER', 'NED', 'wk'),
(gen_random_uuid(), 'Nathan Aké', 'VER', 'NED', 'wk'),
(gen_random_uuid(), 'Stefan de Vrij', 'VER', 'NED', 'wk'),
(gen_random_uuid(), 'Frenkie de Jong', 'MID', 'NED', 'wk'),
(gen_random_uuid(), 'Tijjani Reijnders', 'MID', 'NED', 'wk'),
(gen_random_uuid(), 'Mats Wieffer', 'MID', 'NED', 'wk'),
(gen_random_uuid(), 'Ryan Gravenberch', 'MID', 'NED', 'wk'),
(gen_random_uuid(), 'Quinten Timber', 'MID', 'NED', 'wk'),
(gen_random_uuid(), 'Cody Gakpo', 'AAN', 'NED', 'wk'),
(gen_random_uuid(), 'Memphis Depay', 'AAN', 'NED', 'wk'),
(gen_random_uuid(), 'Donyell Malen', 'AAN', 'NED', 'wk'),
(gen_random_uuid(), 'Wout Weghorst', 'AAN', 'NED', 'wk'),
(gen_random_uuid(), 'Xavi Simons', 'AAN', 'NED', 'wk'),
(gen_random_uuid(), 'Brian Brobbey', 'AAN', 'NED', 'wk'),

-- Group B: England, Iran, USA, Wales
-- England
(gen_random_uuid(), 'Jordan Pickford', 'DOE', 'ENG', 'wk'),
(gen_random_uuid(), 'Aaron Ramsdale', 'DOE', 'ENG', 'wk'),
(gen_random_uuid(), 'Nick Pope', 'DOE', 'ENG', 'wk'),
(gen_random_uuid(), 'Kyle Walker', 'VER', 'ENG', 'wk'),
(gen_random_uuid(), 'John Stones', 'VER', 'ENG', 'wk'),
(gen_random_uuid(), 'Harry Maguire', 'VER', 'ENG', 'wk'),
(gen_random_uuid(), 'Luke Shaw', 'VER', 'ENG', 'wk'),
(gen_random_uuid(), 'Kieran Trippier', 'VER', 'ENG', 'wk'),
(gen_random_uuid(), 'Trent Alexander-Arnold', 'VER', 'ENG', 'wk'),
(gen_random_uuid(), 'Declan Rice', 'MID', 'ENG', 'wk'),
(gen_random_uuid(), 'Jude Bellingham', 'MID', 'ENG', 'wk'),
(gen_random_uuid(), 'Jordan Henderson', 'MID', 'ENG', 'wk'),
(gen_random_uuid(), 'Mason Mount', 'MID', 'ENG', 'wk'),
(gen_random_uuid(), 'Conor Gallagher', 'MID', 'ENG', 'wk'),
(gen_random_uuid(), 'Harry Kane', 'AAN', 'ENG', 'wk'),
(gen_random_uuid(), 'Bukayo Saka', 'AAN', 'ENG', 'wk'),
(gen_random_uuid(), 'Raheem Sterling', 'AAN', 'ENG', 'wk'),
(gen_random_uuid(), 'Marcus Rashford', 'AAN', 'ENG', 'wk'),
(gen_random_uuid(), 'Phil Foden', 'AAN', 'ENG', 'wk'),
(gen_random_uuid(), 'Jack Grealish', 'AAN', 'ENG', 'wk'),

-- Iran
(gen_random_uuid(), 'Alireza Beiranvand', 'DOE', 'IRN', 'wk'),
(gen_random_uuid(), 'Hossein Hosseini', 'DOE', 'IRN', 'wk'),
(gen_random_uuid(), 'Payam Niazmand', 'DOE', 'IRN', 'wk'),
(gen_random_uuid(), 'Shoja Khalilzadeh', 'VER', 'IRN', 'wk'),
(gen_random_uuid(), 'Majid Hosseini', 'VER', 'IRN', 'wk'),
(gen_random_uuid(), 'Ehsan Hajsafi', 'VER', 'IRN', 'wk'),
(gen_random_uuid(), 'Milad Mohammadi', 'VER', 'IRN', 'wk'),
(gen_random_uuid(), 'Ramin Rezaeian', 'VER', 'IRN', 'wk'),
(gen_random_uuid(), 'Sadegh Moharrami', 'VER', 'IRN', 'wk'),
(gen_random_uuid(), 'Saeid Ezatolahi', 'MID', 'IRN', 'wk'),
(gen_random_uuid(), 'Ahmad Noorollahi', 'MID', 'IRN', 'wk'),
(gen_random_uuid(), 'Ali Karimi', 'MID', 'IRN', 'wk'),
(gen_random_uuid(), 'Vahid Amiri', 'MID', 'IRN', 'wk'),
(gen_random_uuid(), 'Alireza Jahanbakhsh', 'AAN', 'IRN', 'wk'),
(gen_random_uuid(), 'Mehdi Taremi', 'AAN', 'IRN', 'wk'),
(gen_random_uuid(), 'Sardar Azmoun', 'AAN', 'IRN', 'wk'),
(gen_random_uuid(), 'Karim Ansarifard', 'AAN', 'IRN', 'wk'),
(gen_random_uuid(), 'Allahyar Sayyadmanesh', 'AAN', 'IRN', 'wk'),

-- USA
(gen_random_uuid(), 'Matt Turner', 'DOE', 'USA', 'wk'),
(gen_random_uuid(), 'Ethan Horvath', 'DOE', 'USA', 'wk'),
(gen_random_uuid(), 'Sean Johnson', 'DOE', 'USA', 'wk'),
(gen_random_uuid(), 'Sergino Dest', 'VER', 'USA', 'wk'),
(gen_random_uuid(), 'Walker Zimmerman', 'VER', 'USA', 'wk'),
(gen_random_uuid(), 'Miles Robinson', 'VER', 'USA', 'wk'),
(gen_random_uuid(), 'Tim Ream', 'VER', 'USA', 'wk'),
(gen_random_uuid(), 'Joe Scally', 'VER', 'USA', 'wk'),
(gen_random_uuid(), 'Chris Richards', 'VER', 'USA', 'wk'),
(gen_random_uuid(), 'Tyler Adams', 'MID', 'USA', 'wk'),
(gen_random_uuid(), 'Weston McKennie', 'MID', 'USA', 'wk'),
(gen_random_uuid(), 'Yunus Musah', 'MID', 'USA', 'wk'),
(gen_random_uuid(), 'Luca de la Torre', 'MID', 'USA', 'wk'),
(gen_random_uuid(), 'Brenden Aaronson', 'MID', 'USA', 'wk'),
(gen_random_uuid(), 'Christian Pulisic', 'AAN', 'USA', 'wk'),
(gen_random_uuid(), 'Timothy Weah', 'AAN', 'USA', 'wk'),
(gen_random_uuid(), 'Josh Sargent', 'AAN', 'USA', 'wk'),
(gen_random_uuid(), 'Ricardo Pepi', 'AAN', 'USA', 'wk'),
(gen_random_uuid(), 'Folarin Balogun', 'AAN', 'USA', 'wk'),
(gen_random_uuid(), 'Jesús Ferreira', 'AAN', 'USA', 'wk'),

-- Wales
(gen_random_uuid(), 'Wayne Hennessey', 'DOE', 'WAL', 'wk'),
(gen_random_uuid(), 'Danny Ward', 'DOE', 'WAL', 'wk'),
(gen_random_uuid(), 'Adam Davies', 'DOE', 'WAL', 'wk'),
(gen_random_uuid(), 'Ben Davies', 'VER', 'WAL', 'wk'),
(gen_random_uuid(), 'Chris Mepham', 'VER', 'WAL', 'wk'),
(gen_random_uuid(), 'Neco Williams', 'VER', 'WAL', 'wk'),
(gen_random_uuid(), 'Connor Roberts', 'VER', 'WAL', 'wk'),
(gen_random_uuid(), 'Tom Lockyer', 'VER', 'WAL', 'wk'),
(gen_random_uuid(), 'Ethan Ampadu', 'MID', 'WAL', 'wk'),
(gen_random_uuid(), 'Joe Allen', 'MID', 'WAL', 'wk'),
(gen_random_uuid(), 'Aaron Ramsey', 'MID', 'WAL', 'wk'),
(gen_random_uuid(), 'Harry Wilson', 'MID', 'WAL', 'wk'),
(gen_random_uuid(), 'Dylan Levitt', 'MID', 'WAL', 'wk'),
(gen_random_uuid(), 'Gareth Bale', 'AAN', 'WAL', 'wk'),
(gen_random_uuid(), 'Kieffer Moore', 'AAN', 'WAL', 'wk'),
(gen_random_uuid(), 'Daniel James', 'AAN', 'WAL', 'wk'),
(gen_random_uuid(), 'Brennan Johnson', 'AAN', 'WAL', 'wk'),
(gen_random_uuid(), 'Mark Harris', 'AAN', 'WAL', 'wk'),

-- Group C: Argentina, Saudi Arabia, Mexico, Poland
-- Argentina
(gen_random_uuid(), 'Emiliano Martínez', 'DOE', 'ARG', 'wk'),
(gen_random_uuid(), 'Geronimo Rulli', 'DOE', 'ARG', 'wk'),
(gen_random_uuid(), 'Franco Armani', 'DOE', 'ARG', 'wk'),
(gen_random_uuid(), 'Nahuel Molina', 'VER', 'ARG', 'wk'),
(gen_random_uuid(), 'Cristian Romero', 'VER', 'ARG', 'wk'),
(gen_random_uuid(), 'Nicolás Otamendi', 'VER', 'ARG', 'wk'),
(gen_random_uuid(), 'Marcos Acuña', 'VER', 'ARG', 'wk'),
(gen_random_uuid(), 'Lisandro Martínez', 'VER', 'ARG', 'wk'),
(gen_random_uuid(), 'Nicolás Tagliafico', 'VER', 'ARG', 'wk'),
(gen_random_uuid(), 'Rodrigo De Paul', 'MID', 'ARG', 'wk'),
(gen_random_uuid(), 'Enzo Fernández', 'MID', 'ARG', 'wk'),
(gen_random_uuid(), 'Leandro Paredes', 'MID', 'ARG', 'wk'),
(gen_random_uuid(), 'Alexis Mac Allister', 'MID', 'ARG', 'wk'),
(gen_random_uuid(), 'Exequiel Palacios', 'MID', 'ARG', 'wk'),
(gen_random_uuid(), 'Lionel Messi', 'AAN', 'ARG', 'wk'),
(gen_random_uuid(), 'Lautaro Martínez', 'AAN', 'ARG', 'wk'),
(gen_random_uuid(), 'Julián Álvarez', 'AAN', 'ARG', 'wk'),
(gen_random_uuid(), 'Ángel Correa', 'AAN', 'ARG', 'wk'),
(gen_random_uuid(), 'Nicolás González', 'AAN', 'ARG', 'wk'),
(gen_random_uuid(), 'Paulo Dybala', 'AAN', 'ARG', 'wk'),

-- Saudi Arabia
(gen_random_uuid(), 'Mohammed Al-Owais', 'DOE', 'KSA', 'wk'),
(gen_random_uuid(), 'Fawaz Al-Qarni', 'DOE', 'KSA', 'wk'),
(gen_random_uuid(), 'Yasser Al-Mosailem', 'DOE', 'KSA', 'wk'),
(gen_random_uuid(), 'Saud Abdulhamid', 'VER', 'KSA', 'wk'),
(gen_random_uuid(), 'Ali Al-Bulaihi', 'VER', 'KSA', 'wk'),
(gen_random_uuid(), 'Sultan Al-Ghannam', 'VER', 'KSA', 'wk'),
(gen_random_uuid(), 'Hassan Al-Tambakti', 'VER', 'KSA', 'wk'),
(gen_random_uuid(), 'Abdulellah Al-Malki', 'VER', 'KSA', 'wk'),
(gen_random_uuid(), 'Sami Al-Najei', 'MID', 'KSA', 'wk'),
(gen_random_uuid(), 'Mohamed Kanno', 'MID', 'KSA', 'wk'),
(gen_random_uuid(), 'Ali Al-Hassan', 'MID', 'KSA', 'wk'),
(gen_random_uuid(), 'Saleh Al-Shehri', 'AAN', 'KSA', 'wk'),
(gen_random_uuid(), 'Salem Al-Dawsari', 'AAN', 'KSA', 'wk'),
(gen_random_uuid(), 'Firas Al-Buraikan', 'AAN', 'KSA', 'wk'),
(gen_random_uuid(), 'Haitham Asiri', 'AAN', 'KSA', 'wk'),
(gen_random_uuid(), 'Abdullah Al-Hamdan', 'AAN', 'KSA', 'wk'),

-- Mexico
(gen_random_uuid(), 'Guillermo Ochoa', 'DOE', 'MEX', 'wk'),
(gen_random_uuid(), 'Alfredo Talavera', 'DOE', 'MEX', 'wk'),
(gen_random_uuid(), 'Carlos Acevedo', 'DOE', 'MEX', 'wk'),
(gen_random_uuid(), 'César Montes', 'VER', 'MEX', 'wk'),
(gen_random_uuid(), 'Héctor Moreno', 'VER', 'MEX', 'wk'),
(gen_random_uuid(), 'Jorge Sánchez', 'VER', 'MEX', 'wk'),
(gen_random_uuid(), 'Gerardo Arteaga', 'VER', 'MEX', 'wk'),
(gen_random_uuid(), 'Jesús Gallardo', 'VER', 'MEX', 'wk'),
(gen_random_uuid(), 'Johan Vásquez', 'VER', 'MEX', 'wk'),
(gen_random_uuid(), 'Héctor Herrera', 'MID', 'MEX', 'wk'),
(gen_random_uuid(), 'Edson Álvarez', 'MID', 'MEX', 'wk'),
(gen_random_uuid(), 'Luis Romo', 'MID', 'MEX', 'wk'),
(gen_random_uuid(), 'Érick Gutiérrez', 'MID', 'MEX', 'wk'),
(gen_random_uuid(), 'Sebastián Córdova', 'MID', 'MEX', 'wk'),
(gen_random_uuid(), 'Hirving Lozano', 'AAN', 'MEX', 'wk'),
(gen_random_uuid(), 'Raúl Jiménez', 'AAN', 'MEX', 'wk'),
(gen_random_uuid(), 'Henry Martín', 'AAN', 'MEX', 'wk'),
(gen_random_uuid(), 'Alexis Vega', 'AAN', 'MEX', 'wk'),
(gen_random_uuid(), 'Uriel Antuna', 'AAN', 'MEX', 'wk'),
(gen_random_uuid(), 'Rogelio Funes Mori', 'AAN', 'MEX', 'wk'),

-- Poland
(gen_random_uuid(), 'Wojciech Szczęsny', 'DOE', 'POL', 'wk'),
(gen_random_uuid(), 'Łukasz Skorupski', 'DOE', 'POL', 'wk'),
(gen_random_uuid(), 'Kamil Grabara', 'DOE', 'POL', 'wk'),
(gen_random_uuid(), 'Matty Cash', 'VER', 'POL', 'wk'),
(gen_random_uuid(), 'Kamil Glik', 'VER', 'POL', 'wk'),
(gen_random_uuid(), 'Jan Bednarek', 'VER', 'POL', 'wk'),
(gen_random_uuid(), 'Bartosz Bereszyński', 'VER', 'POL', 'wk'),
(gen_random_uuid(), 'Maciej Rybus', 'VER', 'POL', 'wk'),
(gen_random_uuid(), 'Jakub Kiwior', 'VER', 'POL', 'wk'),
(gen_random_uuid(), 'Grzegorz Krychowiak', 'MID', 'POL', 'wk'),
(gen_random_uuid(), 'Piotr Zielinski', 'MID', 'POL', 'wk'),
(gen_random_uuid(), 'Krzysztof Piątek', 'MID', 'POL', 'wk'),
(gen_random_uuid(), 'Sebastian Szymanski', 'MID', 'POL', 'wk'),
(gen_random_uuid(), 'Jakub Moder', 'MID', 'POL', 'wk'),
(gen_random_uuid(), 'Robert Lewandowski', 'AAN', 'POL', 'wk'),
(gen_random_uuid(), 'Arkadiusz Milik', 'AAN', 'POL', 'wk'),
(gen_random_uuid(), 'Karol Świderski', 'AAN', 'POL', 'wk'),
(gen_random_uuid(), 'Kamil Grosicki', 'AAN', 'POL', 'wk'),
(gen_random_uuid(), 'Michał Skóraś', 'AAN', 'POL', 'wk'),

-- Group D: France, Australia, Denmark, Tunisia
-- France
(gen_random_uuid(), 'Hugo Lloris', 'DOE', 'FRA', 'wk'),
(gen_random_uuid(), 'Mike Maignan', 'DOE', 'FRA', 'wk'),
(gen_random_uuid(), 'Alphonse Areola', 'DOE', 'FRA', 'wk'),
(gen_random_uuid(), 'Benjamin Pavard', 'VER', 'FRA', 'wk'),
(gen_random_uuid(), 'Raphaël Varane', 'VER', 'FRA', 'wk'),
(gen_random_uuid(), 'Lucas Hernández', 'VER', 'FRA', 'wk'),
(gen_random_uuid(), 'Théo Hernández', 'VER', 'FRA', 'wk'),
(gen_random_uuid(), 'Dayot Upamecano', 'VER', 'FRA', 'wk'),
(gen_random_uuid(), 'Jules Koundé', 'VER', 'FRA', 'wk'),
(gen_random_uuid(), 'Aurélien Tchouaméni', 'MID', 'FRA', 'wk'),
(gen_random_uuid(), 'Adrien Rabiot', 'MID', 'FRA', 'wk'),
(gen_random_uuid(), 'Antoine Griezmann', 'MID', 'FRA', 'wk'),
(gen_random_uuid(), 'Eduardo Camavinga', 'MID', 'FRA', 'wk'),
(gen_random_uuid(), 'Youssouf Fofana', 'MID', 'FRA', 'wk'),
(gen_random_uuid(), 'Kylian Mbappé', 'AAN', 'FRA', 'wk'),
(gen_random_uuid(), 'Olivier Giroud', 'AAN', 'FRA', 'wk'),
(gen_random_uuid(), 'Marcus Thuram', 'AAN', 'FRA', 'wk'),
(gen_random_uuid(), 'Ousmane Dembélé', 'AAN', 'FRA', 'wk'),
(gen_random_uuid(), 'Randal Kolo Muani', 'AAN', 'FRA', 'wk'),
(gen_random_uuid(), 'Kingsley Coman', 'AAN', 'FRA', 'wk'),

-- Australia
(gen_random_uuid(), 'Mat Ryan', 'DOE', 'AUS', 'wk'),
(gen_random_uuid(), 'Andrew Redmayne', 'DOE', 'AUS', 'wk'),
(gen_random_uuid(), 'Danny Vukovic', 'DOE', 'AUS', 'wk'),
(gen_random_uuid(), 'Harry Souttar', 'VER', 'AUS', 'wk'),
(gen_random_uuid(), 'Milos Degenek', 'VER', 'AUS', 'wk'),
(gen_random_uuid(), 'Aziz Behich', 'VER', 'AUS', 'wk'),
(gen_random_uuid(), 'Nathaniel Atkinson', 'VER', 'AUS', 'wk'),
(gen_random_uuid(), 'Fran Karačić', 'VER', 'AUS', 'wk'),
(gen_random_uuid(), 'Kye Rowles', 'VER', 'AUS', 'wk'),
(gen_random_uuid(), 'Aaron Mooy', 'MID', 'AUS', 'wk'),
(gen_random_uuid(), 'Jackson Irvine', 'MID', 'AUS', 'wk'),
(gen_random_uuid(), 'Riley McGree', 'MID', 'AUS', 'wk'),
(gen_random_uuid(), 'Ajdin Hrustic', 'MID', 'AUS', 'wk'),
(gen_random_uuid(), 'Cameron Devlin', 'MID', 'AUS', 'wk'),
(gen_random_uuid(), 'Mathew Leckie', 'AAN', 'AUS', 'wk'),
(gen_random_uuid(), 'Mitchell Duke', 'AAN', 'AUS', 'wk'),
(gen_random_uuid(), 'Martin Boyle', 'AAN', 'AUS', 'wk'),
(gen_random_uuid(), 'Craig Goodwin', 'AAN', 'AUS', 'wk'),
(gen_random_uuid(), 'Jamie Maclaren', 'AAN', 'AUS', 'wk'),

-- Denmark
(gen_random_uuid(), 'Kasper Schmeichel', 'DOE', 'DEN', 'wk'),
(gen_random_uuid(), 'Frederik Rønnow', 'DOE', 'DEN', 'wk'),
(gen_random_uuid(), 'Oliver Christensen', 'DOE', 'DEN', 'wk'),
(gen_random_uuid(), 'Simon Kjær', 'VER', 'DEN', 'wk'),
(gen_random_uuid(), 'Andreas Christensen', 'VER', 'DEN', 'wk'),
(gen_random_uuid(), 'Joachim Andersen', 'VER', 'DEN', 'wk'),
(gen_random_uuid(), 'Jens Stryger Larsen', 'VER', 'DEN', 'wk'),
(gen_random_uuid(), 'Alexander Bah', 'VER', 'DEN', 'wk'),
(gen_random_uuid(), 'Victor Nelsson', 'VER', 'DEN', 'wk'),
(gen_random_uuid(), 'Christian Eriksen', 'MID', 'DEN', 'wk'),
(gen_random_uuid(), 'Pierre-Emile Højbjerg', 'MID', 'DEN', 'wk'),
(gen_random_uuid(), 'Thomas Delaney', 'MID', 'DEN', 'wk'),
(gen_random_uuid(), 'Mathias Jensen', 'MID', 'DEN', 'wk'),
(gen_random_uuid(), 'Mikkel Damsgaard', 'MID', 'DEN', 'wk'),
(gen_random_uuid(), 'Martin Braithwaite', 'AAN', 'DEN', 'wk'),
(gen_random_uuid(), 'Andreas Skov Olsen', 'AAN', 'DEN', 'wk'),
(gen_random_uuid(), 'Kasper Dolberg', 'AAN', 'DEN', 'wk'),
(gen_random_uuid(), 'Jonas Wind', 'AAN', 'DEN', 'wk'),
(gen_random_uuid(), 'Jesper Lindstrøm', 'AAN', 'DEN', 'wk'),

-- Tunisia
(gen_random_uuid(), 'Aymen Dahmen', 'DOE', 'TUN', 'wk'),
(gen_random_uuid(), 'Mouez Hassen', 'DOE', 'TUN', 'wk'),
(gen_random_uuid(), 'Béchir Ben Said', 'DOE', 'TUN', 'wk'),
(gen_random_uuid(), 'Dylan Bronn', 'VER', 'TUN', 'wk'),
(gen_random_uuid(), 'Montassar Talbi', 'VER', 'TUN', 'wk'),
(gen_random_uuid(), 'Ali Maaloul', 'VER', 'TUN', 'wk'),
(gen_random_uuid(), 'Mohamed Draeger', 'VER', 'TUN', 'wk'),
(gen_random_uuid(), 'Nader Ghandri', 'VER', 'TUN', 'wk'),
(gen_random_uuid(), 'Wajdi Kechrida', 'VER', 'TUN', 'wk'),
(gen_random_uuid(), 'Anis Slimane', 'MID', 'TUN', 'wk'),
(gen_random_uuid(), 'Ellyes Skhiri', 'MID', 'TUN', 'wk'),
(gen_random_uuid(), 'Ghaylen Chaalali', 'MID', 'TUN', 'wk'),
(gen_random_uuid(), 'Hannibal Mejbri', 'MID', 'TUN', 'wk'),
(gen_random_uuid(), 'Youssef Msakni', 'AAN', 'TUN', 'wk'),
(gen_random_uuid(), 'Wahbi Khazri', 'AAN', 'TUN', 'wk'),
(gen_random_uuid(), 'Seifeddine Jaziri', 'AAN', 'TUN', 'wk'),
(gen_random_uuid(), 'Issam Jebali', 'AAN', 'TUN', 'wk'),
(gen_random_uuid(), 'Taha Yassine Khenissi', 'AAN', 'TUN', 'wk'),

-- Group E: Spain, Costa Rica, Germany, Japan
-- Spain
(gen_random_uuid(), 'Unai Simón', 'DOE', 'ESP', 'wk'),
(gen_random_uuid(), 'Robert Sánchez', 'DOE', 'ESP', 'wk'),
(gen_random_uuid(), 'David Raya', 'DOE', 'ESP', 'wk'),
(gen_random_uuid(), 'Dani Carvajal', 'VER', 'ESP', 'wk'),
(gen_random_uuid(), 'Pau Torres', 'VER', 'ESP', 'wk'),
(gen_random_uuid(), 'Aymeric Laporte', 'VER', 'ESP', 'wk'),
(gen_random_uuid(), 'Jordi Alba', 'VER', 'ESP', 'wk'),
(gen_random_uuid(), 'César Azpilicueta', 'VER', 'ESP', 'wk'),
(gen_random_uuid(), 'Eric García', 'VER', 'ESP', 'wk'),
(gen_random_uuid(), 'Sergio Busquets', 'MID', 'ESP', 'wk'),
(gen_random_uuid(), 'Pedri', 'MID', 'ESP', 'wk'),
(gen_random_uuid(), 'Gavi', 'MID', 'ESP', 'wk'),
(gen_random_uuid(), 'Koke', 'MID', 'ESP', 'wk'),
(gen_random_uuid(), 'Carlos Soler', 'MID', 'ESP', 'wk'),
(gen_random_uuid(), 'Álvaro Morata', 'AAN', 'ESP', 'wk'),
(gen_random_uuid(), 'Ferran Torres', 'AAN', 'ESP', 'wk'),
(gen_random_uuid(), 'Dani Olmo', 'AAN', 'ESP', 'wk'),
(gen_random_uuid(), 'Marco Asensio', 'AAN', 'ESP', 'wk'),
(gen_random_uuid(), 'Ansu Fati', 'AAN', 'ESP', 'wk'),
(gen_random_uuid(), 'Yeremy Pino', 'AAN', 'ESP', 'wk'),

-- Costa Rica
(gen_random_uuid(), 'Keylor Navas', 'DOE', 'CRC', 'wk'),
(gen_random_uuid(), 'Patrick Sequeira', 'DOE', 'CRC', 'wk'),
(gen_random_uuid(), 'Esteban Alvarado', 'DOE', 'CRC', 'wk'),
(gen_random_uuid(), 'Bryan Ruiz', 'VER', 'CRC', 'wk'),
(gen_random_uuid(), 'Óscar Duarte', 'VER', 'CRC', 'wk'),
(gen_random_uuid(), 'Keysher Fuller', 'VER', 'CRC', 'wk'),
(gen_random_uuid(), 'Bryan Oviedo', 'VER', 'CRC', 'wk'),
(gen_random_uuid(), 'Francisco Calvo', 'VER', 'CRC', 'wk'),
(gen_random_uuid(), 'Carlos Martínez', 'VER', 'CRC', 'wk'),
(gen_random_uuid(), 'Celso Borges', 'MID', 'CRC', 'wk'),
(gen_random_uuid(), 'Yeltsin Tejeda', 'MID', 'CRC', 'wk'),
(gen_random_uuid(), 'Rándall Leal', 'MID', 'CRC', 'wk'),
(gen_random_uuid(), 'Cristian Gamboa', 'MID', 'CRC', 'wk'),
(gen_random_uuid(), 'Joel Campbell', 'AAN', 'CRC', 'wk'),
(gen_random_uuid(), 'Alonso Martínez', 'AAN', 'CRC', 'wk'),
(gen_random_uuid(), 'Anthony Contreras', 'AAN', 'CRC', 'wk'),
(gen_random_uuid(), 'Johan Venegas', 'AAN', 'CRC', 'wk'),

-- Germany
(gen_random_uuid(), 'Manuel Neuer', 'DOE', 'GER', 'wk'),
(gen_random_uuid(), 'Marc-André ter Stegen', 'DOE', 'GER', 'wk'),
(gen_random_uuid(), 'Kevin Trapp', 'DOE', 'GER', 'wk'),
(gen_random_uuid(), 'Joshua Kimmich', 'VER', 'GER', 'wk'),
(gen_random_uuid(), 'Antonio Rüdiger', 'VER', 'GER', 'wk'),
(gen_random_uuid(), 'David Raum', 'VER', 'GER', 'wk'),
(gen_random_uuid(), 'Thilo Kehrer', 'VER', 'GER', 'wk'),
(gen_random_uuid(), 'Nico Schlotterbeck', 'VER', 'GER', 'wk'),
(gen_random_uuid(), 'Benjamin Henrichs', 'VER', 'GER', 'wk'),
(gen_random_uuid(), 'Leon Goretzka', 'MID', 'GER', 'wk'),
(gen_random_uuid(), 'Kai Havertz', 'MID', 'GER', 'wk'),
(gen_random_uuid(), 'Jamal Musiala', 'MID', 'GER', 'wk'),
(gen_random_uuid(), 'Florian Wirtz', 'MID', 'GER', 'wk'),
(gen_random_uuid(), 'Jonas Hofmann', 'MID', 'GER', 'wk'),
(gen_random_uuid(), 'Serge Gnabry', 'AAN', 'GER', 'wk'),
(gen_random_uuid(), 'Thomas Müller', 'AAN', 'GER', 'wk'),
(gen_random_uuid(), 'Leroy Sané', 'AAN', 'GER', 'wk'),
(gen_random_uuid(), 'Niclas Füllkrug', 'AAN', 'GER', 'wk'),
(gen_random_uuid(), 'Lukas Nmecha', 'AAN', 'GER', 'wk'),

-- Japan
(gen_random_uuid(), 'Shuichi Gonda', 'DOE', 'JPN', 'wk'),
(gen_random_uuid(), 'Daniel Schmidt', 'DOE', 'JPN', 'wk'),
(gen_random_uuid(), 'Kosei Tani', 'DOE', 'JPN', 'wk'),
(gen_random_uuid(), 'Maya Yoshida', 'VER', 'JPN', 'wk'),
(gen_random_uuid(), 'Takehiro Tomiyasu', 'VER', 'JPN', 'wk'),
(gen_random_uuid(), 'Yuto Nagatomo', 'VER', 'JPN', 'wk'),
(gen_random_uuid(), 'Ko Itakura', 'VER', 'JPN', 'wk'),
(gen_random_uuid(), 'Shogo Taniguchi', 'VER', 'JPN', 'wk'),
(gen_random_uuid(), 'Hiroki Ito', 'VER', 'JPN', 'wk'),
(gen_random_uuid(), 'Wataru Endo', 'MID', 'JPN', 'wk'),
(gen_random_uuid(), 'Gaku Shibasaki', 'MID', 'JPN', 'wk'),
(gen_random_uuid(), 'Ritsu Doan', 'MID', 'JPN', 'wk'),
(gen_random_uuid(), 'Junya Ito', 'MID', 'JPN', 'wk'),
(gen_random_uuid(), 'Daichi Kamada', 'MID', 'JPN', 'wk'),
(gen_random_uuid(), 'Takumi Minamino', 'AAN', 'JPN', 'wk'),
(gen_random_uuid(), 'Kaoru Mitoma', 'AAN', 'JPN', 'wk'),
(gen_random_uuid(), 'Kyogo Furuhashi', 'AAN', 'JPN', 'wk'),
(gen_random_uuid(), 'Ao Tanaka', 'AAN', 'JPN', 'wk'),
(gen_random_uuid(), 'Ayase Ueda', 'AAN', 'JPN', 'wk'),

-- Group F: Belgium, Canada, Morocco, Croatia
-- Belgium
(gen_random_uuid(), 'Thibaut Courtois', 'DOE', 'BEL', 'wk'),
(gen_random_uuid(), 'Simon Mignolet', 'DOE', 'BEL', 'wk'),
(gen_random_uuid(), 'Koen Casteels', 'DOE', 'BEL', 'wk'),
(gen_random_uuid(), 'Toby Alderweireld', 'VER', 'BEL', 'wk'),
(gen_random_uuid(), 'Zeno Debast', 'VER', 'BEL', 'wk'),
(gen_random_uuid(), 'Thomas Meunier', 'VER', 'BEL', 'wk'),
(gen_random_uuid(), 'Arthur Theate', 'VER', 'BEL', 'wk'),
(gen_random_uuid(), 'Timothy Castagne', 'VER', 'BEL', 'wk'),
(gen_random_uuid(), 'Wout Faes', 'VER', 'BEL', 'wk'),
(gen_random_uuid(), 'Kevin De Bruyne', 'MID', 'BEL', 'wk'),
(gen_random_uuid(), 'Axel Witsel', 'MID', 'BEL', 'wk'),
(gen_random_uuid(), 'Youri Tielemans', 'MID', 'BEL', 'wk'),
(gen_random_uuid(), 'Hans Vanaken', 'MID', 'BEL', 'wk'),
(gen_random_uuid(), 'Amadou Onana', 'MID', 'BEL', 'wk'),
(gen_random_uuid(), 'Romelu Lukaku', 'AAN', 'BEL', 'wk'),
(gen_random_uuid(), 'Eden Hazard', 'AAN', 'BEL', 'wk'),
(gen_random_uuid(), 'Dodi Lukebakio', 'AAN', 'BEL', 'wk'),
(gen_random_uuid(), 'Loïs Openda', 'AAN', 'BEL', 'wk'),
(gen_random_uuid(), 'Leandro Trossard', 'AAN', 'BEL', 'wk'),

-- Canada
(gen_random_uuid(), 'Milan Borjan', 'DOE', 'CAN', 'wk'),
(gen_random_uuid(), 'Maxime Crépeau', 'DOE', 'CAN', 'wk'),
(gen_random_uuid(), 'James Pantemis', 'DOE', 'CAN', 'wk'),
(gen_random_uuid(), 'Alistair Johnston', 'VER', 'CAN', 'wk'),
(gen_random_uuid(), 'Kamal Miller', 'VER', 'CAN', 'wk'),
(gen_random_uuid(), 'Steven Vitória', 'VER', 'CAN', 'wk'),
(gen_random_uuid(), 'Derek Cornelius', 'VER', 'CAN', 'wk'),
(gen_random_uuid(), 'Sam Adekugbe', 'VER', 'CAN', 'wk'),
(gen_random_uuid(), 'Richie Laryea', 'VER', 'CAN', 'wk'),
(gen_random_uuid(), 'Atiba Hutchinson', 'MID', 'CAN', 'wk'),
(gen_random_uuid(), 'Stephen Eustáquio', 'MID', 'CAN', 'wk'),
(gen_random_uuid(), 'Jonathan Osorio', 'MID', 'CAN', 'wk'),
(gen_random_uuid(), 'Mark-Anthony Kaye', 'MID', 'CAN', 'wk'),
(gen_random_uuid(), 'Tajon Buchanan', 'AAN', 'CAN', 'wk'),
(gen_random_uuid(), 'Alphonso Davies', 'AAN', 'CAN', 'wk'),
(gen_random_uuid(), 'Jonathan David', 'AAN', 'CAN', 'wk'),
(gen_random_uuid(), 'Cyle Larin', 'AAN', 'CAN', 'wk'),
(gen_random_uuid(), 'Liam Millar', 'AAN', 'CAN', 'wk'),
(gen_random_uuid(), 'Junior Hoilett', 'AAN', 'CAN', 'wk'),

-- Morocco
(gen_random_uuid(), 'Yassine Bounou', 'DOE', 'MAR', 'wk'),
(gen_random_uuid(), 'Ahmed Reda Tagnaouti', 'DOE', 'MAR', 'wk'),
(gen_random_uuid(), 'Munir Mohamedi', 'DOE', 'MAR', 'wk'),
(gen_random_uuid(), 'Achraf Hakimi', 'VER', 'MAR', 'wk'),
(gen_random_uuid(), 'Romain Saïss', 'VER', 'MAR', 'wk'),
(gen_random_uuid(), 'Nayef Aguerd', 'VER', 'MAR', 'wk'),
(gen_random_uuid(), 'Noussair Mazraoui', 'VER', 'MAR', 'wk'),
(gen_random_uuid(), 'Jawad El Yamiq', 'VER', 'MAR', 'wk'),
(gen_random_uuid(), 'Badr Benoun', 'VER', 'MAR', 'wk'),
(gen_random_uuid(), 'Sofyan Amrabat', 'MID', 'MAR', 'wk'),
(gen_random_uuid(), 'Azzedine Ounahi', 'MID', 'MAR', 'wk'),
(gen_random_uuid(), 'Selim Amallah', 'MID', 'MAR', 'wk'),
(gen_random_uuid(), 'Bilal El Khannouss', 'MID', 'MAR', 'wk'),
(gen_random_uuid(), 'Youssef En-Nesyri', 'AAN', 'MAR', 'wk'),
(gen_random_uuid(), 'Hakim Ziyech', 'AAN', 'MAR', 'wk'),
(gen_random_uuid(), 'Abderrazak Hamdallah', 'AAN', 'MAR', 'wk'),
(gen_random_uuid(), 'Zakaria Aboukhlal', 'AAN', 'MAR', 'wk'),
(gen_random_uuid(), 'Ilias Chair', 'AAN', 'MAR', 'wk'),
(gen_random_uuid(), 'Tarik Tissoudali', 'AAN', 'MAR', 'wk'),

-- Croatia
(gen_random_uuid(), 'Dominik Livaković', 'DOE', 'CRO', 'wk'),
(gen_random_uuid(), 'Ivica Ivušić', 'DOE', 'CRO', 'wk'),
(gen_random_uuid(), 'Nediljko Labrović', 'DOE', 'CRO', 'wk'),
(gen_random_uuid(), 'Josip Juranović', 'VER', 'CRO', 'wk'),
(gen_random_uuid(), 'Domagoj Vida', 'VER', 'CRO', 'wk'),
(gen_random_uuid(), 'Joško Gvardiol', 'VER', 'CRO', 'wk'),
(gen_random_uuid(), 'Borna Sosa', 'VER', 'CRO', 'wk'),
(gen_random_uuid(), 'Šime Vrsaljko', 'VER', 'CRO', 'wk'),
(gen_random_uuid(), 'Duje Ćaleta-Car', 'VER', 'CRO', 'wk'),
(gen_random_uuid(), 'Luka Modrić', 'MID', 'CRO', 'wk'),
(gen_random_uuid(), 'Mateo Kovačić', 'MID', 'CRO', 'wk'),
(gen_random_uuid(), 'Marcelo Brozović', 'MID', 'CRO', 'wk'),
(gen_random_uuid(), 'Mario Pašalić', 'MID', 'CRO', 'wk'),
(gen_random_uuid(), 'Nikola Vlašić', 'MID', 'CRO', 'wk'),
(gen_random_uuid(), 'Andrej Kramarić', 'AAN', 'CRO', 'wk'),
(gen_random_uuid(), 'Ivan Perišić', 'AAN', 'CRO', 'wk'),
(gen_random_uuid(), 'Bruno Petković', 'AAN', 'CRO', 'wk'),
(gen_random_uuid(), 'Ante Budimir', 'AAN', 'CRO', 'wk'),
(gen_random_uuid(), 'Mislav Oršić', 'AAN', 'CRO', 'wk'),

-- Group G: Brazil, Serbia, Switzerland, Cameroon
-- Brazil
(gen_random_uuid(), 'Alisson', 'DOE', 'BRA', 'wk'),
(gen_random_uuid(), 'Ederson', 'DOE', 'BRA', 'wk'),
(gen_random_uuid(), 'Weverton', 'DOE', 'BRA', 'wk'),
(gen_random_uuid(), 'Thiago Silva', 'VER', 'BRA', 'wk'),
(gen_random_uuid(), 'Marquinhos', 'VER', 'BRA', 'wk'),
(gen_random_uuid(), 'Éder Militão', 'VER', 'BRA', 'wk'),
(gen_random_uuid(), 'Danilo', 'VER', 'BRA', 'wk'),
(gen_random_uuid(), 'Alex Sandro', 'VER', 'BRA', 'wk'),
(gen_random_uuid(), 'Bremer', 'VER', 'BRA', 'wk'),
(gen_random_uuid(), 'Casemiro', 'MID', 'BRA', 'wk'),
(gen_random_uuid(), 'Lucas Paquetá', 'MID', 'BRA', 'wk'),
(gen_random_uuid(), 'Fred', 'MID', 'BRA', 'wk'),
(gen_random_uuid(), 'Fabinho', 'MID', 'BRA', 'wk'),
(gen_random_uuid(), 'Bruno Guimarães', 'MID', 'BRA', 'wk'),
(gen_random_uuid(), 'Neymar', 'AAN', 'BRA', 'wk'),
(gen_random_uuid(), 'Vinicius Jr.', 'AAN', 'BRA', 'wk'),
(gen_random_uuid(), 'Rodrygo', 'AAN', 'BRA', 'wk'),
(gen_random_uuid(), 'Richarlison', 'AAN', 'BRA', 'wk'),
(gen_random_uuid(), 'Raphinha', 'AAN', 'BRA', 'wk'),
(gen_random_uuid(), 'Gabriel Jesus', 'AAN', 'BRA', 'wk'),

-- Serbia
(gen_random_uuid(), 'Vanja Milinković-Savić', 'DOE', 'SRB', 'wk'),
(gen_random_uuid(), 'Predrag Rajković', 'DOE', 'SRB', 'wk'),
(gen_random_uuid(), 'Marko Dmitrović', 'DOE', 'SRB', 'wk'),
(gen_random_uuid(), 'Strahinja Pavlović', 'VER', 'SRB', 'wk'),
(gen_random_uuid(), 'Nikola Milenković', 'VER', 'SRB', 'wk'),
(gen_random_uuid(), 'Stefan Mitrović', 'VER', 'SRB', 'wk'),
(gen_random_uuid(), 'Aleksandar Kolarov', 'VER', 'SRB', 'wk'),
(gen_random_uuid(), 'Filip Mladenović', 'VER', 'SRB', 'wk'),
(gen_random_uuid(), 'Srđan Babić', 'VER', 'SRB', 'wk'),
(gen_random_uuid(), 'Sergej Milinković-Savić', 'MID', 'SRB', 'wk'),
(gen_random_uuid(), 'Nemanja Gudelj', 'MID', 'SRB', 'wk'),
(gen_random_uuid(), 'Saša Lukić', 'MID', 'SRB', 'wk'),
(gen_random_uuid(), 'Darko Lazović', 'MID', 'SRB', 'wk'),
(gen_random_uuid(), 'Nemanja Radonjić', 'MID', 'SRB', 'wk'),
(gen_random_uuid(), 'Aleksandar Mitrović', 'AAN', 'SRB', 'wk'),
(gen_random_uuid(), 'Dušan Vlahović', 'AAN', 'SRB', 'wk'),
(gen_random_uuid(), 'Andrija Živković', 'AAN', 'SRB', 'wk'),
(gen_random_uuid(), 'Filip Đuričić', 'AAN', 'SRB', 'wk'),
(gen_random_uuid(), 'Aleksandar Prijović', 'AAN', 'SRB', 'wk'),

-- Switzerland
(gen_random_uuid(), 'Yann Sommer', 'DOE', 'SUI', 'wk'),
(gen_random_uuid(), 'Jonas Omlin', 'DOE', 'SUI', 'wk'),
(gen_random_uuid(), 'Gregor Kobel', 'DOE', 'SUI', 'wk'),
(gen_random_uuid(), 'Manuel Akanji', 'VER', 'SUI', 'wk'),
(gen_random_uuid(), 'Fabian Schär', 'VER', 'SUI', 'wk'),
(gen_random_uuid(), 'Nico Elvedi', 'VER', 'SUI', 'wk'),
(gen_random_uuid(), 'Ricardo Rodríguez', 'VER', 'SUI', 'wk'),
(gen_random_uuid(), 'Silvan Widmer', 'VER', 'SUI', 'wk'),
(gen_random_uuid(), 'Kevin Mbabu', 'VER', 'SUI', 'wk'),
(gen_random_uuid(), 'Granit Xhaka', 'MID', 'SUI', 'wk'),
(gen_random_uuid(), 'Remo Freuler', 'MID', 'SUI', 'wk'),
(gen_random_uuid(), 'Denis Zakaria', 'MID', 'SUI', 'wk'),
(gen_random_uuid(), 'Xherdan Shaqiri', 'MID', 'SUI', 'wk'),
(gen_random_uuid(), 'Michel Aebischer', 'MID', 'SUI', 'wk'),
(gen_random_uuid(), 'Breel Embolo', 'AAN', 'SUI', 'wk'),
(gen_random_uuid(), 'Haris Seferović', 'AAN', 'SUI', 'wk'),
(gen_random_uuid(), 'Noah Okafor', 'AAN', 'SUI', 'wk'),
(gen_random_uuid(), 'Dan Ndoye', 'AAN', 'SUI', 'wk'),
(gen_random_uuid(), 'Christian Fassnacht', 'AAN', 'SUI', 'wk'),

-- Cameroon
(gen_random_uuid(), 'André Onana', 'DOE', 'CMR', 'wk'),
(gen_random_uuid(), 'Simon Omossola', 'DOE', 'CMR', 'wk'),
(gen_random_uuid(), 'Devis Epassy', 'DOE', 'CMR', 'wk'),
(gen_random_uuid(), 'Collins Fai', 'VER', 'CMR', 'wk'),
(gen_random_uuid(), 'Nicolas Nkoulou', 'VER', 'CMR', 'wk'),
(gen_random_uuid(), 'Jean-Charles Castelletto', 'VER', 'CMR', 'wk'),
(gen_random_uuid(), 'Michael Ngadeu-Ngadjui', 'VER', 'CMR', 'wk'),
(gen_random_uuid(), 'Enzo Ebosse', 'VER', 'CMR', 'wk'),
(gen_random_uuid(), 'Nouhou Tolo', 'VER', 'CMR', 'wk'),
(gen_random_uuid(), 'André-Frank Zambo Anguissa', 'MID', 'CMR', 'wk'),
(gen_random_uuid(), 'Samuel Gouet', 'MID', 'CMR', 'wk'),
(gen_random_uuid(), 'Martin Hongla', 'MID', 'CMR', 'wk'),
(gen_random_uuid(), 'Jean Onana', 'MID', 'CMR', 'wk'),
(gen_random_uuid(), 'Gaëtan Bong', 'MID', 'CMR', 'wk'),
(gen_random_uuid(), 'Karl Toko Ekambi', 'AAN', 'CMR', 'wk'),
(gen_random_uuid(), 'Vincent Aboubakar', 'AAN', 'CMR', 'wk'),
(gen_random_uuid(), 'Stéphane Bahoken', 'AAN', 'CMR', 'wk'),
(gen_random_uuid(), 'Ignatius Ganago', 'AAN', 'CMR', 'wk'),
(gen_random_uuid(), 'Clinton Njie', 'AAN', 'CMR', 'wk'),

-- Group H: Portugal, Ghana, Uruguay, South Korea
-- Portugal
(gen_random_uuid(), 'Rui Patrício', 'DOE', 'POR', 'wk'),
(gen_random_uuid(), 'Diogo Costa', 'DOE', 'POR', 'wk'),
(gen_random_uuid(), 'José Sá', 'DOE', 'POR', 'wk'),
(gen_random_uuid(), 'João Cancelo', 'VER', 'POR', 'wk'),
(gen_random_uuid(), 'Rúben Dias', 'VER', 'POR', 'wk'),
(gen_random_uuid(), 'Pepe', 'VER', 'POR', 'wk'),
(gen_random_uuid(), 'Nuno Mendes', 'VER', 'POR', 'wk'),
(gen_random_uuid(), 'Danilo Pereira', 'VER', 'POR', 'wk'),
(gen_random_uuid(), 'Diogo Dalot', 'VER', 'POR', 'wk'),
(gen_random_uuid(), 'João Moutinho', 'MID', 'POR', 'wk'),
(gen_random_uuid(), 'Rúben Neves', 'MID', 'POR', 'wk'),
(gen_random_uuid(), 'Bernardo Silva', 'MID', 'POR', 'wk'),
(gen_random_uuid(), 'Bruno Fernandes', 'MID', 'POR', 'wk'),
(gen_random_uuid(), 'Vitinha', 'MID', 'POR', 'wk'),
(gen_random_uuid(), 'Cristiano Ronaldo', 'AAN', 'POR', 'wk'),
(gen_random_uuid(), 'João Félix', 'AAN', 'POR', 'wk'),
(gen_random_uuid(), 'Diogo Jota', 'AAN', 'POR', 'wk'),
(gen_random_uuid(), 'Rafael Leão', 'AAN', 'POR', 'wk'),
(gen_random_uuid(), 'André Silva', 'AAN', 'POR', 'wk'),
(gen_random_uuid(), 'Gonçalo Ramos', 'AAN', 'POR', 'wk'),

-- Ghana
(gen_random_uuid(), 'Lawrence Ati-Zigi', 'DOE', 'GHA', 'wk'),
(gen_random_uuid(), 'Joe Wollacott', 'DOE', 'GHA', 'wk'),
(gen_random_uuid(), 'Ibrahim Danlad', 'DOE', 'GHA', 'wk'),
(gen_random_uuid(), 'Andrew Ayew', 'VER', 'GHA', 'wk'),
(gen_random_uuid(), 'Daniel Amartey', 'VER', 'GHA', 'wk'),
(gen_random_uuid(), 'Alexander Djiku', 'VER', 'GHA', 'wk'),
(gen_random_uuid(), 'Gideon Mensah', 'VER', 'GHA', 'wk'),
(gen_random_uuid(), 'Tariq Lamptey', 'VER', 'GHA', 'wk'),
(gen_random_uuid(), 'Denis Odoi', 'VER', 'GHA', 'wk'),
(gen_random_uuid(), 'Thomas Partey', 'MID', 'GHA', 'wk'),
(gen_random_uuid(), 'Iddrisu Baba', 'MID', 'GHA', 'wk'),
(gen_random_uuid(), 'Baba Rahman', 'MID', 'GHA', 'wk'),
(gen_random_uuid(), 'Mohammed Kudus', 'MID', 'GHA', 'wk'),
(gen_random_uuid(), 'Daniel Kofi Kyereh', 'MID', 'GHA', 'wk'),
(gen_random_uuid(), 'Jordan Ayew', 'AAN', 'GHA', 'wk'),
(gen_random_uuid(), 'André Ayew', 'AAN', 'GHA', 'wk'),
(gen_random_uuid(), 'Osman Bukari', 'AAN', 'GHA', 'wk'),
(gen_random_uuid(), 'Kamaldeen Sulemana', 'AAN', 'GHA', 'wk'),
(gen_random_uuid(), 'Antoine Semenyo', 'AAN', 'GHA', 'wk'),

-- Uruguay
(gen_random_uuid(), 'Fernando Muslera', 'DOE', 'URU', 'wk'),
(gen_random_uuid(), 'Sebastián Sosa', 'DOE', 'URU', 'wk'),
(gen_random_uuid(), 'Sergio Rochet', 'DOE', 'URU', 'wk'),
(gen_random_uuid(), 'Diego Godín', 'VER', 'URU', 'wk'),
(gen_random_uuid(), 'José María Giménez', 'VER', 'URU', 'wk'),
(gen_random_uuid(), 'Ronald Araújo', 'VER', 'URU', 'wk'),
(gen_random_uuid(), 'Martín Cáceres', 'VER', 'URU', 'wk'),
(gen_random_uuid(), 'Mathías Olivera', 'VER', 'URU', 'wk'),
(gen_random_uuid(), 'Guillermo Varela', 'VER', 'URU', 'wk'),
(gen_random_uuid(), 'Federico Valverde', 'MID', 'URU', 'wk'),
(gen_random_uuid(), 'Rodrigo Bentancur', 'MID', 'URU', 'wk'),
(gen_random_uuid(), 'Lucas Torreira', 'MID', 'URU', 'wk'),
(gen_random_uuid(), 'Matías Vecino', 'MID', 'URU', 'wk'),
(gen_random_uuid(), 'Nicolás De la Cruz', 'MID', 'URU', 'wk'),
(gen_random_uuid(), 'Luis Suárez', 'AAN', 'URU', 'wk'),
(gen_random_uuid(), 'Darwin Núñez', 'AAN', 'URU', 'wk'),
(gen_random_uuid(), 'Edinson Cavani', 'AAN', 'URU', 'wk'),
(gen_random_uuid(), 'Facundo Torres', 'AAN', 'URU', 'wk'),
(gen_random_uuid(), 'Agustín Canobbio', 'AAN', 'URU', 'wk'),

-- South Korea
(gen_random_uuid(), 'Kim Seung-gyu', 'DOE', 'KOR', 'wk'),
(gen_random_uuid(), 'Jo Hyeon-woo', 'DOE', 'KOR', 'wk'),
(gen_random_uuid(), 'Song Bum-keun', 'DOE', 'KOR', 'wk'),
(gen_random_uuid(), 'Kim Min-jae', 'VER', 'KOR', 'wk'),
(gen_random_uuid(), 'Kim Young-gwon', 'VER', 'KOR', 'wk'),
(gen_random_uuid(), 'Kim Jin-su', 'VER', 'KOR', 'wk'),
(gen_random_uuid(), 'Kim Moon-hwan', 'VER', 'KOR', 'wk'),
(gen_random_uuid(), 'Lee Ki-je', 'VER', 'KOR', 'wk'),
(gen_random_uuid(), 'Kwon Kyung-won', 'VER', 'KOR', 'wk'),
(gen_random_uuid(), 'Hwang In-beom', 'MID', 'KOR', 'wk'),
(gen_random_uuid(), 'Jung Woo-young', 'MID', 'KOR', 'wk'),
(gen_random_uuid(), 'Lee Jae-sung', 'MID', 'KOR', 'wk'),
(gen_random_uuid(), 'Paik Seung-ho', 'MID', 'KOR', 'wk'),
(gen_random_uuid(), 'Son Jun-ho', 'MID', 'KOR', 'wk'),
(gen_random_uuid(), 'Son Heung-min', 'AAN', 'KOR', 'wk'),
(gen_random_uuid(), 'Hwang Hee-chan', 'AAN', 'KOR', 'wk'),
(gen_random_uuid(), 'Hwang Ui-jo', 'AAN', 'KOR', 'wk'),
(gen_random_uuid(), 'Lee Kang-in', 'AAN', 'KOR', 'wk'),
(gen_random_uuid(), 'Cho Gue-sung', 'AAN', 'KOR', 'wk'),

-- Group I: Sweden, Norway, Finland, Slovakia
-- Sweden
(gen_random_uuid(), 'Robin Olsen', 'DOE', 'SWE', 'wk'),
(gen_random_uuid(), 'Karl-Johan Johnsson', 'DOE', 'SWE', 'wk'),
(gen_random_uuid(), 'Kristoffer Nordfeldt', 'DOE', 'SWE', 'wk'),
(gen_random_uuid(), 'Victor Lindelöf', 'VER', 'SWE', 'wk'),
(gen_random_uuid(), 'Ludwig Augustinsson', 'VER', 'SWE', 'wk'),
(gen_random_uuid(), 'Filip Helander', 'VER', 'SWE', 'wk'),
(gen_random_uuid(), 'Mikael Lustig', 'VER', 'SWE', 'wk'),
(gen_random_uuid(), 'Marcus Danielson', 'VER', 'SWE', 'wk'),
(gen_random_uuid(), 'Emil Krafth', 'VER', 'SWE', 'wk'),
(gen_random_uuid(), 'Albin Ekdal', 'MID', 'SWE', 'wk'),
(gen_random_uuid(), 'Viktor Claesson', 'MID', 'SWE', 'wk'),
(gen_random_uuid(), 'Sebastian Larsson', 'MID', 'SWE', 'wk'),
(gen_random_uuid(), 'Dejan Kulusevski', 'MID', 'SWE', 'wk'),
(gen_random_uuid(), 'Jens-Lys Cajuste', 'MID', 'SWE', 'wk'),
(gen_random_uuid(), 'Zlatan Ibrahimović', 'AAN', 'SWE', 'wk'),
(gen_random_uuid(), 'Alexander Isak', 'AAN', 'SWE', 'wk'),
(gen_random_uuid(), 'Marcus Berg', 'AAN', 'SWE', 'wk'),
(gen_random_uuid(), 'Jordan Larsson', 'AAN', 'SWE', 'wk'),
(gen_random_uuid(), 'Robin Quaison', 'AAN', 'SWE', 'wk'),

-- Norway
(gen_random_uuid(), 'Rune Jarstein', 'DOE', 'NOR', 'wk'),
(gen_random_uuid(), 'Ørjan Nyland', 'DOE', 'NOR', 'wk'),
(gen_random_uuid(), 'Jørgen Strand Larsen', 'DOE', 'NOR', 'wk'),
(gen_random_uuid(), 'Kristoffer Ajer', 'VER', 'NOR', 'wk'),
(gen_random_uuid(), 'Birger Meling', 'VER', 'NOR', 'wk'),
(gen_random_uuid(), 'Andreas Hanche-Olsen', 'VER', 'NOR', 'wk'),
(gen_random_uuid(), 'Leo Skiri Østigård', 'VER', 'NOR', 'wk'),
(gen_random_uuid(), 'Fredrik Aursnes', 'VER', 'NOR', 'wk'),
(gen_random_uuid(), 'Julian Ryerson', 'VER', 'NOR', 'wk'),
(gen_random_uuid(), 'Sander Berge', 'MID', 'NOR', 'wk'),
(gen_random_uuid(), 'Martin Ødegaard', 'MID', 'NOR', 'wk'),
(gen_random_uuid(), 'Stefan Johansen', 'MID', 'NOR', 'wk'),
(gen_random_uuid(), 'Morten Thorsby', 'MID', 'NOR', 'wk'),
(gen_random_uuid(), 'Patrick Berg', 'MID', 'NOR', 'wk'),
(gen_random_uuid(), 'Erling Haaland', 'AAN', 'NOR', 'wk'),
(gen_random_uuid(), 'Joshua King', 'AAN', 'NOR', 'wk'),
(gen_random_uuid(), 'Mohamed Elyounoussi', 'AAN', 'NOR', 'wk'),
(gen_random_uuid(), 'Alexander Sørloth', 'AAN', 'NOR', 'wk'),
(gen_random_uuid(), 'Ola Solbakken', 'AAN', 'NOR', 'wk'),

-- Finland
(gen_random_uuid(), 'Lukáš Hrádecký', 'DOE', 'FIN', 'wk'),
(gen_random_uuid(), 'Jesse Joronen', 'DOE', 'FIN', 'wk'),
(gen_random_uuid(), 'Anssi Jaakkola', 'DOE', 'FIN', 'wk'),
(gen_random_uuid(), 'Joona Toivio', 'VER', 'FIN', 'wk'),
(gen_random_uuid(), 'Paulus Arajuuri', 'VER', 'FIN', 'wk'),
(gen_random_uuid(), 'Jere Uronen', 'VER', 'FIN', 'wk'),
(gen_random_uuid(), 'Sauli Väisänen', 'VER', 'FIN', 'wk'),
(gen_random_uuid(), 'Leo Väisänen', 'VER', 'FIN', 'wk'),
(gen_random_uuid(), 'Nikolai Alho', 'VER', 'FIN', 'wk'),
(gen_random_uuid(), 'Glen Kamara', 'MID', 'FIN', 'wk'),
(gen_random_uuid(), 'Robin Lod', 'MID', 'FIN', 'wk'),
(gen_random_uuid(), 'Rasmus Schüller', 'MID', 'FIN', 'wk'),
(gen_random_uuid(), 'Jasse Tuominen', 'MID', 'FIN', 'wk'),
(gen_random_uuid(), 'Onni Valakari', 'MID', 'FIN', 'wk'),
(gen_random_uuid(), 'Teemu Pukki', 'AAN', 'FIN', 'wk'),
(gen_random_uuid(), 'Joel Pohjanpalo', 'AAN', 'FIN', 'wk'),
(gen_random_uuid(), 'Marcus Forss', 'AAN', 'FIN', 'wk'),
(gen_random_uuid(), 'Fredrik Jensen', 'AAN', 'FIN', 'wk'),
(gen_random_uuid(), 'Daniel O''Shaughnessy', 'AAN', 'FIN', 'wk'),

-- Slovakia
(gen_random_uuid(), 'Martin Dúbravka', 'DOE', 'SVK', 'wk'),
(gen_random_uuid(), 'Henrich Ravas', 'DOE', 'SVK', 'wk'),
(gen_random_uuid(), 'Adrián Chovan', 'DOE', 'SVK', 'wk'),
(gen_random_uuid(), 'Milan Škriniar', 'VER', 'SVK', 'wk'),
(gen_random_uuid(), 'Denis Vavro', 'VER', 'SVK', 'wk'),
(gen_random_uuid(), 'Peter Pekarík', 'VER', 'SVK', 'wk'),
(gen_random_uuid(), 'Tomáš Hubočan', 'VER', 'SVK', 'wk'),
(gen_random_uuid(), 'Norbert Gyömbér', 'VER', 'SVK', 'wk'),
(gen_random_uuid(), 'Lukáš Pauschek', 'VER', 'SVK', 'wk'),
(gen_random_uuid(), 'Marek Hamšík', 'MID', 'SVK', 'wk'),
(gen_random_uuid(), 'Juraj Kucka', 'MID', 'SVK', 'wk'),
(gen_random_uuid(), 'Stanislav Lobotka', 'MID', 'SVK', 'wk'),
(gen_random_uuid(), 'László Bénes', 'MID', 'SVK', 'wk'),
(gen_random_uuid(), 'Ondrej Duda', 'MID', 'SVK', 'wk'),
(gen_random_uuid(), 'Róbert Mak', 'AAN', 'SVK', 'wk'),
(gen_random_uuid(), 'Dávid Hancko', 'AAN', 'SVK', 'wk'),
(gen_random_uuid(), 'Dušan Švento', 'AAN', 'SVK', 'wk'),
(gen_random_uuid(), 'Adam Zreľák', 'AAN', 'SVK', 'wk'),
(gen_random_uuid(), 'Ivan Schranz', 'AAN', 'SVK', 'wk'),

-- Group J: Austria, Bosnia & Herzegovina, Cape Verde, Algeria
-- Austria
(gen_random_uuid(), 'Patrick Pentz', 'DOE', 'AUT', 'wk'),
(gen_random_uuid(), 'Daniel Bachmann', 'DOE', 'AUT', 'wk'),
(gen_random_uuid(), 'Alexander Schlager', 'DOE', 'AUT', 'wk'),
(gen_random_uuid(), 'David Alaba', 'VER', 'AUT', 'wk'),
(gen_random_uuid(), 'Philipp Lienhart', 'VER', 'AUT', 'wk'),
(gen_random_uuid(), 'Stefan Posch', 'VER', 'AUT', 'wk'),
(gen_random_uuid(), 'Maximilian Wöber', 'VER', 'AUT', 'wk'),
(gen_random_uuid(), 'Phillipp Mwene', 'VER', 'AUT', 'wk'),
(gen_random_uuid(), 'Aleksandar Dragović', 'VER', 'AUT', 'wk'),
(gen_random_uuid(), 'Florian Grillitsch', 'MID', 'AUT', 'wk'),
(gen_random_uuid(), 'Julian Baumgartlinger', 'MID', 'AUT', 'wk'),
(gen_random_uuid(), 'Konrad Laimer', 'MID', 'AUT', 'wk'),
(gen_random_uuid(), 'Marcel Sabitzer', 'MID', 'AUT', 'wk'),
(gen_random_uuid(), 'Xaver Schlager', 'MID', 'AUT', 'wk'),
(gen_random_uuid(), 'Marko Arnautović', 'AAN', 'AUT', 'wk'),
(gen_random_uuid(), 'Michael Gregoritsch', 'AAN', 'AUT', 'wk'),
(gen_random_uuid(), 'Christoph Baumgartner', 'AAN', 'AUT', 'wk'),
(gen_random_uuid(), 'Patrick Wimmer', 'AAN', 'AUT', 'wk'),
(gen_random_uuid(), 'Louis Schaub', 'AAN', 'AUT', 'wk'),

-- Bosnia & Herzegovina
(gen_random_uuid(), 'Kenan Pirić', 'DOE', 'BIH', 'wk'),
(gen_random_uuid(), 'Vedran Kjosevski', 'DOE', 'BIH', 'wk'),
(gen_random_uuid(), 'Ibrahim Šehić', 'DOE', 'BIH', 'wk'),
(gen_random_uuid(), 'Ermin Bičakčić', 'VER', 'BIH', 'wk'),
(gen_random_uuid(), 'Sead Kolašinac', 'VER', 'BIH', 'wk'),
(gen_random_uuid(), 'Ognjen Vranješ', 'VER', 'BIH', 'wk'),
(gen_random_uuid(), 'Amar Dedić', 'VER', 'BIH', 'wk'),
(gen_random_uuid(), 'Dario Šimić', 'VER', 'BIH', 'wk'),
(gen_random_uuid(), 'Nermin Zolotić', 'VER', 'BIH', 'wk'),
(gen_random_uuid(), 'Miralem Pjanić', 'MID', 'BIH', 'wk'),
(gen_random_uuid(), 'Gojko Cimirot', 'MID', 'BIH', 'wk'),
(gen_random_uuid(), 'Amer Gojak', 'MID', 'BIH', 'wk'),
(gen_random_uuid(), 'Haris Duljevic', 'MID', 'BIH', 'wk'),
(gen_random_uuid(), 'Ermedin Demirović', 'MID', 'BIH', 'wk'),
(gen_random_uuid(), 'Edin Džeko', 'AAN', 'BIH', 'wk'),
(gen_random_uuid(), 'Armin Hodžić', 'AAN', 'BIH', 'wk'),
(gen_random_uuid(), 'Anel Ahmedhodžić', 'AAN', 'BIH', 'wk'),
(gen_random_uuid(), 'Smail Prevljak', 'AAN', 'BIH', 'wk'),
(gen_random_uuid(), 'Dženan Radončić', 'AAN', 'BIH', 'wk'),

-- Cape Verde
(gen_random_uuid(), 'Vozinha', 'DOE', 'CPV', 'wk'),
(gen_random_uuid(), 'Marcelo Boia', 'DOE', 'CPV', 'wk'),
(gen_random_uuid(), 'Stefan Pires', 'DOE', 'CPV', 'wk'),
(gen_random_uuid(), 'Roberto Lopes', 'VER', 'CPV', 'wk'),
(gen_random_uuid(), 'Dylan Tavares', 'VER', 'CPV', 'wk'),
(gen_random_uuid(), 'Diney', 'VER', 'CPV', 'wk'),
(gen_random_uuid(), 'Stopira', 'VER', 'CPV', 'wk'),
(gen_random_uuid(), 'Weldon', 'VER', 'CPV', 'wk'),
(gen_random_uuid(), 'Logan Costa', 'VER', 'CPV', 'wk'),
(gen_random_uuid(), 'Kenny Rocha Santos', 'MID', 'CPV', 'wk'),
(gen_random_uuid(), 'Jamiro Monteiro', 'MID', 'CPV', 'wk'),
(gen_random_uuid(), 'Ryan Mendes', 'MID', 'CPV', 'wk'),
(gen_random_uuid(), 'Lisandro Semedo', 'MID', 'CPV', 'wk'),
(gen_random_uuid(), 'Gabão', 'MID', 'CPV', 'wk'),
(gen_random_uuid(), 'Garry Rodrigues', 'AAN', 'CPV', 'wk'),
(gen_random_uuid(), 'Hélder Rodrigues', 'AAN', 'CPV', 'wk'),
(gen_random_uuid(), 'Djaniny', 'AAN', 'CPV', 'wk'),
(gen_random_uuid(), 'Ze Lp', 'AAN', 'CPV', 'wk'),
(gen_random_uuid(), 'Fernando Varela', 'AAN', 'CPV', 'wk'),

-- Algeria
(gen_random_uuid(), 'Rais M''Bolhi', 'DOE', 'ALG', 'wk'),
(gen_random_uuid(), 'Alexandre Oukidja', 'DOE', 'ALG', 'wk'),
(gen_random_uuid(), 'Sofiane Benguit', 'DOE', 'ALG', 'wk'),
(gen_random_uuid(), 'Djamel Benlamri', 'VER', 'ALG', 'wk'),
(gen_random_uuid(), 'Aïssa Mandi', 'VER', 'ALG', 'wk'),
(gen_random_uuid(), 'Mehdi Zeffane', 'VER', 'ALG', 'wk'),
(gen_random_uuid(), 'Youcef Atal', 'VER', 'ALG', 'wk'),
(gen_random_uuid(), 'Ramy Bensebaini', 'VER', 'ALG', 'wk'),
(gen_random_uuid(), 'Hicham Boudaoui', 'VER', 'ALG', 'wk'),
(gen_random_uuid(), 'Ismaël Bennacer', 'MID', 'ALG', 'wk'),
(gen_random_uuid(), 'Nabil Bentaleb', 'MID', 'ALG', 'wk'),
(gen_random_uuid(), 'Adlène Guedioura', 'MID', 'ALG', 'wk'),
(gen_random_uuid(), 'Sofiane Feghouli', 'MID', 'ALG', 'wk'),
(gen_random_uuid(), 'Ramiz Zerrouki', 'MID', 'ALG', 'wk'),
(gen_random_uuid(), 'Riyad Mahrez', 'AAN', 'ALG', 'wk'),
(gen_random_uuid(), 'Islam Slimani', 'AAN', 'ALG', 'wk'),
(gen_random_uuid(), 'Yacine Brahimi', 'AAN', 'ALG', 'wk'),
(gen_random_uuid(), 'Baghdad Bounedjah', 'AAN', 'ALG', 'wk'),
(gen_random_uuid(), 'Andy Delort', 'AAN', 'ALG', 'wk'),

-- Group K: Jordan, Iraq, Ivory Coast, DR Congo
-- Jordan
(gen_random_uuid(), 'Yazeed Abulaila', 'DOE', 'JOR', 'wk'),
(gen_random_uuid(), 'Mohammad Abu Hashhash', 'DOE', 'JOR', 'wk'),
(gen_random_uuid(), 'Awni Hijazi', 'DOE', 'JOR', 'wk'),
(gen_random_uuid(), 'Yazan Al-Naimat', 'VER', 'JOR', 'wk'),
(gen_random_uuid(), 'Hassan Abdel-Fattah', 'VER', 'JOR', 'wk'),
(gen_random_uuid(), 'Baha Faisal', 'VER', 'JOR', 'wk'),
(gen_random_uuid(), 'Zaid Tahseen', 'VER', 'JOR', 'wk'),
(gen_random_uuid(), 'Samer Ighbarieh', 'VER', 'JOR', 'wk'),
(gen_random_uuid(), 'Musa Al-Taamari', 'MID', 'JOR', 'wk'),
(gen_random_uuid(), 'Nour Mansour', 'MID', 'JOR', 'wk'),
(gen_random_uuid(), 'Ahmad Sarour', 'MID', 'JOR', 'wk'),
(gen_random_uuid(), 'Ehsan Haddad', 'MID', 'JOR', 'wk'),
(gen_random_uuid(), 'Majed Al-Rashid', 'MID', 'JOR', 'wk'),
(gen_random_uuid(), 'Ahmad Hayel', 'AAN', 'JOR', 'wk'),
(gen_random_uuid(), 'Hamza Al-Dardour', 'AAN', 'JOR', 'wk'),
(gen_random_uuid(), 'Yazan Al-Arab', 'AAN', 'JOR', 'wk'),
(gen_random_uuid(), 'Ahmad Al-Sarour', 'AAN', 'JOR', 'wk'),

-- Iraq
(gen_random_uuid(), 'Jalal Hassan', 'DOE', 'IRQ', 'wk'),
(gen_random_uuid(), 'Mohammed Hamid', 'DOE', 'IRQ', 'wk'),
(gen_random_uuid(), 'Ali Bassem', 'DOE', 'IRQ', 'wk'),
(gen_random_uuid(), 'Ali Adnan', 'VER', 'IRQ', 'wk'),
(gen_random_uuid(), 'Saad Abdul-Amir', 'VER', 'IRQ', 'wk'),
(gen_random_uuid(), 'Rebin Sulaka', 'VER', 'IRQ', 'wk'),
(gen_random_uuid(), 'Mustafa Mohammed', 'VER', 'IRQ', 'wk'),
(gen_random_uuid(), 'Ali Hassan', 'VER', 'IRQ', 'wk'),
(gen_random_uuid(), 'Ahmed Ibrahim', 'VER', 'IRQ', 'wk'),
(gen_random_uuid(), 'Amjed Attwan', 'MID', 'IRQ', 'wk'),
(gen_random_uuid(), 'Aymen Hussein', 'MID', 'IRQ', 'wk'),
(gen_random_uuid(), 'Humam Tariq', 'MID', 'IRQ', 'wk'),
(gen_random_uuid(), 'Ahmed Yasin', 'MID', 'IRQ', 'wk'),
(gen_random_uuid(), 'Alaa Abbas', 'MID', 'IRQ', 'wk'),
(gen_random_uuid(), 'Mohanad Ali', 'AAN', 'IRQ', 'wk'),
(gen_random_uuid(), 'Ayman Hussein', 'AAN', 'IRQ', 'wk'),
(gen_random_uuid(), 'Hassan Al-Haydos', 'AAN', 'IRQ', 'wk'),
(gen_random_uuid(), 'Safaa Hadi', 'AAN', 'IRQ', 'wk'),
(gen_random_uuid(), 'Ahmed Razzaq', 'AAN', 'IRQ', 'wk'),

-- Ivory Coast
(gen_random_uuid(), 'Badra Ali Sangaré', 'DOE', 'CIV', 'wk'),
(gen_random_uuid(), 'Yahia Fofana', 'DOE', 'CIV', 'wk'),
(gen_random_uuid(), 'Sylvain Gbohouo', 'DOE', 'CIV', 'wk'),
(gen_random_uuid(), 'Serge Aurier', 'VER', 'CIV', 'wk'),
(gen_random_uuid(), 'Simon Deli', 'VER', 'CIV', 'wk'),
(gen_random_uuid(), 'Wilfried Singo', 'VER', 'CIV', 'wk'),
(gen_random_uuid(), 'Ousmane Diomandé', 'VER', 'CIV', 'wk'),
(gen_random_uuid(), 'Ghislain Konan', 'VER', 'CIV', 'wk'),
(gen_random_uuid(), 'Willy Boly', 'VER', 'CIV', 'wk'),
(gen_random_uuid(), 'Franck Kessie', 'MID', 'CIV', 'wk'),
(gen_random_uuid(), 'Jean Michaël Seri', 'MID', 'CIV', 'wk'),
(gen_random_uuid(), 'Ibrahima Sangaré', 'MID', 'CIV', 'wk'),
(gen_random_uuid(), 'Serey Dié', 'MID', 'CIV', 'wk'),
(gen_random_uuid(), 'Seko Fofana', 'MID', 'CIV', 'wk'),
(gen_random_uuid(), 'Sébastien Haller', 'AAN', 'CIV', 'wk'),
(gen_random_uuid(), 'Nicolas Pépé', 'AAN', 'CIV', 'wk'),
(gen_random_uuid(), 'Wilfried Zaha', 'AAN', 'CIV', 'wk'),
(gen_random_uuid(), 'Max-Alain Gradel', 'AAN', 'CIV', 'wk'),
(gen_random_uuid(), 'Jonathan Kodjia', 'AAN', 'CIV', 'wk'),

-- DR Congo
(gen_random_uuid(), 'Joël Kiassumbua', 'DOE', 'COD', 'wk'),
(gen_random_uuid(), 'Ley Matampi', 'DOE', 'COD', 'wk'),
(gen_random_uuid(), 'Dimitri Bertaud', 'DOE', 'COD', 'wk'),
(gen_random_uuid(), 'Chancel Mbemba', 'VER', 'COD', 'wk'),
(gen_random_uuid(), 'Merveille Bope Bokadi', 'VER', 'COD', 'wk'),
(gen_random_uuid(), 'Marcel Tisserand', 'VER', 'COD', 'wk'),
(gen_random_uuid(), 'Yannick Bolasie', 'VER', 'COD', 'wk'),
(gen_random_uuid(), 'Florent Ibenge', 'VER', 'COD', 'wk'),
(gen_random_uuid(), 'Britt Assombalonga', 'VER', 'COD', 'wk'),
(gen_random_uuid(), 'Youri Tielemans', 'MID', 'COD', 'wk'),
(gen_random_uuid(), 'Ngonda Muzinga', 'MID', 'COD', 'wk'),
(gen_random_uuid(), 'Paul-José Mpoku', 'MID', 'COD', 'wk'),
(gen_random_uuid(), 'Cédric Bakambu', 'MID', 'COD', 'wk'),
(gen_random_uuid(), 'Neeskens Kebano', 'MID', 'COD', 'wk'),
(gen_random_uuid(), 'Dieumerci Mbokani', 'AAN', 'COD', 'wk'),
(gen_random_uuid(), 'Michy Batshuayi', 'AAN', 'COD', 'wk'),
(gen_random_uuid(), 'Lassana Faye', 'AAN', 'COD', 'wk'),
(gen_random_uuid(), 'Théo Bongonda', 'AAN', 'COD', 'wk'),
(gen_random_uuid(), 'Emilio Nsimba', 'AAN', 'COD', 'wk'),

-- Group L: Panama, Uzbekistan, Egypt, New Zealand
-- Panama
(gen_random_uuid(), 'Luis Mejía', 'DOE', 'PAN', 'wk'),
(gen_random_uuid(), 'Gianluca Cariolato', 'DOE', 'PAN', 'wk'),
(gen_random_uuid(), 'José Guerra', 'DOE', 'PAN', 'wk'),
(gen_random_uuid(), 'Fidel Escobar', 'VER', 'PAN', 'wk'),
(gen_random_uuid(), 'Andrés Andrade', 'VER', 'PAN', 'wk'),
(gen_random_uuid(), 'Eric Davis', 'VER', 'PAN', 'wk'),
(gen_random_uuid(), 'Michael Murillo', 'VER', 'PAN', 'wk'),
(gen_random_uuid(), 'Roderick Miller', 'VER', 'PAN', 'wk'),
(gen_random_uuid(), 'Harold Cummings', 'VER', 'PAN', 'wk'),
(gen_random_uuid(), 'Adalberto Carrasquilla', 'MID', 'PAN', 'wk'),
(gen_random_uuid(), 'Anibal Godoy', 'MID', 'PAN', 'wk'),
(gen_random_uuid(), 'Édgar Bárcenas', 'MID', 'PAN', 'wk'),
(gen_random_uuid(), 'Alberto Quintero', 'MID', 'PAN', 'wk'),
(gen_random_uuid(), 'Armando Cooper', 'MID', 'PAN', 'wk'),
(gen_random_uuid(), 'Ismael Díaz', 'AAN', 'PAN', 'wk'),
(gen_random_uuid(), 'Rolando Blackburn', 'AAN', 'PAN', 'wk'),
(gen_random_uuid(), 'Gabriel Torres', 'AAN', 'PAN', 'wk'),
(gen_random_uuid(), 'Cesar Yanis', 'AAN', 'PAN', 'wk'),
(gen_random_uuid(), 'Freddy Gondola', 'AAN', 'PAN', 'wk'),

-- Uzbekistan
(gen_random_uuid(), 'Eldorbek Sobirov', 'DOE', 'UZB', 'wk'),
(gen_random_uuid(), 'Oybek Dzhaksybekov', 'DOE', 'UZB', 'wk'),
(gen_random_uuid(), 'Otabek Shukurov', 'DOE', 'UZB', 'wk'),
(gen_random_uuid(), 'Sanjar Tursunov', 'VER', 'UZB', 'wk'),
(gen_random_uuid(), 'Islombek Kobilov', 'VER', 'UZB', 'wk'),
(gen_random_uuid(), 'Dostonbek Khamdamov', 'VER', 'UZB', 'wk'),
(gen_random_uuid(), 'Khusan Toshmatov', 'VER', 'UZB', 'wk'),
(gen_random_uuid(), 'Ulugbek Rashidov', 'VER', 'UZB', 'wk'),
(gen_random_uuid(), 'Botirali Ergashev', 'VER', 'UZB', 'wk'),
(gen_random_uuid(), 'Odil Ahmedov', 'MID', 'UZB', 'wk'),
(gen_random_uuid(), 'Donis Abdurakhimov', 'MID', 'UZB', 'wk'),
(gen_random_uuid(), 'Jasur Yaxshiboyev', 'MID', 'UZB', 'wk'),
(gen_random_uuid(), 'Jaloliddin Masharipov', 'MID', 'UZB', 'wk'),
(gen_random_uuid(), 'Otabek Fayzullayev', 'MID', 'UZB', 'wk'),
(gen_random_uuid(), 'Eldor Shomurodov', 'AAN', 'UZB', 'wk'),
(gen_random_uuid(), 'Akbar Tursunov', 'AAN', 'UZB', 'wk'),
(gen_random_uuid(), 'Doniyor Nosirov', 'AAN', 'UZB', 'wk'),
(gen_random_uuid(), 'Sherzod Nasrullayev', 'AAN', 'UZB', 'wk'),
(gen_random_uuid(), 'Bobir Abdixoliqov', 'AAN', 'UZB', 'wk'),

-- Egypt
(gen_random_uuid(), 'Mohamed El-Shenawy', 'DOE', 'EGY', 'wk'),
(gen_random_uuid(), 'Mohamed Abou Gabal', 'DOE', 'EGY', 'wk'),
(gen_random_uuid(), 'Ahmed El-Shenawy', 'DOE', 'EGY', 'wk'),
(gen_random_uuid(), 'Ahmed Hegazi', 'VER', 'EGY', 'wk'),
(gen_random_uuid(), 'Omar Gaber', 'VER', 'EGY', 'wk'),
(gen_random_uuid(), 'Ahmed Hegazi', 'VER', 'EGY', 'wk'),
(gen_random_uuid(), 'Ayman Ashraf', 'VER', 'EGY', 'wk'),
(gen_random_uuid(), 'Ahmed Fatouh', 'VER', 'EGY', 'wk'),
(gen_random_uuid(), 'Mohamed Abdel-Shafy', 'VER', 'EGY', 'wk'),
(gen_random_uuid(), 'Tarek Hamed', 'MID', 'EGY', 'wk'),
(gen_random_uuid(), 'Amr El-Soulia', 'MID', 'EGY', 'wk'),
(gen_random_uuid(), 'Emam Ashour', 'MID', 'EGY', 'wk'),
(gen_random_uuid(), 'Mahmoud Trezeguet', 'MID', 'EGY', 'wk'),
(gen_random_uuid(), 'Omar Marmoush', 'MID', 'EGY', 'wk'),
(gen_random_uuid(), 'Mohamed Salah', 'AAN', 'EGY', 'wk'),
(gen_random_uuid(), 'Mostafa Mohamed', 'AAN', 'EGY', 'wk'),
(gen_random_uuid(), 'Ahmed Sayed Zizou', 'AAN', 'EGY', 'wk'),
(gen_random_uuid(), 'Ramadan Sobhi', 'AAN', 'EGY', 'wk'),
(gen_random_uuid(), 'Amr Warda', 'AAN', 'EGY', 'wk'),

-- New Zealand
(gen_random_uuid(), 'Joe Leckie', 'DOE', 'NZL', 'wk'),
(gen_random_uuid(), 'Stefan Marinovic', 'DOE', 'NZL', 'wk'),
(gen_random_uuid(), 'Jak Amos', 'DOE', 'NZL', 'wk'),
(gen_random_uuid(), 'Tommy Smith', 'VER', 'NZL', 'wk'),
(gen_random_uuid(), 'Bill Tuiloma', 'VER', 'NZL', 'wk'),
(gen_random_uuid(), 'Nando Pijnaker', 'VER', 'NZL', 'wk'),
(gen_random_uuid(), 'Michael Boxall', 'VER', 'NZL', 'wk'),
(gen_random_uuid(), 'Liberato Cacace', 'VER', 'NZL', 'wk'),
(gen_random_uuid(), 'Winston Reid', 'VER', 'NZL', 'wk'),
(gen_random_uuid(), 'Declan Wynne', 'MID', 'NZL', 'wk'),
(gen_random_uuid(), 'Clayton Lewis', 'MID', 'NZL', 'wk'),
(gen_random_uuid(), 'Joe Bell', 'MID', 'NZL', 'wk'),
(gen_random_uuid(), 'Elijah Just', 'MID', 'NZL', 'wk'),
(gen_random_uuid(), 'Cameron Howieson', 'MID', 'NZL', 'wk'),
(gen_random_uuid(), 'Chris Wood', 'AAN', 'NZL', 'wk'),
(gen_random_uuid(), 'Kosta Barbarouses', 'AAN', 'NZL', 'wk'),
(gen_random_uuid(), 'Callan Elliot', 'AAN', 'NZL', 'wk'),
(gen_random_uuid(), 'Matthew Ridenton', 'AAN', 'NZL', 'wk'),
(gen_random_uuid(), 'Hamish Watson', 'AAN', 'NZL', 'wk'),

-- South Africa (ZAF)
(gen_random_uuid(), 'Ronwen Williams', 'DOE', 'ZAF', 'wk'),
(gen_random_uuid(), 'Veli Mothwa', 'DOE', 'ZAF', 'wk'),
(gen_random_uuid(), 'Bruce Bvuma', 'DOE', 'ZAF', 'wk'),
(gen_random_uuid(), 'Siyanda Xulu', 'VER', 'ZAF', 'wk'),
(gen_random_uuid(), 'Rushine De Reuck', 'VER', 'ZAF', 'wk'),
(gen_random_uuid(), 'Grant Kekana', 'VER', 'ZAF', 'wk'),
(gen_random_uuid(), 'Teboho Mokoena', 'VER', 'ZAF', 'wk'),
(gen_random_uuid(), 'Reeve Frosler', 'VER', 'ZAF', 'wk'),
(gen_random_uuid(), 'Nyiko Mobbie', 'VER', 'ZAF', 'wk'),
(gen_random_uuid(), 'Bongani Zungu', 'MID', 'ZAF', 'wk'),
(gen_random_uuid(), 'Themba Zwane', 'MID', 'ZAF', 'wk'),
(gen_random_uuid(), 'Mothobi Mvala', 'MID', 'ZAF', 'wk'),
(gen_random_uuid(), 'Ethan Ngobo', 'MID', 'ZAF', 'wk'),
(gen_random_uuid(), 'Percy Tau', 'AAN', 'ZAF', 'wk'),
(gen_random_uuid(), 'Lyle Foster', 'AAN', 'ZAF', 'wk'),
(gen_random_uuid(), 'Evidence Makgopa', 'AAN', 'ZAF', 'wk'),
(gen_random_uuid(), 'Bradley Grobler', 'AAN', 'ZAF', 'wk'),
(gen_random_uuid(), 'Ngcosana Mhango', 'AAN', 'ZAF', 'wk'),

-- Haiti
(gen_random_uuid(), 'Josué Duverger', 'DOE', 'HAI', 'wk'),
(gen_random_uuid(), 'Yanick Mésidor', 'DOE', 'HAI', 'wk'),
(gen_random_uuid(), 'Nicolas Moreira', 'DOE', 'HAI', 'wk'),
(gen_random_uuid(), 'Mechack Jérôme', 'VER', 'HAI', 'wk'),
(gen_random_uuid(), 'Jems Geffrard', 'VER', 'HAI', 'wk'),
(gen_random_uuid(), 'Kevin Lafrance', 'VER', 'HAI', 'wk'),
(gen_random_uuid(), 'Reginal Goreux', 'VER', 'HAI', 'wk'),
(gen_random_uuid(), 'Carlens Arcus', 'VER', 'HAI', 'wk'),
(gen_random_uuid(), 'Frémy Bonhomme', 'VER', 'HAI', 'wk'),
(gen_random_uuid(), 'Wilde-Donald Guerrier', 'MID', 'HAI', 'wk'),
(gen_random_uuid(), 'Duckens Nazon', 'MID', 'HAI', 'wk'),
(gen_random_uuid(), 'Jean-Robert Léandre', 'MID', 'HAI', 'wk'),
(gen_random_uuid(), 'Frantzdy Pierrot', 'MID', 'HAI', 'wk'),
(gen_random_uuid(), 'Derrick Étienne', 'MID', 'HAI', 'wk'),
(gen_random_uuid(), 'Djeiny Jeanbaptiste', 'AAN', 'HAI', 'wk'),
(gen_random_uuid(), 'Jeff Louis', 'AAN', 'HAI', 'wk'),
(gen_random_uuid(), 'Nicolas Motta', 'AAN', 'HAI', 'wk'),
(gen_random_uuid(), 'Steeven Saba', 'AAN', 'HAI', 'wk'),

-- Curaçao
(gen_random_uuid(), 'Eloy Room', 'DOE', 'CUR', 'wk'),
(gen_random_uuid(), 'Giliano Wijnaldum', 'DOE', 'CUR', 'wk'),
(gen_random_uuid(), 'Sven Smit', 'DOE', 'CUR', 'wk'),
(gen_random_uuid(), 'Cuco Martina', 'VER', 'CUR', 'wk'),
(gen_random_uuid(), 'Rangelo Janga', 'VER', 'CUR', 'wk'),
(gen_random_uuid(), 'Juriën Gaari', 'VER', 'CUR', 'wk'),
(gen_random_uuid(), 'Shaquill Sno', 'VER', 'CUR', 'wk'),
(gen_random_uuid(), 'Raily Ignacio', 'VER', 'CUR', 'wk'),
(gen_random_uuid(), 'Leandro Bacuna', 'MID', 'CUR', 'wk'),
(gen_random_uuid(), 'Gevaro Nepomuceno', 'MID', 'CUR', 'wk'),
(gen_random_uuid(), 'Jarchinio Antonia', 'MID', 'CUR', 'wk'),
(gen_random_uuid(), 'Charlton Vicento', 'MID', 'CUR', 'wk'),
(gen_random_uuid(), 'Warner Hahn', 'MID', 'CUR', 'wk'),
(gen_random_uuid(), 'Myenty Abena', 'AAN', 'CUR', 'wk'),
(gen_random_uuid(), 'Genero Snijders', 'AAN', 'CUR', 'wk'),
(gen_random_uuid(), 'Gino van Kessel', 'AAN', 'CUR', 'wk'),
(gen_random_uuid(), 'Elson Hooi', 'AAN', 'CUR', 'wk'),
(gen_random_uuid(), 'Quentin Braat', 'AAN', 'CUR', 'wk');
