-- ============================================================
-- GROEP E: GER, CUR, CIV, ECU
-- ============================================================

-- Duitsland (GER)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Oliver Baumann', 'GER', 'DOE', 'wk'),
(gen_random_uuid(), 'Manuel Neuer', 'GER', 'DOE', 'wk'),
(gen_random_uuid(), 'Alexander Nübel', 'GER', 'DOE', 'wk'),
(gen_random_uuid(), 'Joshua Kimmich', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Nico Schlotterbeck', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'David Raum', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Jonathan Tah', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Waldemar Anton', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Antonio Rüdiger', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Mats Hummels', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Maximilian Mittelstädt', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Jamal Musiala', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Florian Wirtz', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Pascal Groß', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Aleksandar Pavlović', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Robert Andrich', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Leroy Sané', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Toni Kroos', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Chris Führich', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Granit Xhaka', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Kai Havertz', 'GER', 'AAN', 'wk'),
(gen_random_uuid(), 'Deniz Undav', 'GER', 'AAN', 'wk'),
(gen_random_uuid(), 'Tim Kleindienst', 'GER', 'AAN', 'wk'),
(gen_random_uuid(), 'Niclas Füllkrug', 'GER', 'AAN', 'wk'),
(gen_random_uuid(), 'Maximilian Beier', 'GER', 'AAN', 'wk'),
(gen_random_uuid(), 'Kevin Schade', 'GER', 'AAN', 'wk');

-- Curaçao (CUR)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Eloy Room', 'CUR', 'DOE', 'wk'),
(gen_random_uuid(), 'Tyrick Bodak', 'CUR', 'DOE', 'wk'),
(gen_random_uuid(), 'Trevor Doornbusch', 'CUR', 'DOE', 'wk'),
(gen_random_uuid(), 'Riechedly Bazoer', 'CUR', 'VER', 'wk'),
(gen_random_uuid(), 'Joshua Brenet', 'CUR', 'VER', 'wk'),
(gen_random_uuid(), 'Roshon van Eijma', 'CUR', 'VER', 'wk'),
(gen_random_uuid(), 'Sherel Floranus', 'CUR', 'VER', 'wk'),
(gen_random_uuid(), 'Deveron Fonville', 'CUR', 'VER', 'wk'),
(gen_random_uuid(), 'Jurien Gaari', 'CUR', 'VER', 'wk'),
(gen_random_uuid(), 'Armando Obispo', 'CUR', 'VER', 'wk'),
(gen_random_uuid(), 'Shurandy Sambo', 'CUR', 'VER', 'wk'),
(gen_random_uuid(), 'Juninho Bacuna', 'CUR', 'MID', 'wk'),
(gen_random_uuid(), 'Leandro Bacuna', 'CUR', 'MID', 'wk'),
(gen_random_uuid(), 'Livano Comenencia', 'CUR', 'MID', 'wk'),
(gen_random_uuid(), 'Kevin Felida', 'CUR', 'MID', 'wk'),
(gen_random_uuid(), 'Ar''Jany Martha', 'CUR', 'MID', 'wk'),
(gen_random_uuid(), 'Tyrese Noslin', 'CUR', 'MID', 'wk'),
(gen_random_uuid(), 'Godfried Roemeratoe', 'CUR', 'MID', 'wk'),
(gen_random_uuid(), 'Tahith Chong', 'CUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Sontje Hansen', 'CUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Kenji Gorré', 'CUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Jeremy Antonisse', 'CUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Gervane Kastaneer', 'CUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Brandley Kuwas', 'CUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Jurgen Locadia', 'CUR', 'AAN', 'wk'),
(gen_random_uuid(), 'Jearl Margaritha', 'CUR', 'AAN', 'wk');

-- Ivoorkust (CIV)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Yahia Fofana', 'CIV', 'DOE', 'wk'),
(gen_random_uuid(), 'Mohamed Koné', 'CIV', 'DOE', 'wk'),
(gen_random_uuid(), 'Alban Lafont', 'CIV', 'DOE', 'wk'),
(gen_random_uuid(), 'Emmanuel Agbadou', 'CIV', 'VER', 'wk'),
(gen_random_uuid(), 'Clément Akpa Akpro', 'CIV', 'VER', 'wk'),
(gen_random_uuid(), 'Ousmane Diomandé', 'CIV', 'VER', 'wk'),
(gen_random_uuid(), 'Guela Doué', 'CIV', 'VER', 'wk'),
(gen_random_uuid(), 'Ghislain Konan', 'CIV', 'VER', 'wk'),
(gen_random_uuid(), 'Odilon Kossounou', 'CIV', 'VER', 'wk'),
(gen_random_uuid(), 'Evan Ndicka', 'CIV', 'VER', 'wk'),
(gen_random_uuid(), 'Wilfried Singo', 'CIV', 'VER', 'wk'),
(gen_random_uuid(), 'Seko Fofana', 'CIV', 'MID', 'wk'),
(gen_random_uuid(), 'Franck Kessié', 'CIV', 'MID', 'wk'),
(gen_random_uuid(), 'Ibrahim Sangaré', 'CIV', 'MID', 'wk'),
(gen_random_uuid(), 'Jean-Mickaël Seri', 'CIV', 'MID', 'wk'),
(gen_random_uuid(), 'Parfait Guiagon', 'CIV', 'MID', 'wk'),
(gen_random_uuid(), 'Christ Oulaï', 'CIV', 'MID', 'wk'),
(gen_random_uuid(), 'Simon Adingra', 'CIV', 'AAN', 'wk'),
(gen_random_uuid(), 'Amad Diallo', 'CIV', 'AAN', 'wk'),
(gen_random_uuid(), 'Nicolas Pépé', 'CIV', 'AAN', 'wk'),
(gen_random_uuid(), 'Elye Wahi', 'CIV', 'AAN', 'wk'),
(gen_random_uuid(), 'Ange-Yoan Bonny', 'CIV', 'AAN', 'wk'),
(gen_random_uuid(), 'Evann Guessand', 'CIV', 'AAN', 'wk'),
(gen_random_uuid(), 'Oumar Diakité', 'CIV', 'AAN', 'wk'),
(gen_random_uuid(), 'Yan Diomandé', 'CIV', 'AAN', 'wk'),
(gen_random_uuid(), 'Bazoumana Touré', 'CIV', 'AAN', 'wk');

-- Ecuador (ECU)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Hernán Galíndez', 'ECU', 'DOE', 'wk'),
(gen_random_uuid(), 'Moisés Ramírez', 'ECU', 'DOE', 'wk'),
(gen_random_uuid(), 'Gonzalo Valle', 'ECU', 'DOE', 'wk'),
(gen_random_uuid(), 'Willian Pacho', 'ECU', 'VER', 'wk'),
(gen_random_uuid(), 'Piero Hincapié', 'ECU', 'VER', 'wk'),
(gen_random_uuid(), 'Joel Ordóñez', 'ECU', 'VER', 'wk'),
(gen_random_uuid(), 'Félix Torres', 'ECU', 'VER', 'wk'),
(gen_random_uuid(), 'Pervis Estupiñán', 'ECU', 'VER', 'wk'),
(gen_random_uuid(), 'Angelo Preciado', 'ECU', 'VER', 'wk'),
(gen_random_uuid(), 'Jackson Porozo', 'ECU', 'VER', 'wk'),
(gen_random_uuid(), 'Yaimar Medina', 'ECU', 'VER', 'wk'),
(gen_random_uuid(), 'Moisés Caicedo', 'ECU', 'MID', 'wk'),
(gen_random_uuid(), 'Alan Franco', 'ECU', 'MID', 'wk'),
(gen_random_uuid(), 'Kendry Páez', 'ECU', 'MID', 'wk'),
(gen_random_uuid(), 'Gonzalo Plata', 'ECU', 'MID', 'wk'),
(gen_random_uuid(), 'John Yeboah', 'ECU', 'MID', 'wk'),
(gen_random_uuid(), 'Alan Minda', 'ECU', 'MID', 'wk'),
(gen_random_uuid(), 'Pedro Vite', 'ECU', 'MID', 'wk'),
(gen_random_uuid(), 'Jordy Alcivar', 'ECU', 'MID', 'wk'),
(gen_random_uuid(), 'Denil Castillo', 'ECU', 'MID', 'wk'),
(gen_random_uuid(), 'Enner Valencia', 'ECU', 'AAN', 'wk'),
(gen_random_uuid(), 'Kevin Rodríguez', 'ECU', 'AAN', 'wk'),
(gen_random_uuid(), 'Anthony Valencia', 'ECU', 'AAN', 'wk'),
(gen_random_uuid(), 'Jordy Caicedo', 'ECU', 'AAN', 'wk'),
(gen_random_uuid(), 'Jeremy Arévalo', 'ECU', 'AAN', 'wk'),
(gen_random_uuid(), 'Willian Corozo', 'ECU', 'AAN', 'wk');

-- ============================================================
-- GROEP F: NED, JPN, SWE, TUN
-- ============================================================

-- Nederland (NED)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Bart Verbruggen', 'NED', 'DOE', 'wk'),
(gen_random_uuid(), 'Mark Flekken', 'NED', 'DOE', 'wk'),
(gen_random_uuid(), 'Kjell Scherpen', 'NED', 'DOE', 'wk'),
(gen_random_uuid(), 'Virgil van Dijk', 'NED', 'VER', 'wk'),
(gen_random_uuid(), 'Denzel Dumfries', 'NED', 'VER', 'wk'),
(gen_random_uuid(), 'Nathan Aké', 'NED', 'VER', 'wk'),
(gen_random_uuid(), 'Lutsharel Geertruida', 'NED', 'VER', 'wk'),
(gen_random_uuid(), 'Micky van de Ven', 'NED', 'VER', 'wk'),
(gen_random_uuid(), 'Jan Paul van Hecke', 'NED', 'VER', 'wk'),
(gen_random_uuid(), 'Jorrel Hato', 'NED', 'VER', 'wk'),
(gen_random_uuid(), 'Frenkie de Jong', 'NED', 'MID', 'wk'),
(gen_random_uuid(), 'Marten de Roon', 'NED', 'MID', 'wk'),
(gen_random_uuid(), 'Tijjani Reijnders', 'NED', 'MID', 'wk'),
(gen_random_uuid(), 'Teun Koopmeiners', 'NED', 'MID', 'wk'),
(gen_random_uuid(), 'Ryan Gravenberch', 'NED', 'MID', 'wk'),
(gen_random_uuid(), 'Quinten Timber', 'NED', 'MID', 'wk'),
(gen_random_uuid(), 'Guus Til', 'NED', 'MID', 'wk'),
(gen_random_uuid(), 'Jerdy Schouten', 'NED', 'MID', 'wk'),
(gen_random_uuid(), 'Brian Brobbey', 'NED', 'AAN', 'wk'),
(gen_random_uuid(), 'Memphis Depay', 'NED', 'AAN', 'wk'),
(gen_random_uuid(), 'Cody Gakpo', 'NED', 'AAN', 'wk'),
(gen_random_uuid(), 'Noa Lang', 'NED', 'AAN', 'wk'),
(gen_random_uuid(), 'Donyell Malen', 'NED', 'AAN', 'wk'),
(gen_random_uuid(), 'Myron Boadu', 'NED', 'AAN', 'wk'),
(gen_random_uuid(), 'Wout Weghorst', 'NED', 'AAN', 'wk'),
(gen_random_uuid(), 'Patrick Kluivert', 'NED', 'AAN', 'wk');

-- Japan (JPN)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Zion Suzuki', 'JPN', 'DOE', 'wk'),
(gen_random_uuid(), 'Tomoki Hayakawa', 'JPN', 'DOE', 'wk'),
(gen_random_uuid(), 'Keisuke Osako', 'JPN', 'DOE', 'wk'),
(gen_random_uuid(), 'Yuto Nagatomo', 'JPN', 'VER', 'wk'),
(gen_random_uuid(), 'Takehiro Tomiyasu', 'JPN', 'VER', 'wk'),
(gen_random_uuid(), 'Ko Itakura', 'JPN', 'VER', 'wk'),
(gen_random_uuid(), 'Shogo Taniguchi', 'JPN', 'VER', 'wk'),
(gen_random_uuid(), 'Hiroki Ito', 'JPN', 'VER', 'wk'),
(gen_random_uuid(), 'Yukinari Sugawara', 'JPN', 'VER', 'wk'),
(gen_random_uuid(), 'Ayumu Seko', 'JPN', 'VER', 'wk'),
(gen_random_uuid(), 'Tsuyoshi Watanabe', 'JPN', 'VER', 'wk'),
(gen_random_uuid(), 'Junnosuke Suzuki', 'JPN', 'VER', 'wk'),
(gen_random_uuid(), 'Wataru Endo', 'JPN', 'MID', 'wk'),
(gen_random_uuid(), 'Junya Ito', 'JPN', 'MID', 'wk'),
(gen_random_uuid(), 'Ritsu Doan', 'JPN', 'MID', 'wk'),
(gen_random_uuid(), 'Daichi Kamada', 'JPN', 'MID', 'wk'),
(gen_random_uuid(), 'Takefusa Kubo', 'JPN', 'MID', 'wk'),
(gen_random_uuid(), 'Ao Tanaka', 'JPN', 'MID', 'wk'),
(gen_random_uuid(), 'Keito Nakamura', 'JPN', 'MID', 'wk'),
(gen_random_uuid(), 'Kaishu Sano', 'JPN', 'MID', 'wk'),
(gen_random_uuid(), 'Ayase Ueda', 'JPN', 'AAN', 'wk'),
(gen_random_uuid(), 'Daizen Maeda', 'JPN', 'AAN', 'wk'),
(gen_random_uuid(), 'Koki Ogawa', 'JPN', 'AAN', 'wk'),
(gen_random_uuid(), 'Yuito Suzuki', 'JPN', 'AAN', 'wk'),
(gen_random_uuid(), 'Keisuke Goto', 'JPN', 'AAN', 'wk'),
(gen_random_uuid(), 'Kento Shiogai', 'JPN', 'AAN', 'wk');

-- Zweden (SWE)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Viktor Johansson', 'SWE', 'DOE', 'wk'),
(gen_random_uuid(), 'Kristoffer Nordfeldt', 'SWE', 'DOE', 'wk'),
(gen_random_uuid(), 'Jacob Widell Zetterström', 'SWE', 'DOE', 'wk'),
(gen_random_uuid(), 'Hjalmar Ekdal', 'SWE', 'VER', 'wk'),
(gen_random_uuid(), 'Gabriel Gudmundsson', 'SWE', 'VER', 'wk'),
(gen_random_uuid(), 'Isak Hien', 'SWE', 'VER', 'wk'),
(gen_random_uuid(), 'Gustaf Lagerbielke', 'SWE', 'VER', 'wk'),
(gen_random_uuid(), 'Victor Lindelöf', 'SWE', 'VER', 'wk'),
(gen_random_uuid(), 'Eric Smith', 'SWE', 'VER', 'wk'),
(gen_random_uuid(), 'Carl Starfelt', 'SWE', 'VER', 'wk'),
(gen_random_uuid(), 'Elliot Stroud', 'SWE', 'VER', 'wk'),
(gen_random_uuid(), 'Daniel Svensson', 'SWE', 'VER', 'wk'),
(gen_random_uuid(), 'Jesper Karlström', 'SWE', 'MID', 'wk'),
(gen_random_uuid(), 'Yasin Ayari', 'SWE', 'MID', 'wk'),
(gen_random_uuid(), 'Mattias Svanberg', 'SWE', 'MID', 'wk'),
(gen_random_uuid(), 'Lucas Bergvall', 'SWE', 'MID', 'wk'),
(gen_random_uuid(), 'Besfort Zeneli', 'SWE', 'MID', 'wk'),
(gen_random_uuid(), 'Herman Johansson', 'SWE', 'MID', 'wk'),
(gen_random_uuid(), 'Viktor Gyökeres', 'SWE', 'AAN', 'wk'),
(gen_random_uuid(), 'Alexander Isak', 'SWE', 'AAN', 'wk'),
(gen_random_uuid(), 'Anthony Elanga', 'SWE', 'AAN', 'wk'),
(gen_random_uuid(), 'Alexander Bernhardsson', 'SWE', 'AAN', 'wk'),
(gen_random_uuid(), 'Gustaf Nilsson', 'SWE', 'AAN', 'wk'),
(gen_random_uuid(), 'Benjamin Nygren', 'SWE', 'AAN', 'wk'),
(gen_random_uuid(), 'Ken Sema', 'SWE', 'AAN', 'wk'),
(gen_random_uuid(), 'Taha Ali', 'SWE', 'AAN', 'wk');

-- Tunesië (TUN)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Aymen Dahmen', 'TUN', 'DOE', 'wk'),
(gen_random_uuid(), 'Mouez Hassen', 'TUN', 'DOE', 'wk'),
(gen_random_uuid(), 'Bechir Ben Said', 'TUN', 'DOE', 'wk'),
(gen_random_uuid(), 'Montassar Talbi', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Dylan Bronn', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Yan Valery', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Ali Abdi', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Hamza Rekik', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Wajdi Kechrida', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Bilel Ifa', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Mohamed Ben Hamida', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Rami Bedoui', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Ellyes Skhiri', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Hannibal Mejbri', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Ismaël Gharbi', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Rani Khedira', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Anis Ben Slimane', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Aissa Laïdouni', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Saifeddine Khaoui', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Khalil Ayari', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Wahbi Khazri', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Naïm Sliti', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Youssef Msakni', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Seifeddine Jaziri', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Ghaylen Chaalali', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Elias Achouri', 'TUN', 'AAN', 'wk');

-- ============================================================
-- GROEP G: BEL, EGY, IRN, NZL
-- ============================================================

-- België (BEL)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Thibaut Courtois', 'BEL', 'DOE', 'wk'),
(gen_random_uuid(), 'Matz Sels', 'BEL', 'DOE', 'wk'),
(gen_random_uuid(), 'Thomas Kaminski', 'BEL', 'DOE', 'wk'),
(gen_random_uuid(), 'Timothy Castagne', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Zeno Debast', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Maxim De Cuyper', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Wout Faes', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Jan Vertonghen', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Thomas Meunier', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Arthur Theate', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Killian Sildillia', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Brandon Mechele', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Kevin De Bruyne', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Amadou Onana', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Orel Mangala', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Youri Tielemans', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Hans Vanaken', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Nicolas Raskin', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Charles De Ketelaere', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Dodi Lukebakio', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Romelu Lukaku', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Leandro Trossard', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Alexis Saelemaekers', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Jérémy Doku', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Lois Openda', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Johan Bakayoko', 'BEL', 'AAN', 'wk');

-- Egypte (EGY)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Mohamed El-Shenawy', 'EGY', 'DOE', 'wk'),
(gen_random_uuid(), 'Mostafa Shobeir', 'EGY', 'DOE', 'wk'),
(gen_random_uuid(), 'El-Mahdy Soliman', 'EGY', 'DOE', 'wk'),
(gen_random_uuid(), 'Mohamed Hani', 'EGY', 'VER', 'wk'),
(gen_random_uuid(), 'Tarek Alaa', 'EGY', 'VER', 'wk'),
(gen_random_uuid(), 'Hamdy Fathy', 'EGY', 'VER', 'wk'),
(gen_random_uuid(), 'Rami Rabia', 'EGY', 'VER', 'wk'),
(gen_random_uuid(), 'Yasser Ibrahim', 'EGY', 'VER', 'wk'),
(gen_random_uuid(), 'Hossam Abdelmaguid', 'EGY', 'VER', 'wk'),
(gen_random_uuid(), 'Mohamed Abdelmonem', 'EGY', 'VER', 'wk'),
(gen_random_uuid(), 'Ahmed Fotouh', 'EGY', 'VER', 'wk'),
(gen_random_uuid(), 'Marwan Attia', 'EGY', 'MID', 'wk'),
(gen_random_uuid(), 'Ahmed Zizo', 'EGY', 'MID', 'wk'),
(gen_random_uuid(), 'Emam Ashour', 'EGY', 'MID', 'wk'),
(gen_random_uuid(), 'Mahmoud Trezeguet', 'EGY', 'MID', 'wk'),
(gen_random_uuid(), 'Ibrahim Adel', 'EGY', 'MID', 'wk'),
(gen_random_uuid(), 'Nabil Emad', 'EGY', 'MID', 'wk'),
(gen_random_uuid(), 'Mostafa Ziko', 'EGY', 'MID', 'wk'),
(gen_random_uuid(), 'Mohanad Lasheen', 'EGY', 'MID', 'wk'),
(gen_random_uuid(), 'Haitham Hassan', 'EGY', 'MID', 'wk'),
(gen_random_uuid(), 'Mahmoud Saber', 'EGY', 'MID', 'wk'),
(gen_random_uuid(), 'Mohamed Salah', 'EGY', 'AAN', 'wk'),
(gen_random_uuid(), 'Omar Marmoush', 'EGY', 'AAN', 'wk'),
(gen_random_uuid(), 'Mostafa Mohamed', 'EGY', 'AAN', 'wk'),
(gen_random_uuid(), 'Aqtay Abdallah', 'EGY', 'AAN', 'wk'),
(gen_random_uuid(), 'Hussein El Shahat', 'EGY', 'AAN', 'wk');

-- Iran (IRN)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Alireza Beiranvand', 'IRN', 'DOE', 'wk'),
(gen_random_uuid(), 'Hossein Hosseini', 'IRN', 'DOE', 'wk'),
(gen_random_uuid(), 'Payam Niazmand', 'IRN', 'DOE', 'wk'),
(gen_random_uuid(), 'Shoja Khalilzadeh', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Ali Karimi', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Ehsan Hajsafi', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Majid Hosseini', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Milad Mohammadi', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Roozbeh Cheshmi', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Abolfazl Jalali', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Sadegh Moharrami', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Saeid Ezatolahi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Ahmad Nourollahi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Saman Ghoddos', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Ali Gholizadeh', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Vahid Amiri', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Alireza Jahanbakhsh', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Mohammad Mohebi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Omid Ebrahimi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Mehdi Torabi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Mehdi Taremi', 'IRN', 'AAN', 'wk'),
(gen_random_uuid(), 'Sardar Azmoun', 'IRN', 'AAN', 'wk'),
(gen_random_uuid(), 'Karim Ansarifard', 'IRN', 'AAN', 'wk'),
(gen_random_uuid(), 'Allahyar Sayyadmanesh', 'IRN', 'AAN', 'wk'),
(gen_random_uuid(), 'Shayan Mosleh', 'IRN', 'AAN', 'wk'),
(gen_random_uuid(), 'Aidin Zare', 'IRN', 'AAN', 'wk');

-- Nieuw-Zeeland (NZL)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Max Crocombe', 'NZL', 'DOE', 'wk'),
(gen_random_uuid(), 'Stefan Marinovic', 'NZL', 'DOE', 'wk'),
(gen_random_uuid(), 'Alex Paulsen', 'NZL', 'DOE', 'wk'),
(gen_random_uuid(), 'Tommy Smith', 'NZL', 'VER', 'wk'),
(gen_random_uuid(), 'Tyler Bindon', 'NZL', 'VER', 'wk'),
(gen_random_uuid(), 'Michael Boxall', 'NZL', 'VER', 'wk'),
(gen_random_uuid(), 'Liberato Cacace', 'NZL', 'VER', 'wk'),
(gen_random_uuid(), 'Francis de Vries', 'NZL', 'VER', 'wk'),
(gen_random_uuid(), 'Tim Payne', 'NZL', 'VER', 'wk'),
(gen_random_uuid(), 'Nando Pijnaker', 'NZL', 'VER', 'wk'),
(gen_random_uuid(), 'Finn Surman', 'NZL', 'VER', 'wk'),
(gen_random_uuid(), 'Callan Elliot', 'NZL', 'VER', 'wk'),
(gen_random_uuid(), 'Joe Bell', 'NZL', 'MID', 'wk'),
(gen_random_uuid(), 'Matt Garbett', 'NZL', 'MID', 'wk'),
(gen_random_uuid(), 'Alex Rufer', 'NZL', 'MID', 'wk'),
(gen_random_uuid(), 'Sarpreet Singh', 'NZL', 'MID', 'wk'),
(gen_random_uuid(), 'Marko Stamenić', 'NZL', 'MID', 'wk'),
(gen_random_uuid(), 'Ryan Thomas', 'NZL', 'MID', 'wk'),
(gen_random_uuid(), 'Chris Wood', 'NZL', 'AAN', 'wk'),
(gen_random_uuid(), 'Kosta Barbarouses', 'NZL', 'AAN', 'wk'),
(gen_random_uuid(), 'Ben Old', 'NZL', 'AAN', 'wk'),
(gen_random_uuid(), 'Jesse Randall', 'NZL', 'AAN', 'wk'),
(gen_random_uuid(), 'Ben Waine', 'NZL', 'AAN', 'wk'),
(gen_random_uuid(), 'Callum McCowatt', 'NZL', 'AAN', 'wk'),
(gen_random_uuid(), 'Lachlan Bayliss', 'NZL', 'AAN', 'wk'),
(gen_random_uuid(), 'Eli Just', 'NZL', 'AAN', 'wk');

-- ============================================================
-- GROEP H: ESP, CPV, KSA, URU
-- ============================================================

-- Spanje (ESP)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Unai Simón', 'ESP', 'DOE', 'wk'),
(gen_random_uuid(), 'David Raya', 'ESP', 'DOE', 'wk'),
(gen_random_uuid(), 'Alex Remiro', 'ESP', 'DOE', 'wk'),
(gen_random_uuid(), 'Marc Cucurella', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Alejandro Grimaldo', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Pau Cubarsí', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Aymeric Laporte', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Marc Pubill', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Éric García', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Diego Llorente', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Pedro Porro', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Pedri', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Fabián Ruiz', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Martín Zubimendi', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Gavi', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Rodri', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Alex Baena', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Mikel Merino', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Mikel Oyarzabal', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Dani Olmo', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Nico Williams', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Yeremy Pino', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Ferran Torres', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Borja Iglesias', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Lamine Yamal', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Bryan Zaragoza', 'ESP', 'AAN', 'wk');

-- Kaapverdië (CPV)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Vozinha', 'CPV', 'DOE', 'wk'),
(gen_random_uuid(), 'Márcio Rosa', 'CPV', 'DOE', 'wk'),
(gen_random_uuid(), 'CJ Dos Santos', 'CPV', 'DOE', 'wk'),
(gen_random_uuid(), 'Stopira', 'CPV', 'VER', 'wk'),
(gen_random_uuid(), 'Roberto Lopes', 'CPV', 'VER', 'wk'),
(gen_random_uuid(), 'João Paulo', 'CPV', 'VER', 'wk'),
(gen_random_uuid(), 'Sidny Lopes Cabral', 'CPV', 'VER', 'wk'),
(gen_random_uuid(), 'Logan Costa', 'CPV', 'VER', 'wk'),
(gen_random_uuid(), 'Steven Moreira', 'CPV', 'VER', 'wk'),
(gen_random_uuid(), 'Wagner Pina', 'CPV', 'VER', 'wk'),
(gen_random_uuid(), 'Kelvin Pires', 'CPV', 'VER', 'wk'),
(gen_random_uuid(), 'Diney', 'CPV', 'VER', 'wk'),
(gen_random_uuid(), 'Jamiro Monteiro', 'CPV', 'MID', 'wk'),
(gen_random_uuid(), 'Kevin Pina', 'CPV', 'MID', 'wk'),
(gen_random_uuid(), 'Deroy Duarte', 'CPV', 'MID', 'wk'),
(gen_random_uuid(), 'Telmo Arcanjo', 'CPV', 'MID', 'wk'),
(gen_random_uuid(), 'Laros Duarte', 'CPV', 'MID', 'wk'),
(gen_random_uuid(), 'Yannick Semedo', 'CPV', 'MID', 'wk'),
(gen_random_uuid(), 'Ryan Mendes', 'CPV', 'AAN', 'wk'),
(gen_random_uuid(), 'Garry Rodrigues', 'CPV', 'AAN', 'wk'),
(gen_random_uuid(), 'Willy Semedo', 'CPV', 'AAN', 'wk'),
(gen_random_uuid(), 'Jovane Cabral', 'CPV', 'AAN', 'wk'),
(gen_random_uuid(), 'Gilson Benchimol', 'CPV', 'AAN', 'wk'),
(gen_random_uuid(), 'Dailon Livramento', 'CPV', 'AAN', 'wk'),
(gen_random_uuid(), 'Hélio Varela', 'CPV', 'AAN', 'wk'),
(gen_random_uuid(), 'Nuno Da Costa', 'CPV', 'AAN', 'wk');

-- Saudi-Arabië (KSA)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Mohammed Al-Owais', 'KSA', 'DOE', 'wk'),
(gen_random_uuid(), 'Nawaf Al-Aqidi', 'KSA', 'DOE', 'wk'),
(gen_random_uuid(), 'Ahmed Al-Kassar', 'KSA', 'DOE', 'wk'),
(gen_random_uuid(), 'Saud Abdulhamid', 'KSA', 'VER', 'wk'),
(gen_random_uuid(), 'Jehad Thakri', 'KSA', 'VER', 'wk'),
(gen_random_uuid(), 'Abdulelah Al-Amri', 'KSA', 'VER', 'wk'),
(gen_random_uuid(), 'Hassan Tambakti', 'KSA', 'VER', 'wk'),
(gen_random_uuid(), 'Ali Lajami', 'KSA', 'VER', 'wk'),
(gen_random_uuid(), 'Hassan Kadesh', 'KSA', 'VER', 'wk'),
(gen_random_uuid(), 'Moteb Al-Harbi', 'KSA', 'VER', 'wk'),
(gen_random_uuid(), 'Nawaf Boushal', 'KSA', 'VER', 'wk'),
(gen_random_uuid(), 'Ali Majrashi', 'KSA', 'VER', 'wk'),
(gen_random_uuid(), 'Mohammed Abu Alshamat', 'KSA', 'VER', 'wk'),
(gen_random_uuid(), 'Ziyad Al-Johani', 'KSA', 'MID', 'wk'),
(gen_random_uuid(), 'Nasser Al-Dawsari', 'KSA', 'MID', 'wk'),
(gen_random_uuid(), 'Mohamed Kanno', 'KSA', 'MID', 'wk'),
(gen_random_uuid(), 'Abdullah Al-Khaibari', 'KSA', 'MID', 'wk'),
(gen_random_uuid(), 'Alaa Al-Hejji', 'KSA', 'MID', 'wk'),
(gen_random_uuid(), 'Musab Al-Juwayr', 'KSA', 'MID', 'wk'),
(gen_random_uuid(), 'Sultan Mandash', 'KSA', 'MID', 'wk'),
(gen_random_uuid(), 'Ayman Yahya', 'KSA', 'MID', 'wk'),
(gen_random_uuid(), 'Khalid Al-Ghannam', 'KSA', 'MID', 'wk'),
(gen_random_uuid(), 'Hattan Bahebri', 'KSA', 'MID', 'wk'),
(gen_random_uuid(), 'Salem Al-Dawsari', 'KSA', 'AAN', 'wk'),
(gen_random_uuid(), 'Abdullah Al-Hamdan', 'KSA', 'AAN', 'wk'),
(gen_random_uuid(), 'Feras Al-Brikan', 'KSA', 'AAN', 'wk');

-- Uruguay (URU)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Sergio Rochet', 'URU', 'DOE', 'wk'),
(gen_random_uuid(), 'Fernando Muslera', 'URU', 'DOE', 'wk'),
(gen_random_uuid(), 'Santiago Mele', 'URU', 'DOE', 'wk'),
(gen_random_uuid(), 'Ronald Araújo', 'URU', 'VER', 'wk'),
(gen_random_uuid(), 'José Giménez', 'URU', 'VER', 'wk'),
(gen_random_uuid(), 'Santiago Bueno', 'URU', 'VER', 'wk'),
(gen_random_uuid(), 'Sebastián Cáceres', 'URU', 'VER', 'wk'),
(gen_random_uuid(), 'Mathías Olivera', 'URU', 'VER', 'wk'),
(gen_random_uuid(), 'Joaquín Piquerez', 'URU', 'VER', 'wk'),
(gen_random_uuid(), 'Guillermo Varela', 'URU', 'VER', 'wk'),
(gen_random_uuid(), 'Matías Viña', 'URU', 'VER', 'wk'),
(gen_random_uuid(), 'Manuel Ugarte', 'URU', 'MID', 'wk'),
(gen_random_uuid(), 'Rodrigo Bentancur', 'URU', 'MID', 'wk'),
(gen_random_uuid(), 'Federico Valverde', 'URU', 'MID', 'wk'),
(gen_random_uuid(), 'Giorgian de Arrascaeta', 'URU', 'MID', 'wk'),
(gen_random_uuid(), 'Nicolás de la Cruz', 'URU', 'MID', 'wk'),
(gen_random_uuid(), 'Rodrigo Zalazar', 'URU', 'MID', 'wk'),
(gen_random_uuid(), 'Facundo Pellistri', 'URU', 'MID', 'wk'),
(gen_random_uuid(), 'Agustín Canobbio', 'URU', 'MID', 'wk'),
(gen_random_uuid(), 'Emiliano Martínez', 'URU', 'MID', 'wk'),
(gen_random_uuid(), 'Juan Manuel Sanabria', 'URU', 'MID', 'wk'),
(gen_random_uuid(), 'Darwin Núñez', 'URU', 'AAN', 'wk'),
(gen_random_uuid(), 'Rodrigo Aguirre', 'URU', 'AAN', 'wk'),
(gen_random_uuid(), 'Federico Viñas', 'URU', 'AAN', 'wk'),
(gen_random_uuid(), 'Facundo Torres', 'URU', 'AAN', 'wk'),
(gen_random_uuid(), 'Diego Rossi', 'URU', 'AAN', 'wk');
