export type Positie = "AAN" | "MID" | "VER" | "DOE";

export interface Speler {
  naam: string;
  positie: Positie;
  team: string;
}

// Order: AAN → MID → VER → DOE (meeste kans op scoren eerst)
const CL_FINALE_SPELERS: Speler[] = [
  // ── PSG – Aanvallers ──────────────────────────────────────
  { naam: "Ousmane Dembélé",        positie: "AAN", team: "PSG" },
  { naam: "Khvicha Kvaratskhelia",  positie: "AAN", team: "PSG" },
  { naam: "Bradley Barcola",        positie: "AAN", team: "PSG" },
  { naam: "Désiré Doué",            positie: "AAN", team: "PSG" },
  { naam: "Gonçalo Ramos",          positie: "AAN", team: "PSG" },
  { naam: "Quentin Ndjantou",       positie: "AAN", team: "PSG" },
  { naam: "Ibrahim Mbaye",          positie: "AAN", team: "PSG" },
  // ── PSG – Middenvelders ───────────────────────────────────
  { naam: "Vitinha",                positie: "MID", team: "PSG" },
  { naam: "Fabian Ruiz",            positie: "MID", team: "PSG" },
  { naam: "Warren Zaïre-Emery",     positie: "MID", team: "PSG" },
  { naam: "João Neves",             positie: "MID", team: "PSG" },
  { naam: "Lee Kang-in",            positie: "MID", team: "PSG" },
  { naam: "Senny Mayulu",           positie: "MID", team: "PSG" },
  { naam: "Dro Fernández",          positie: "MID", team: "PSG" },
  // ── PSG – Verdedigers ─────────────────────────────────────
  { naam: "Achraf Hakimi",          positie: "VER", team: "PSG" },
  { naam: "Marquinhos",             positie: "VER", team: "PSG" },
  { naam: "Willian Pacho",          positie: "VER", team: "PSG" },
  { naam: "Lucas Hernández",        positie: "VER", team: "PSG" },
  { naam: "Nuno Mendes",            positie: "VER", team: "PSG" },
  { naam: "Lucas Beraldo",          positie: "VER", team: "PSG" },
  { naam: "Illia Zabarnyi",         positie: "VER", team: "PSG" },
  // ── PSG – Doelmannen ──────────────────────────────────────
  { naam: "Matvey Safonov",         positie: "DOE", team: "PSG" },
  { naam: "Lucas Chevalier",        positie: "DOE", team: "PSG" },
  { naam: "Renato Marin",           positie: "DOE", team: "PSG" },

  // ── Arsenal – Aanvallers ──────────────────────────────────
  { naam: "Viktor Gyökeres",        positie: "AAN", team: "Arsenal" },
  { naam: "Bukayo Saka",            positie: "AAN", team: "Arsenal" },
  { naam: "Eberechi Eze",           positie: "AAN", team: "Arsenal" },
  { naam: "Gabriel Martinelli",     positie: "AAN", team: "Arsenal" },
  { naam: "Noni Madueke",           positie: "AAN", team: "Arsenal" },
  { naam: "Leandro Trossard",       positie: "AAN", team: "Arsenal" },
  { naam: "Kai Havertz",            positie: "AAN", team: "Arsenal" },
  { naam: "Gabriel Jesus",          positie: "AAN", team: "Arsenal" },
  // ── Arsenal – Middenvelders ───────────────────────────────
  { naam: "Martin Ødegaard",        positie: "MID", team: "Arsenal" },
  { naam: "Declan Rice",            positie: "MID", team: "Arsenal" },
  { naam: "Mikel Merino",           positie: "MID", team: "Arsenal" },
  { naam: "Martin Zubimendi",       positie: "MID", team: "Arsenal" },
  { naam: "Christian Nørgaard",     positie: "MID", team: "Arsenal" },
  // ── Arsenal – Verdedigers ─────────────────────────────────
  { naam: "William Saliba",         positie: "VER", team: "Arsenal" },
  { naam: "Gabriel Magalhães",      positie: "VER", team: "Arsenal" },
  { naam: "Riccardo Calafiori",     positie: "VER", team: "Arsenal" },
  { naam: "Myles Lewis-Skelly",     positie: "VER", team: "Arsenal" },
  { naam: "Piero Hincapié",         positie: "VER", team: "Arsenal" },
  { naam: "Cristhian Mosquera",     positie: "VER", team: "Arsenal" },
  { naam: "Jurrien Timber",         positie: "VER", team: "Arsenal" },
  { naam: "Ben White",              positie: "VER", team: "Arsenal" },
  // ── Arsenal – Doelmannen ──────────────────────────────────
  { naam: "David Raya",             positie: "DOE", team: "Arsenal" },
  { naam: "Kepa Arrizabalaga",      positie: "DOE", team: "Arsenal" },
  { naam: "Tommy Setford",          positie: "DOE", team: "Arsenal" },
];

const OEF_NED_ALG_SPELERS: Speler[] = [
  // ── Nederland – Aanvallers ────────────────────────────────
  { naam: "Cody Gakpo",              positie: "AAN", team: "NED" },
  { naam: "Donyell Malen",           positie: "AAN", team: "NED" },
  { naam: "Brian Brobbey",           positie: "AAN", team: "NED" },
  { naam: "Noa Lang",                positie: "AAN", team: "NED" },
  { naam: "Memphis Depay",           positie: "AAN", team: "NED" },
  { naam: "Crysencio Summerville",   positie: "AAN", team: "NED" },
  { naam: "Wout Weghorst",           positie: "AAN", team: "NED" },
  { naam: "Justin Kluivert",         positie: "AAN", team: "NED" },
  // ── Nederland – Middenvelders ─────────────────────────────
  { naam: "Tijjani Reijnders",       positie: "MID", team: "NED" },
  { naam: "Frenkie de Jong",         positie: "MID", team: "NED" },
  { naam: "Ryan Gravenberch",        positie: "MID", team: "NED" },
  { naam: "Teun Koopmeiners",        positie: "MID", team: "NED" },
  { naam: "Marten de Roon",          positie: "MID", team: "NED" },
  { naam: "Guus Til",                positie: "MID", team: "NED" },
  { naam: "Quinten Timber",          positie: "MID", team: "NED" },
  { naam: "Mats Wieffer",            positie: "MID", team: "NED" },
  // ── Nederland – Verdedigers ───────────────────────────────
  { naam: "Virgil van Dijk",         positie: "VER", team: "NED" },
  { naam: "Denzel Dumfries",         positie: "VER", team: "NED" },
  { naam: "Micky van de Ven",        positie: "VER", team: "NED" },
  { naam: "Nathan Aké",              positie: "VER", team: "NED" },
  { naam: "Jan Paul van Hecke",      positie: "VER", team: "NED" },
  { naam: "Jurriën Timber",          positie: "VER", team: "NED" },
  { naam: "Jorrel Hato",             positie: "VER", team: "NED" },
  // ── Nederland – Doelmannen ────────────────────────────────
  { naam: "Bart Verbruggen",         positie: "DOE", team: "NED" },
  { naam: "Mark Flekken",            positie: "DOE", team: "NED" },
  { naam: "Robin Roefs",             positie: "DOE", team: "NED" },

  // ── Algerije – Aanvallers ─────────────────────────────────
  { naam: "Riyad Mahrez",            positie: "AAN", team: "ALG" },
  { naam: "Amine Gouiri",            positie: "AAN", team: "ALG" },
  { naam: "Mohamed Amine Amoura",    positie: "AAN", team: "ALG" },
  { naam: "Anis Hadj Moussa",        positie: "AAN", team: "ALG" },
  { naam: "Nadhir Ben Bouali",       positie: "AAN", team: "ALG" },
  { naam: "Adel Boulbina",           positie: "AAN", team: "ALG" },
  // ── Algerije – Middenvelders ──────────────────────────────
  { naam: "Farès Chaïbi",            positie: "MID", team: "ALG" },
  { naam: "Hicham Boudaoui",         positie: "MID", team: "ALG" },
  { naam: "Houssem Aouar",           positie: "MID", team: "ALG" },
  { naam: "Ramiz Zerrouki",          positie: "MID", team: "ALG" },
  { naam: "Nabil Bentaleb",          positie: "MID", team: "ALG" },
  { naam: "Ismael Bennacer",         positie: "MID", team: "ALG" },
  { naam: "Ibrahim Maza",            positie: "MID", team: "ALG" },
  { naam: "Yacine Titraoui",         positie: "MID", team: "ALG" },
  // ── Algerije – Verdedigers ────────────────────────────────
  { naam: "Ramy Bensebaini",         positie: "VER", team: "ALG" },
  { naam: "Aïssa Mandi",             positie: "VER", team: "ALG" },
  { naam: "Rayan Aït-Nouri",         positie: "VER", team: "ALG" },
  { naam: "Jaouen Hadjam",           positie: "VER", team: "ALG" },
  { naam: "Rafik Belghali",          positie: "VER", team: "ALG" },
  { naam: "Zineddine Belaid",        positie: "VER", team: "ALG" },
  { naam: "Samir Chergui",           positie: "VER", team: "ALG" },
  // ── Algerije – Doelmannen ─────────────────────────────────
  { naam: "Luca Zidane",             positie: "DOE", team: "ALG" },
  { naam: "Melvin Mastil",           positie: "DOE", team: "ALG" },
  { naam: "Oussama Benbot",          positie: "DOE", team: "ALG" },
];

const WK_SPELERS: Speler[] = [
  // ── Nederland (NED) ───────────────────────────────────────
  { naam: "Cody Gakpo",              positie: "AAN", team: "NED" },
  { naam: "Brian Brobbey",           positie: "AAN", team: "NED" },
  { naam: "Donyell Malen",           positie: "AAN", team: "NED" },
  { naam: "Noa Lang",                positie: "AAN", team: "NED" },
  { naam: "Wout Weghorst",           positie: "AAN", team: "NED" },
  { naam: "Memphis Depay",           positie: "AAN", team: "NED" },
  { naam: "Crysencio Summerville",   positie: "AAN", team: "NED" },
  { naam: "Justin Kluivert",         positie: "AAN", team: "NED" },
  { naam: "Tijjani Reijnders",       positie: "MID", team: "NED" },
  { naam: "Frenkie de Jong",         positie: "MID", team: "NED" },
  { naam: "Ryan Gravenberch",        positie: "MID", team: "NED" },
  { naam: "Teun Koopmeiners",        positie: "MID", team: "NED" },
  { naam: "Marten de Roon",          positie: "MID", team: "NED" },
  { naam: "Quinten Timber",          positie: "MID", team: "NED" },
  { naam: "Mats Wieffer",            positie: "MID", team: "NED" },
  { naam: "Virgil van Dijk",         positie: "VER", team: "NED" },
  { naam: "Denzel Dumfries",         positie: "VER", team: "NED" },
  { naam: "Micky van de Ven",        positie: "VER", team: "NED" },
  { naam: "Nathan Aké",              positie: "VER", team: "NED" },
  { naam: "Jurriën Timber",          positie: "VER", team: "NED" },
  { naam: "Jorrel Hato",             positie: "VER", team: "NED" },
  { naam: "Jan Paul van Hecke",      positie: "VER", team: "NED" },
  { naam: "Bart Verbruggen",         positie: "DOE", team: "NED" },
  { naam: "Mark Flekken",            positie: "DOE", team: "NED" },
  { naam: "Robin Roefs",             positie: "DOE", team: "NED" },

  // ── Senegal (SEN) ─────────────────────────────────────────
  { naam: "Sadio Mané",              positie: "AAN", team: "SEN" },
  { naam: "Ismaïla Sarr",            positie: "AAN", team: "SEN" },
  { naam: "Boulaye Dia",             positie: "AAN", team: "SEN" },
  { naam: "Nicolas Jackson",         positie: "AAN", team: "SEN" },
  { naam: "Habib Diallo",            positie: "AAN", team: "SEN" },
  { naam: "Lamine Camara",           positie: "MID", team: "SEN" },
  { naam: "Idrissa Gueye",           positie: "MID", team: "SEN" },
  { naam: "Pape Matar Sarr",         positie: "MID", team: "SEN" },
  { naam: "Nampalys Mendy",          positie: "MID", team: "SEN" },
  { naam: "Krepin Diatta",           positie: "MID", team: "SEN" },
  { naam: "Kalidou Koulibaly",       positie: "VER", team: "SEN" },
  { naam: "Abdou Diallo",            positie: "VER", team: "SEN" },
  { naam: "Formose Mendy",           positie: "VER", team: "SEN" },
  { naam: "Ismail Jakobs",           positie: "VER", team: "SEN" },
  { naam: "Édouard Mendy",           positie: "DOE", team: "SEN" },
  { naam: "Seny Dieng",              positie: "DOE", team: "SEN" },

  // ── Peru (PER) ────────────────────────────────────────────
  { naam: "Gianluca Lapadula",       positie: "AAN", team: "PER" },
  { naam: "Edison Flores",           positie: "AAN", team: "PER" },
  { naam: "André Carrillo",          positie: "AAN", team: "PER" },
  { naam: "Bryan Reyna",             positie: "AAN", team: "PER" },
  { naam: "Joao Grimaldo",           positie: "AAN", team: "PER" },
  { naam: "Renato Tapia",            positie: "MID", team: "PER" },
  { naam: "Yoshimar Yotún",          positie: "MID", team: "PER" },
  { naam: "Jesús Castillo",          positie: "MID", team: "PER" },
  { naam: "Sergio Peña",             positie: "MID", team: "PER" },
  { naam: "Alexander Callens",       positie: "VER", team: "PER" },
  { naam: "Miguel Araujo",           positie: "VER", team: "PER" },
  { naam: "Aldo Corzo",              positie: "VER", team: "PER" },
  { naam: "Pedro Gallese",           positie: "DOE", team: "PER" },

  // ── Nieuw-Zeeland (NZL) ───────────────────────────────────
  { naam: "Chris Wood",              positie: "AAN", team: "NZL" },
  { naam: "Liberato Cacace",         positie: "AAN", team: "NZL" },
  { naam: "Elijah Just",             positie: "AAN", team: "NZL" },
  { naam: "Matthew Garbett",         positie: "MID", team: "NZL" },
  { naam: "Clayton Lewis",           positie: "MID", team: "NZL" },
  { naam: "Joe Bell",                positie: "MID", team: "NZL" },
  { naam: "Finn Surman",             positie: "MID", team: "NZL" },
  { naam: "Winston Reid",            positie: "VER", team: "NZL" },
  { naam: "Michael Boxall",          positie: "VER", team: "NZL" },
  { naam: "Nando de Wys",            positie: "VER", team: "NZL" },
  { naam: "Oliver Sail",             positie: "DOE", team: "NZL" },

  // ── Argentinië (ARG) ──────────────────────────────────────
  { naam: "Lionel Messi",            positie: "AAN", team: "ARG" },
  { naam: "Lautaro Martínez",        positie: "AAN", team: "ARG" },
  { naam: "Julián Álvarez",          positie: "AAN", team: "ARG" },
  { naam: "Ángel Di María",          positie: "AAN", team: "ARG" },
  { naam: "Alejandro Garnacho",      positie: "AAN", team: "ARG" },
  { naam: "Paulo Dybala",            positie: "AAN", team: "ARG" },
  { naam: "Nicolás González",        positie: "AAN", team: "ARG" },
  { naam: "Rodrigo De Paul",         positie: "MID", team: "ARG" },
  { naam: "Enzo Fernández",          positie: "MID", team: "ARG" },
  { naam: "Alexis Mac Allister",     positie: "MID", team: "ARG" },
  { naam: "Leandro Paredes",         positie: "MID", team: "ARG" },
  { naam: "Giovani Lo Celso",        positie: "MID", team: "ARG" },
  { naam: "Lisandro Martínez",       positie: "VER", team: "ARG" },
  { naam: "Cristian Romero",         positie: "VER", team: "ARG" },
  { naam: "Nicolás Otamendi",        positie: "VER", team: "ARG" },
  { naam: "Nahuel Molina",           positie: "VER", team: "ARG" },
  { naam: "Marcos Acuña",            positie: "VER", team: "ARG" },
  { naam: "Emiliano Martínez",       positie: "DOE", team: "ARG" },
  { naam: "Gerónimo Rulli",          positie: "DOE", team: "ARG" },

  // ── VS (USA) ──────────────────────────────────────────────
  { naam: "Christian Pulisic",       positie: "AAN", team: "USA" },
  { naam: "Ricardo Pepi",            positie: "AAN", team: "USA" },
  { naam: "Josh Sargent",            positie: "AAN", team: "USA" },
  { naam: "Gio Reyna",               positie: "AAN", team: "USA" },
  { naam: "Timothy Weah",            positie: "AAN", team: "USA" },
  { naam: "Folarin Balogun",         positie: "AAN", team: "USA" },
  { naam: "Weston McKennie",         positie: "MID", team: "USA" },
  { naam: "Tyler Adams",             positie: "MID", team: "USA" },
  { naam: "Yunus Musah",             positie: "MID", team: "USA" },
  { naam: "Brenden Aaronson",        positie: "MID", team: "USA" },
  { naam: "Miles Robinson",          positie: "VER", team: "USA" },
  { naam: "Antonee Robinson",        positie: "VER", team: "USA" },
  { naam: "Joe Scally",              positie: "VER", team: "USA" },
  { naam: "Chris Richards",          positie: "VER", team: "USA" },
  { naam: "Matt Turner",             positie: "DOE", team: "USA" },
  { naam: "Ethan Horvath",           positie: "DOE", team: "USA" },

  // ── Mexico (MEX) ──────────────────────────────────────────
  { naam: "Hirving Lozano",          positie: "AAN", team: "MEX" },
  { naam: "Raúl Jiménez",            positie: "AAN", team: "MEX" },
  { naam: "Henry Martín",            positie: "AAN", team: "MEX" },
  { naam: "Santiago Giménez",        positie: "AAN", team: "MEX" },
  { naam: "Uriel Antuna",            positie: "AAN", team: "MEX" },
  { naam: "Alexis Vega",             positie: "AAN", team: "MEX" },
  { naam: "Edson Álvarez",           positie: "MID", team: "MEX" },
  { naam: "Orbelin Pineda",          positie: "MID", team: "MEX" },
  { naam: "Carlos Rodríguez",        positie: "MID", team: "MEX" },
  { naam: "Luis Chávez",             positie: "MID", team: "MEX" },
  { naam: "César Montes",            positie: "VER", team: "MEX" },
  { naam: "Jorge Sánchez",           positie: "VER", team: "MEX" },
  { naam: "Jesús Gallardo",          positie: "VER", team: "MEX" },
  { naam: "Johan Vásquez",           positie: "VER", team: "MEX" },
  { naam: "Guillermo Ochoa",         positie: "DOE", team: "MEX" },
  { naam: "Luis Malagón",            positie: "DOE", team: "MEX" },

  // ── Marokko (MAR) ─────────────────────────────────────────
  { naam: "Youssef En-Nesyri",       positie: "AAN", team: "MAR" },
  { naam: "Hakim Ziyech",            positie: "AAN", team: "MAR" },
  { naam: "Soufiane Rahimi",         positie: "AAN", team: "MAR" },
  { naam: "Abde Ezzalzouli",         positie: "AAN", team: "MAR" },
  { naam: "Ayoub El Kaabi",          positie: "AAN", team: "MAR" },
  { naam: "Sofyan Amrabat",          positie: "MID", team: "MAR" },
  { naam: "Azzedine Ounahi",         positie: "MID", team: "MAR" },
  { naam: "Selim Amallah",           positie: "MID", team: "MAR" },
  { naam: "Bilal El Khannouss",      positie: "MID", team: "MAR" },
  { naam: "Achraf Hakimi",           positie: "VER", team: "MAR" },
  { naam: "Nayef Aguerd",            positie: "VER", team: "MAR" },
  { naam: "Romain Saïss",            positie: "VER", team: "MAR" },
  { naam: "Noussair Mazraoui",       positie: "VER", team: "MAR" },
  { naam: "Yassine Bounou",          positie: "DOE", team: "MAR" },
  { naam: "Munir Mohamedi",          positie: "DOE", team: "MAR" },

  // ── Brazilië (BRA) ────────────────────────────────────────
  { naam: "Vinicius Junior",         positie: "AAN", team: "BRA" },
  { naam: "Rodrygo",                 positie: "AAN", team: "BRA" },
  { naam: "Endrick",                 positie: "AAN", team: "BRA" },
  { naam: "Raphinha",                positie: "AAN", team: "BRA" },
  { naam: "Gabriel Martinelli",      positie: "AAN", team: "BRA" },
  { naam: "Savinho",                 positie: "AAN", team: "BRA" },
  { naam: "Bruno Guimarães",         positie: "MID", team: "BRA" },
  { naam: "Lucas Paquetá",           positie: "MID", team: "BRA" },
  { naam: "Gerson",                  positie: "MID", team: "BRA" },
  { naam: "Andreas Pereira",         positie: "MID", team: "BRA" },
  { naam: "Marquinhos",              positie: "VER", team: "BRA" },
  { naam: "Militão",                 positie: "VER", team: "BRA" },
  { naam: "Danilo",                  positie: "VER", team: "BRA" },
  { naam: "Alex Sandro",             positie: "VER", team: "BRA" },
  { naam: "Wendell",                 positie: "VER", team: "BRA" },
  { naam: "Alisson",                 positie: "DOE", team: "BRA" },
  { naam: "Ederson",                 positie: "DOE", team: "BRA" },

  // ── Kroatië (CRO) ─────────────────────────────────────────
  { naam: "Ivan Perišić",            positie: "AAN", team: "CRO" },
  { naam: "Andrej Kramarić",         positie: "AAN", team: "CRO" },
  { naam: "Bruno Petković",          positie: "AAN", team: "CRO" },
  { naam: "Marko Livaja",            positie: "AAN", team: "CRO" },
  { naam: "Luka Modrić",             positie: "MID", team: "CRO" },
  { naam: "Mateo Kovačić",           positie: "MID", team: "CRO" },
  { naam: "Marcelo Brozović",        positie: "MID", team: "CRO" },
  { naam: "Lovro Majer",             positie: "MID", team: "CRO" },
  { naam: "Nikola Vlašić",           positie: "MID", team: "CRO" },
  { naam: "Joško Gvardiol",          positie: "VER", team: "CRO" },
  { naam: "Dejan Lovren",            positie: "VER", team: "CRO" },
  { naam: "Josip Juranović",         positie: "VER", team: "CRO" },
  { naam: "Dominik Livaković",       positie: "DOE", team: "CRO" },

  // ── Zwitserland (SUI) ─────────────────────────────────────
  { naam: "Breel Embolo",            positie: "AAN", team: "SUI" },
  { naam: "Ruben Vargas",            positie: "AAN", team: "SUI" },
  { naam: "Noah Okafor",             positie: "AAN", team: "SUI" },
  { naam: "Dan Ndoye",               positie: "AAN", team: "SUI" },
  { naam: "Granit Xhaka",            positie: "MID", team: "SUI" },
  { naam: "Remo Freuler",            positie: "MID", team: "SUI" },
  { naam: "Denis Zakaria",           positie: "MID", team: "SUI" },
  { naam: "Fabian Rieder",           positie: "MID", team: "SUI" },
  { naam: "Xherdan Shaqiri",         positie: "MID", team: "SUI" },
  { naam: "Manuel Akanji",           positie: "VER", team: "SUI" },
  { naam: "Nico Elvedi",             positie: "VER", team: "SUI" },
  { naam: "Ricardo Rodríguez",       positie: "VER", team: "SUI" },
  { naam: "Yann Sommer",             positie: "DOE", team: "SUI" },
  { naam: "Gregor Kobel",            positie: "DOE", team: "SUI" },

  // ── Australië (AUS) ───────────────────────────────────────
  { naam: "Mitchell Duke",           positie: "AAN", team: "AUS" },
  { naam: "Jamie Maclaren",          positie: "AAN", team: "AUS" },
  { naam: "Martin Boyle",            positie: "AAN", team: "AUS" },
  { naam: "Craig Goodwin",           positie: "AAN", team: "AUS" },
  { naam: "Ajdin Hrustic",           positie: "MID", team: "AUS" },
  { naam: "Jackson Irvine",          positie: "MID", team: "AUS" },
  { naam: "Riley McGree",            positie: "MID", team: "AUS" },
  { naam: "Keanu Baccus",            positie: "MID", team: "AUS" },
  { naam: "Harry Souttar",           positie: "VER", team: "AUS" },
  { naam: "Miloš Degenek",           positie: "VER", team: "AUS" },
  { naam: "Aziz Behich",             positie: "VER", team: "AUS" },
  { naam: "Mathew Ryan",             positie: "DOE", team: "AUS" },

  // ── Duitsland (GER) ───────────────────────────────────────
  { naam: "Jamal Musiala",           positie: "AAN", team: "GER" },
  { naam: "Florian Wirtz",           positie: "AAN", team: "GER" },
  { naam: "Kai Havertz",             positie: "AAN", team: "GER" },
  { naam: "Leroy Sané",              positie: "AAN", team: "GER" },
  { naam: "Thomas Müller",           positie: "AAN", team: "GER" },
  { naam: "Serge Gnabry",            positie: "AAN", team: "GER" },
  { naam: "Christopher Nkunku",      positie: "AAN", team: "GER" },
  { naam: "Joshua Kimmich",          positie: "MID", team: "GER" },
  { naam: "Toni Kroos",              positie: "MID", team: "GER" },
  { naam: "İlkay Gündoğan",          positie: "MID", team: "GER" },
  { naam: "Leon Goretzka",           positie: "MID", team: "GER" },
  { naam: "Aleksandar Pavlović",     positie: "MID", team: "GER" },
  { naam: "Antonio Rüdiger",         positie: "VER", team: "GER" },
  { naam: "Jonathan Tah",            positie: "VER", team: "GER" },
  { naam: "David Raum",              positie: "VER", team: "GER" },
  { naam: "Benjamin Henrichs",       positie: "VER", team: "GER" },
  { naam: "Manuel Neuer",            positie: "DOE", team: "GER" },
  { naam: "Marc-André ter Stegen",   positie: "DOE", team: "GER" },
  { naam: "Oliver Baumann",          positie: "DOE", team: "GER" },

  // ── Portugal (POR) ────────────────────────────────────────
  { naam: "Cristiano Ronaldo",       positie: "AAN", team: "POR" },
  { naam: "Rafael Leão",             positie: "AAN", team: "POR" },
  { naam: "Pedro Neto",              positie: "AAN", team: "POR" },
  { naam: "Gonçalo Ramos",           positie: "AAN", team: "POR" },
  { naam: "Francisco Conceição",     positie: "AAN", team: "POR" },
  { naam: "João Félix",              positie: "AAN", team: "POR" },
  { naam: "Bruno Fernandes",         positie: "MID", team: "POR" },
  { naam: "Bernardo Silva",          positie: "MID", team: "POR" },
  { naam: "Vitinha",                 positie: "MID", team: "POR" },
  { naam: "João Neves",              positie: "MID", team: "POR" },
  { naam: "Rúben Neves",             positie: "MID", team: "POR" },
  { naam: "Rúben Dias",              positie: "VER", team: "POR" },
  { naam: "Pepe",                    positie: "VER", team: "POR" },
  { naam: "João Cancelo",            positie: "VER", team: "POR" },
  { naam: "Nuno Mendes",             positie: "VER", team: "POR" },
  { naam: "Diogo Dalot",             positie: "VER", team: "POR" },
  { naam: "Diogo Costa",             positie: "DOE", team: "POR" },
  { naam: "Rui Patrício",            positie: "DOE", team: "POR" },

  // ── Turkije (TUR) ─────────────────────────────────────────
  { naam: "Arda Güler",              positie: "AAN", team: "TUR" },
  { naam: "Kerem Aktürkoğlu",        positie: "AAN", team: "TUR" },
  { naam: "Barış Alper Yılmaz",      positie: "AAN", team: "TUR" },
  { naam: "Cenk Tosun",              positie: "AAN", team: "TUR" },
  { naam: "Yunus Akgün",             positie: "AAN", team: "TUR" },
  { naam: "Hakan Çalhanoğlu",        positie: "MID", team: "TUR" },
  { naam: "Orkun Kökçü",             positie: "MID", team: "TUR" },
  { naam: "Kaan Ayhan",              positie: "MID", team: "TUR" },
  { naam: "Okay Yokuşlu",            positie: "MID", team: "TUR" },
  { naam: "Samet Akaydın",           positie: "VER", team: "TUR" },
  { naam: "Zeki Çelik",              positie: "VER", team: "TUR" },
  { naam: "Ferdi Kadıoğlu",          positie: "VER", team: "TUR" },
  { naam: "Merih Demiral",           positie: "VER", team: "TUR" },
  { naam: "Mert Günok",              positie: "DOE", team: "TUR" },
  { naam: "Altay Bayındır",          positie: "DOE", team: "TUR" },

  // ── Spanje (ESP) ──────────────────────────────────────────
  { naam: "Lamine Yamal",            positie: "AAN", team: "ESP" },
  { naam: "Nico Williams",           positie: "AAN", team: "ESP" },
  { naam: "Álvaro Morata",           positie: "AAN", team: "ESP" },
  { naam: "Mikel Oyarzabal",         positie: "AAN", team: "ESP" },
  { naam: "Ferran Torres",           positie: "AAN", team: "ESP" },
  { naam: "Bryan Zaragoza",          positie: "AAN", team: "ESP" },
  { naam: "Pedri",                   positie: "MID", team: "ESP" },
  { naam: "Gavi",                    positie: "MID", team: "ESP" },
  { naam: "Rodri",                   positie: "MID", team: "ESP" },
  { naam: "Fabian Ruiz",             positie: "MID", team: "ESP" },
  { naam: "Dani Olmo",               positie: "MID", team: "ESP" },
  { naam: "Martín Zubimendi",        positie: "MID", team: "ESP" },
  { naam: "Daniel Carvajal",         positie: "VER", team: "ESP" },
  { naam: "Alejandro Grimaldo",      positie: "VER", team: "ESP" },
  { naam: "Aymeric Laporte",         positie: "VER", team: "ESP" },
  { naam: "Robin Le Normand",        positie: "VER", team: "ESP" },
  { naam: "Pau Cubarsí",             positie: "VER", team: "ESP" },
  { naam: "Unai Simón",              positie: "DOE", team: "ESP" },
  { naam: "David Raya",              positie: "DOE", team: "ESP" },

  // ── Engeland (ENG) ────────────────────────────────────────
  { naam: "Harry Kane",              positie: "AAN", team: "ENG" },
  { naam: "Jude Bellingham",         positie: "AAN", team: "ENG" },
  { naam: "Bukayo Saka",             positie: "AAN", team: "ENG" },
  { naam: "Phil Foden",              positie: "AAN", team: "ENG" },
  { naam: "Marcus Rashford",         positie: "AAN", team: "ENG" },
  { naam: "Cole Palmer",             positie: "AAN", team: "ENG" },
  { naam: "Ollie Watkins",           positie: "AAN", team: "ENG" },
  { naam: "Anthony Gordon",          positie: "AAN", team: "ENG" },
  { naam: "Declan Rice",             positie: "MID", team: "ENG" },
  { naam: "Kobbie Mainoo",           positie: "MID", team: "ENG" },
  { naam: "Conor Gallagher",         positie: "MID", team: "ENG" },
  { naam: "Trent Alexander-Arnold",  positie: "VER", team: "ENG" },
  { naam: "Kieran Trippier",         positie: "VER", team: "ENG" },
  { naam: "John Stones",             positie: "VER", team: "ENG" },
  { naam: "Marc Guéhi",              positie: "VER", team: "ENG" },
  { naam: "Luke Shaw",               positie: "VER", team: "ENG" },
  { naam: "Jordan Pickford",         positie: "DOE", team: "ENG" },
  { naam: "Aaron Ramsdale",          positie: "DOE", team: "ENG" },

  // ── Uruguay (URU) ─────────────────────────────────────────
  { naam: "Darwin Núñez",            positie: "AAN", team: "URU" },
  { naam: "Facundo Pellistri",       positie: "AAN", team: "URU" },
  { naam: "Maximiliano Araújo",      positie: "AAN", team: "URU" },
  { naam: "Agustín Canobbio",        positie: "AAN", team: "URU" },
  { naam: "Federico Valverde",       positie: "MID", team: "URU" },
  { naam: "Rodrigo Bentancur",       positie: "MID", team: "URU" },
  { naam: "Manuel Ugarte",           positie: "MID", team: "URU" },
  { naam: "Nicolás De La Cruz",      positie: "MID", team: "URU" },
  { naam: "José María Giménez",      positie: "VER", team: "URU" },
  { naam: "Ronald Araújo",           positie: "VER", team: "URU" },
  { naam: "Matías Viña",             positie: "VER", team: "URU" },
  { naam: "Nahitan Nández",          positie: "VER", team: "URU" },
  { naam: "Sergio Rochet",           positie: "DOE", team: "URU" },

  // ── Servië (SRB) ──────────────────────────────────────────
  { naam: "Dušan Vlahović",          positie: "AAN", team: "SRB" },
  { naam: "Aleksandar Mitrović",     positie: "AAN", team: "SRB" },
  { naam: "Filip Kostić",            positie: "AAN", team: "SRB" },
  { naam: "Dušan Tadić",             positie: "AAN", team: "SRB" },
  { naam: "Luka Jović",              positie: "AAN", team: "SRB" },
  { naam: "Sergej Milinković-Savić", positie: "MID", team: "SRB" },
  { naam: "Nemanja Gudelj",          positie: "MID", team: "SRB" },
  { naam: "Saša Lukić",              positie: "MID", team: "SRB" },
  { naam: "Ivan Ilić",               positie: "MID", team: "SRB" },
  { naam: "Nikola Milenković",       positie: "VER", team: "SRB" },
  { naam: "Strahinja Pavlović",      positie: "VER", team: "SRB" },
  { naam: "Filip Mladenović",        positie: "VER", team: "SRB" },
  { naam: "Predrag Rajković",        positie: "DOE", team: "SRB" },
  { naam: "Vanja Milinković-Savić",  positie: "DOE", team: "SRB" },

  // ── Ivoorkust (CIV) ───────────────────────────────────────
  { naam: "Sébastien Haller",        positie: "AAN", team: "CIV" },
  { naam: "Wilfried Zaha",           positie: "AAN", team: "CIV" },
  { naam: "Franck Kessié",           positie: "MID", team: "CIV" },
  { naam: "Jean Michaël Seri",       positie: "MID", team: "CIV" },
  { naam: "Seko Fofana",             positie: "MID", team: "CIV" },
  { naam: "Maxwel Cornet",           positie: "AAN", team: "CIV" },
  { naam: "Simon Adingra",           positie: "AAN", team: "CIV" },
  { naam: "Eric Bailly",             positie: "VER", team: "CIV" },
  { naam: "Serge Aurier",            positie: "VER", team: "CIV" },
  { naam: "Willy Boly",              positie: "VER", team: "CIV" },
  { naam: "Yahia Fofana",            positie: "DOE", team: "CIV" },

  // ── Frankrijk (FRA) ───────────────────────────────────────
  { naam: "Kylian Mbappé",           positie: "AAN", team: "FRA" },
  { naam: "Ousmane Dembélé",         positie: "AAN", team: "FRA" },
  { naam: "Marcus Thuram",           positie: "AAN", team: "FRA" },
  { naam: "Randal Kolo Muani",       positie: "AAN", team: "FRA" },
  { naam: "Bradley Barcola",         positie: "AAN", team: "FRA" },
  { naam: "Antoine Griezmann",       positie: "AAN", team: "FRA" },
  { naam: "Kingsley Coman",          positie: "AAN", team: "FRA" },
  { naam: "N'Golo Kanté",            positie: "MID", team: "FRA" },
  { naam: "Aurélien Tchouaméni",     positie: "MID", team: "FRA" },
  { naam: "Adrien Rabiot",           positie: "MID", team: "FRA" },
  { naam: "Warren Zaïre-Emery",      positie: "MID", team: "FRA" },
  { naam: "Youssouf Fofana",         positie: "MID", team: "FRA" },
  { naam: "Jules Koundé",            positie: "VER", team: "FRA" },
  { naam: "Dayot Upamecano",         positie: "VER", team: "FRA" },
  { naam: "William Saliba",          positie: "VER", team: "FRA" },
  { naam: "Théo Hernández",          positie: "VER", team: "FRA" },
  { naam: "Mike Maignan",            positie: "DOE", team: "FRA" },
  { naam: "Alphonse Areola",         positie: "DOE", team: "FRA" },

  // ── Nigeria (NGA) ─────────────────────────────────────────
  { naam: "Victor Osimhen",          positie: "AAN", team: "NGA" },
  { naam: "Ademola Lookman",         positie: "AAN", team: "NGA" },
  { naam: "Samuel Chukwueze",        positie: "AAN", team: "NGA" },
  { naam: "Kelechi Iheanacho",       positie: "AAN", team: "NGA" },
  { naam: "Paul Onuachu",            positie: "AAN", team: "NGA" },
  { naam: "Alex Iwobi",              positie: "MID", team: "NGA" },
  { naam: "Wilfred Ndidi",           positie: "MID", team: "NGA" },
  { naam: "Frank Onyeka",            positie: "MID", team: "NGA" },
  { naam: "Joe Aribo",               positie: "MID", team: "NGA" },
  { naam: "Semi Ajayi",              positie: "VER", team: "NGA" },
  { naam: "William Troost-Ekong",    positie: "VER", team: "NGA" },
  { naam: "Zaidu Sanusi",            positie: "VER", team: "NGA" },
  { naam: "Stanley Nwabali",         positie: "DOE", team: "NGA" },
  { naam: "Francis Uzoho",           positie: "DOE", team: "NGA" },

  // ── Colombia (COL) ────────────────────────────────────────
  { naam: "Luis Díaz",               positie: "AAN", team: "COL" },
  { naam: "Rafael Santos Borré",     positie: "AAN", team: "COL" },
  { naam: "Jhon Córdoba",            positie: "AAN", team: "COL" },
  { naam: "Cucho Hernández",         positie: "AAN", team: "COL" },
  { naam: "James Rodríguez",         positie: "MID", team: "COL" },
  { naam: "Juan Cuadrado",           positie: "MID", team: "COL" },
  { naam: "Moisés Caicedo",          positie: "MID", team: "COL" },
  { naam: "Richard Ríos",            positie: "MID", team: "COL" },
  { naam: "Jefferson Lerma",         positie: "MID", team: "COL" },
  { naam: "Dávinson Sánchez",        positie: "VER", team: "COL" },
  { naam: "Yerry Mina",              positie: "VER", team: "COL" },
  { naam: "Johan Mojica",            positie: "VER", team: "COL" },
  { naam: "Camilo Vargas",           positie: "DOE", team: "COL" },

  // ── Ecuador (ECU) ─────────────────────────────────────────
  { naam: "Enner Valencia",          positie: "AAN", team: "ECU" },
  { naam: "Jeremy Sarmiento",        positie: "AAN", team: "ECU" },
  { naam: "Gonzalo Plata",           positie: "AAN", team: "ECU" },
  { naam: "Kevin Rodríguez",         positie: "AAN", team: "ECU" },
  { naam: "Moisés Caicedo",          positie: "MID", team: "ECU" },
  { naam: "Romario Ibarra",          positie: "MID", team: "ECU" },
  { naam: "José Cifuentes",          positie: "MID", team: "ECU" },
  { naam: "Ángelo Preciado",         positie: "VER", team: "ECU" },
  { naam: "Félix Torres",            positie: "VER", team: "ECU" },
  { naam: "Piero Hincapié",          positie: "VER", team: "ECU" },
  { naam: "Hernán Galíndez",         positie: "DOE", team: "ECU" },

  // ── België (BEL) ──────────────────────────────────────────
  { naam: "Romelu Lukaku",           positie: "AAN", team: "BEL" },
  { naam: "Leandro Trossard",        positie: "AAN", team: "BEL" },
  { naam: "Lois Openda",             positie: "AAN", team: "BEL" },
  { naam: "Dodi Lukebakio",          positie: "AAN", team: "BEL" },
  { naam: "Jeremy Doku",             positie: "AAN", team: "BEL" },
  { naam: "Kevin De Bruyne",         positie: "MID", team: "BEL" },
  { naam: "Youri Tielemans",         positie: "MID", team: "BEL" },
  { naam: "Axel Witsel",             positie: "MID", team: "BEL" },
  { naam: "Amadou Onana",            positie: "MID", team: "BEL" },
  { naam: "Arthur Theate",           positie: "VER", team: "BEL" },
  { naam: "Wout Faes",               positie: "VER", team: "BEL" },
  { naam: "Timothy Castagne",        positie: "VER", team: "BEL" },
  { naam: "Jan Vertonghen",          positie: "VER", team: "BEL" },
  { naam: "Koen Casteels",           positie: "DOE", team: "BEL" },
  { naam: "Thibaut Courtois",        positie: "DOE", team: "BEL" },

  // ── Japan (JPN) ───────────────────────────────────────────
  { naam: "Kaoru Mitoma",            positie: "AAN", team: "JPN" },
  { naam: "Ritsu Doan",              positie: "AAN", team: "JPN" },
  { naam: "Takumi Minamino",         positie: "AAN", team: "JPN" },
  { naam: "Junya Ito",               positie: "AAN", team: "JPN" },
  { naam: "Ayase Ueda",              positie: "AAN", team: "JPN" },
  { naam: "Daichi Kamada",           positie: "MID", team: "JPN" },
  { naam: "Wataru Endō",             positie: "MID", team: "JPN" },
  { naam: "Hidemasa Morita",         positie: "MID", team: "JPN" },
  { naam: "Gaku Shibasaki",          positie: "MID", team: "JPN" },
  { naam: "Ko Itakura",              positie: "VER", team: "JPN" },
  { naam: "Takehiro Tomiyasu",       positie: "VER", team: "JPN" },
  { naam: "Hiroki Sakai",            positie: "VER", team: "JPN" },
  { naam: "Shuichi Gonda",           positie: "DOE", team: "JPN" },

  // ── Zuid-Korea (KOR) ──────────────────────────────────────
  { naam: "Son Heung-min",           positie: "AAN", team: "KOR" },
  { naam: "Hwang Hee-chan",          positie: "AAN", team: "KOR" },
  { naam: "Cho Gue-sung",            positie: "AAN", team: "KOR" },
  { naam: "Lee Kang-in",             positie: "MID", team: "KOR" },
  { naam: "Hwang In-beom",           positie: "MID", team: "KOR" },
  { naam: "Jung Woo-young",          positie: "MID", team: "KOR" },
  { naam: "Paik Seung-ho",           positie: "MID", team: "KOR" },
  { naam: "Kim Min-jae",             positie: "VER", team: "KOR" },
  { naam: "Kim Young-gwon",          positie: "VER", team: "KOR" },
  { naam: "Kim Jin-su",              positie: "VER", team: "KOR" },
  { naam: "Kim Seung-gyu",           positie: "DOE", team: "KOR" },

  // ── Chili (CHI) ───────────────────────────────────────────
  { naam: "Ben Brereton Díaz",       positie: "AAN", team: "CHI" },
  { naam: "Alexis Sánchez",          positie: "AAN", team: "CHI" },
  { naam: "Eduardo Vargas",          positie: "AAN", team: "CHI" },
  { naam: "Darío Osorio",            positie: "AAN", team: "CHI" },
  { naam: "Arturo Vidal",            positie: "MID", team: "CHI" },
  { naam: "Charles Aránguiz",        positie: "MID", team: "CHI" },
  { naam: "Marcelino Núñez",         positie: "MID", team: "CHI" },
  { naam: "Rodrigo Echeverría",      positie: "MID", team: "CHI" },
  { naam: "Guillermo Maripán",       positie: "VER", team: "CHI" },
  { naam: "Paulo Díaz",              positie: "VER", team: "CHI" },
  { naam: "Gabriel Suazo",           positie: "VER", team: "CHI" },
  { naam: "Claudio Bravo",           positie: "DOE", team: "CHI" },

  // ── Polen (POL) ───────────────────────────────────────────
  { naam: "Robert Lewandowski",      positie: "AAN", team: "POL" },
  { naam: "Arkadiusz Milik",         positie: "AAN", team: "POL" },
  { naam: "Karol Świderski",         positie: "AAN", team: "POL" },
  { naam: "Piotr Zieliński",         positie: "MID", team: "POL" },
  { naam: "Kacper Urbański",         positie: "MID", team: "POL" },
  { naam: "Nicola Zalewski",         positie: "MID", team: "POL" },
  { naam: "Kamil Grosicki",          positie: "AAN", team: "POL" },
  { naam: "Sebastian Szymański",     positie: "MID", team: "POL" },
  { naam: "Jan Bednarek",            positie: "VER", team: "POL" },
  { naam: "Bartosz Bereszyński",     positie: "VER", team: "POL" },
  { naam: "Wojciech Szczęsny",       positie: "DOE", team: "POL" },
  { naam: "Łukasz Skorupski",        positie: "DOE", team: "POL" },

  // ── Kameroen (CMR) ────────────────────────────────────────
  { naam: "André Onana",             positie: "DOE", team: "CMR" },
  { naam: "Vincent Aboubakar",       positie: "AAN", team: "CMR" },
  { naam: "Bryan Mbeumo",            positie: "AAN", team: "CMR" },
  { naam: "Karl Toko Ekambi",        positie: "AAN", team: "CMR" },
  { naam: "Nicolas Ngamaleu",        positie: "AAN", team: "CMR" },
  { naam: "Martin Hongla",           positie: "MID", team: "CMR" },
  { naam: "André-Frank Zambo Anguissa", positie: "MID", team: "CMR" },
  { naam: "Samuel Oum Gouet",        positie: "MID", team: "CMR" },
  { naam: "Collins Fai",             positie: "VER", team: "CMR" },
  { naam: "Michael Ngadeu-Ngadjui",  positie: "VER", team: "CMR" },
  { naam: "Jean-Charles Castelletto", positie: "VER", team: "CMR" },

  // ── Qatar (QAT) ───────────────────────────────────────────
  { naam: "Akram Afif",              positie: "AAN", team: "QAT" },
  { naam: "Almoez Ali",              positie: "AAN", team: "QAT" },
  { naam: "Hassan Al-Haydos",        positie: "AAN", team: "QAT" },
  { naam: "Ismaeel Mohammad",        positie: "MID", team: "QAT" },
  { naam: "Karim Boudiaf",           positie: "MID", team: "QAT" },
  { naam: "Abdulaziz Hatem",         positie: "MID", team: "QAT" },
  { naam: "Bassam Al-Rawi",          positie: "VER", team: "QAT" },
  { naam: "Pedro Miguel",            positie: "VER", team: "QAT" },
  { naam: "Homam Ahmed",             positie: "VER", team: "QAT" },
  { naam: "Meshaal Barsham",         positie: "DOE", team: "QAT" },
];

export function getSpelers(soort: string): Speler[] {
  if (soort === "cl_finale") return CL_FINALE_SPELERS;
  if (soort === "oefenwedstrijd") return OEF_NED_ALG_SPELERS;
  if (soort === "wk") return WK_SPELERS;
  return [];
}
