-- Verwijder foute teams die niet in WK 2026 zitten
DELETE FROM "Speler" WHERE soort = 'wk' AND team IN ('CHI','CMR','NGA','PER','POL','SRB');

-- Voeg ontbrekende WK 2026 teams toe
INSERT INTO "Speler" (id, naam, positie, team, soort) VALUES

-- Kaapverdië (CPV)
(gen_random_uuid()::text,'Garry Rodrigues','AAN','CPV','wk'),
(gen_random_uuid()::text,'Ryan Mendes','AAN','CPV','wk'),
(gen_random_uuid()::text,'Bebé','AAN','CPV','wk'),
(gen_random_uuid()::text,'Jamiro Monteiro','MID','CPV','wk'),
(gen_random_uuid()::text,'Júlio Tavares','MID','CPV','wk'),
(gen_random_uuid()::text,'Kenny Rocha','MID','CPV','wk'),
(gen_random_uuid()::text,'Diney','MID','CPV','wk'),
(gen_random_uuid()::text,'Stopira','VER','CPV','wk'),
(gen_random_uuid()::text,'Zé Lopes','VER','CPV','wk'),
(gen_random_uuid()::text,'Steven Fortes','VER','CPV','wk'),
(gen_random_uuid()::text,'Óscar Maciel','VER','CPV','wk'),
(gen_random_uuid()::text,'Vozinha','DOE','CPV','wk'),
(gen_random_uuid()::text,'Marcelo Bobo','DOE','CPV','wk'),

-- Zweden (SWE)
(gen_random_uuid()::text,'Alexander Isak','AAN','SWE','wk'),
(gen_random_uuid()::text,'Dejan Kulusevski','AAN','SWE','wk'),
(gen_random_uuid()::text,'Viktor Gyökeres','AAN','SWE','wk'),
(gen_random_uuid()::text,'Anthony Elanga','AAN','SWE','wk'),
(gen_random_uuid()::text,'Robin Quaison','AAN','SWE','wk'),
(gen_random_uuid()::text,'Mattias Svanberg','MID','SWE','wk'),
(gen_random_uuid()::text,'Albin Ekdal','MID','SWE','wk'),
(gen_random_uuid()::text,'Jesper Karlsson','MID','SWE','wk'),
(gen_random_uuid()::text,'Samuel Gustafson','MID','SWE','wk'),
(gen_random_uuid()::text,'Emil Forsberg','MID','SWE','wk'),
(gen_random_uuid()::text,'Victor Lindelöf','VER','SWE','wk'),
(gen_random_uuid()::text,'Isak Hien','VER','SWE','wk'),
(gen_random_uuid()::text,'Marcus Danielson','VER','SWE','wk'),
(gen_random_uuid()::text,'Mikael Lustig','VER','SWE','wk'),
(gen_random_uuid()::text,'Ludwig Augustinsson','VER','SWE','wk'),
(gen_random_uuid()::text,'Robin Olsen','DOE','SWE','wk'),
(gen_random_uuid()::text,'Karl-Johan Johnsson','DOE','SWE','wk'),

-- Tunesië (TUN)
(gen_random_uuid()::text,'Youssef Msakni','AAN','TUN','wk'),
(gen_random_uuid()::text,'Wahbi Khazri','AAN','TUN','wk'),
(gen_random_uuid()::text,'Seifeddine Jaziri','AAN','TUN','wk'),
(gen_random_uuid()::text,'Taha Yassine Khenissi','AAN','TUN','wk'),
(gen_random_uuid()::text,'Anis Ben Slimane','MID','TUN','wk'),
(gen_random_uuid()::text,'Ellyes Skhiri','MID','TUN','wk'),
(gen_random_uuid()::text,'Ferjani Sassi','MID','TUN','wk'),
(gen_random_uuid()::text,'Hannibal Mejbri','MID','TUN','wk'),
(gen_random_uuid()::text,'Ali Maâloul','VER','TUN','wk'),
(gen_random_uuid()::text,'Montassar Talbi','VER','TUN','wk'),
(gen_random_uuid()::text,'Dylan Bronn','VER','TUN','wk'),
(gen_random_uuid()::text,'Wajdi Kechrida','VER','TUN','wk'),
(gen_random_uuid()::text,'Nader Ghandri','VER','TUN','wk'),
(gen_random_uuid()::text,'Aymen Dahmen','DOE','TUN','wk'),
(gen_random_uuid()::text,'Farouk Ben Mustapha','DOE','TUN','wk'),

-- Egypte (EGY)
(gen_random_uuid()::text,'Mohamed Salah','AAN','EGY','wk'),
(gen_random_uuid()::text,'Omar Marmoush','AAN','EGY','wk'),
(gen_random_uuid()::text,'Mostafa Mohamed','AAN','EGY','wk'),
(gen_random_uuid()::text,'Zizo','AAN','EGY','wk'),
(gen_random_uuid()::text,'Trezeguet','AAN','EGY','wk'),
(gen_random_uuid()::text,'Tarek Hamed','MID','EGY','wk'),
(gen_random_uuid()::text,'Mahmoud Trezeguet','MID','EGY','wk'),
(gen_random_uuid()::text,'Amr El-Sulaya','MID','EGY','wk'),
(gen_random_uuid()::text,'Emam Ashour','MID','EGY','wk'),
(gen_random_uuid()::text,'Ahmed Hegazy','VER','EGY','wk'),
(gen_random_uuid()::text,'Omar Kamal','VER','EGY','wk'),
(gen_random_uuid()::text,'Mahmoud Hamdi','VER','EGY','wk'),
(gen_random_uuid()::text,'Mohamed Abdel-Moneim','VER','EGY','wk'),
(gen_random_uuid()::text,'Mohamed El-Shenawy','DOE','EGY','wk'),
(gen_random_uuid()::text,'Mostafa Shobeir','DOE','EGY','wk'),

-- Iran (IRN)
(gen_random_uuid()::text,'Mehdi Taremi','AAN','IRN','wk'),
(gen_random_uuid()::text,'Sardar Azmoun','AAN','IRN','wk'),
(gen_random_uuid()::text,'Allahyar Sayyadmanesh','AAN','IRN','wk'),
(gen_random_uuid()::text,'Karim Ansarifard','AAN','IRN','wk'),
(gen_random_uuid()::text,'Ali Gholizadeh','AAN','IRN','wk'),
(gen_random_uuid()::text,'Saeid Ezatolahi','MID','IRN','wk'),
(gen_random_uuid()::text,'Ahmad Noorollahi','MID','IRN','wk'),
(gen_random_uuid()::text,'Saman Ghoddos','MID','IRN','wk'),
(gen_random_uuid()::text,'Vahid Amiri','MID','IRN','wk'),
(gen_random_uuid()::text,'Ehsan Hajsafi','VER','IRN','wk'),
(gen_random_uuid()::text,'Milad Mohammadi','VER','IRN','wk'),
(gen_random_uuid()::text,'Morteza Pouraliganji','VER','IRN','wk'),
(gen_random_uuid()::text,'Shoja Khalilzadeh','VER','IRN','wk'),
(gen_random_uuid()::text,'Majid Hosseini','VER','IRN','wk'),
(gen_random_uuid()::text,'Alireza Beiranvand','DOE','IRN','wk'),
(gen_random_uuid()::text,'Hossein Hosseini','DOE','IRN','wk'),

-- Saoedi-Arabië (KSA)
(gen_random_uuid()::text,'Salem Al-Dawsari','AAN','KSA','wk'),
(gen_random_uuid()::text,'Firas Al-Buraikan','AAN','KSA','wk'),
(gen_random_uuid()::text,'Saleh Al-Shehri','AAN','KSA','wk'),
(gen_random_uuid()::text,'Abdullah Al-Hamdan','AAN','KSA','wk'),
(gen_random_uuid()::text,'Sami Al-Najei','MID','KSA','wk'),
(gen_random_uuid()::text,'Mohammed Al-Qasem','MID','KSA','wk'),
(gen_random_uuid()::text,'Nasser Al-Dawsari','MID','KSA','wk'),
(gen_random_uuid()::text,'Ali Al-Hassan','MID','KSA','wk'),
(gen_random_uuid()::text,'Mohamed Kanno','MID','KSA','wk'),
(gen_random_uuid()::text,'Ali Al-Bulaihi','VER','KSA','wk'),
(gen_random_uuid()::text,'Hassan Al-Tambakti','VER','KSA','wk'),
(gen_random_uuid()::text,'Saud Abdulhamid','VER','KSA','wk'),
(gen_random_uuid()::text,'Abdullah Madu','VER','KSA','wk'),
(gen_random_uuid()::text,'Mohammed Al-Owais','DOE','KSA','wk'),
(gen_random_uuid()::text,'Nawaf Al-Aqidi','DOE','KSA','wk'),

-- Irak (IRQ)
(gen_random_uuid()::text,'Aymen Hussein','AAN','IRQ','wk'),
(gen_random_uuid()::text,'Mohanad Ali','AAN','IRQ','wk'),
(gen_random_uuid()::text,'Alaa Abbas','AAN','IRQ','wk'),
(gen_random_uuid()::text,'Ahmed Yasin','MID','IRQ','wk'),
(gen_random_uuid()::text,'Bashar Resan','MID','IRQ','wk'),
(gen_random_uuid()::text,'Ali Adnan','MID','IRQ','wk'),
(gen_random_uuid()::text,'Amjad Attwan','MID','IRQ','wk'),
(gen_random_uuid()::text,'Hussein Ali','VER','IRQ','wk'),
(gen_random_uuid()::text,'Rebin Sulaka','VER','IRQ','wk'),
(gen_random_uuid()::text,'Saad Natiq','VER','IRQ','wk'),
(gen_random_uuid()::text,'Mustafa Nadhim','VER','IRQ','wk'),
(gen_random_uuid()::text,'Jalal Hassan','DOE','IRQ','wk'),
(gen_random_uuid()::text,'Mohammed Hameed','DOE','IRQ','wk'),

-- Noorwegen (NOR)
(gen_random_uuid()::text,'Erling Haaland','AAN','NOR','wk'),
(gen_random_uuid()::text,'Alexander Sørloth','AAN','NOR','wk'),
(gen_random_uuid()::text,'Mohamed Elyounoussi','AAN','NOR','wk'),
(gen_random_uuid()::text,'Ola Brynhildsen','AAN','NOR','wk'),
(gen_random_uuid()::text,'Martin Ødegaard','MID','NOR','wk'),
(gen_random_uuid()::text,'Sander Berge','MID','NOR','wk'),
(gen_random_uuid()::text,'Morten Thorsby','MID','NOR','wk'),
(gen_random_uuid()::text,'Fredrik Aursnes','MID','NOR','wk'),
(gen_random_uuid()::text,'Patrick Berg','MID','NOR','wk'),
(gen_random_uuid()::text,'Leo Østigård','VER','NOR','wk'),
(gen_random_uuid()::text,'Andreas Hanche-Olsen','VER','NOR','wk'),
(gen_random_uuid()::text,'Birger Meling','VER','NOR','wk'),
(gen_random_uuid()::text,'Kristoffer Ajer','VER','NOR','wk'),
(gen_random_uuid()::text,'Ørjan Nyland','DOE','NOR','wk'),
(gen_random_uuid()::text,'Jorgen Strand Larsen','AAN','NOR','wk'),

-- Oostenrijk (AUT)
(gen_random_uuid()::text,'Marko Arnautovic','AAN','AUT','wk'),
(gen_random_uuid()::text,'Michael Gregoritsch','AAN','AUT','wk'),
(gen_random_uuid()::text,'Christoph Baumgartner','AAN','AUT','wk'),
(gen_random_uuid()::text,'Patrick Wimmer','AAN','AUT','wk'),
(gen_random_uuid()::text,'Marcel Sabitzer','MID','AUT','wk'),
(gen_random_uuid()::text,'Florian Grillitsch','MID','AUT','wk'),
(gen_random_uuid()::text,'Nicolas Seiwald','MID','AUT','wk'),
(gen_random_uuid()::text,'Konrad Laimer','MID','AUT','wk'),
(gen_random_uuid()::text,'David Alaba','VER','AUT','wk'),
(gen_random_uuid()::text,'Stefan Posch','VER','AUT','wk'),
(gen_random_uuid()::text,'Philipp Mwene','VER','AUT','wk'),
(gen_random_uuid()::text,'Maximilian Wöber','VER','AUT','wk'),
(gen_random_uuid()::text,'Kevin Danso','VER','AUT','wk'),
(gen_random_uuid()::text,'Patrick Pentz','DOE','AUT','wk'),
(gen_random_uuid()::text,'Alexander Schlager','DOE','AUT','wk'),

-- Jordanië (JOR)
(gen_random_uuid()::text,'Yazan Al-Naimat','AAN','JOR','wk'),
(gen_random_uuid()::text,'Baha Faisal','AAN','JOR','wk'),
(gen_random_uuid()::text,'Hamza Al-Dardour','AAN','JOR','wk'),
(gen_random_uuid()::text,'Mousa Al-Taamari','AAN','JOR','wk'),
(gen_random_uuid()::text,'Mahmoud Almardi','MID','JOR','wk'),
(gen_random_uuid()::text,'Nizar Al-Rawi','MID','JOR','wk'),
(gen_random_uuid()::text,'Musa Al-Taamari','MID','JOR','wk'),
(gen_random_uuid()::text,'Saleh Hardain','MID','JOR','wk'),
(gen_random_uuid()::text,'Abdallah Nasib','VER','JOR','wk'),
(gen_random_uuid()::text,'Yazeed Abo Laila','VER','JOR','wk'),
(gen_random_uuid()::text,'Badr Al-Momani','VER','JOR','wk'),
(gen_random_uuid()::text,'Ahmad Hejazi','VER','JOR','wk'),
(gen_random_uuid()::text,'Amer Shafi','DOE','JOR','wk'),
(gen_random_uuid()::text,'Musa Eid','DOE','JOR','wk'),

-- Congo DR (COD)
(gen_random_uuid()::text,'Cédric Bakambu','AAN','COD','wk'),
(gen_random_uuid()::text,'Yannick Bolasie','AAN','COD','wk'),
(gen_random_uuid()::text,'Dieumerci Mbokani','AAN','COD','wk'),
(gen_random_uuid()::text,'Jonathan Bolingi','AAN','COD','wk'),
(gen_random_uuid()::text,'Chancel Mbemba','VER','COD','wk'),
(gen_random_uuid()::text,'Youssouf Mulumbu','MID','COD','wk'),
(gen_random_uuid()::text,'Merveille Bongonda','AAN','COD','wk'),
(gen_random_uuid()::text,'Arthur Masuaku','VER','COD','wk'),
(gen_random_uuid()::text,'Marcel Tisserand','VER','COD','wk'),
(gen_random_uuid()::text,'Hervé Kage','MID','COD','wk'),
(gen_random_uuid()::text,'Théo Bongonda','MID','COD','wk'),
(gen_random_uuid()::text,'Christian Luyindama','VER','COD','wk'),
(gen_random_uuid()::text,'Joël Kiassumbua','DOE','COD','wk'),
(gen_random_uuid()::text,'Lionel Mpasi','DOE','COD','wk'),

-- Oezbekistan (UZB)
(gen_random_uuid()::text,'Eldor Shomurodov','AAN','UZB','wk'),
(gen_random_uuid()::text,'Jasur Yaxshiboev','AAN','UZB','wk'),
(gen_random_uuid()::text,'Sherzod Nasimov','AAN','UZB','wk'),
(gen_random_uuid()::text,'Otabek Shukurov','MID','UZB','wk'),
(gen_random_uuid()::text,'Jaloliddin Masharipov','MID','UZB','wk'),
(gen_random_uuid()::text,'Abbosbek Fayzullaev','MID','UZB','wk'),
(gen_random_uuid()::text,'Bobur Abdixoliqov','MID','UZB','wk'),
(gen_random_uuid()::text,'Dostonbek Khamdamov','VER','UZB','wk'),
(gen_random_uuid()::text,'Shukurjon Madaminov','VER','UZB','wk'),
(gen_random_uuid()::text,'Sanjar Tursunov','VER','UZB','wk'),
(gen_random_uuid()::text,'Islom Tukhtahujaev','VER','UZB','wk'),
(gen_random_uuid()::text,'Botir Yusupov','DOE','UZB','wk'),
(gen_random_uuid()::text,'Sarbon Yokubov','DOE','UZB','wk'),

-- Ghana (GHA)
(gen_random_uuid()::text,'Jordan Ayew','AAN','GHA','wk'),
(gen_random_uuid()::text,'André Ayew','AAN','GHA','wk'),
(gen_random_uuid()::text,'Inaki Williams','AAN','GHA','wk'),
(gen_random_uuid()::text,'Antoine Semenyo','AAN','GHA','wk'),
(gen_random_uuid()::text,'Tariq Lamptey','MID','GHA','wk'),
(gen_random_uuid()::text,'Thomas Partey','MID','GHA','wk'),
(gen_random_uuid()::text,'Mohammed Kudus','MID','GHA','wk'),
(gen_random_uuid()::text,'Daniel-Kofi Kyereh','MID','GHA','wk'),
(gen_random_uuid()::text,'Baba Rahman','VER','GHA','wk'),
(gen_random_uuid()::text,'Daniel Amartey','VER','GHA','wk'),
(gen_random_uuid()::text,'Alexander Djiku','VER','GHA','wk'),
(gen_random_uuid()::text,'Andy Yiadom','VER','GHA','wk'),
(gen_random_uuid()::text,'Lawrence Ati-Zigi','DOE','GHA','wk'),
(gen_random_uuid()::text,'Joe Wollacott','DOE','GHA','wk'),

-- Panama (PAN)
(gen_random_uuid()::text,'Rolando Blackburn','AAN','PAN','wk'),
(gen_random_uuid()::text,'Ismael Díaz','AAN','PAN','wk'),
(gen_random_uuid()::text,'Cecilio Waterman','AAN','PAN','wk'),
(gen_random_uuid()::text,'Abdiel Arroyo','AAN','PAN','wk'),
(gen_random_uuid()::text,'Anibal Godoy','MID','PAN','wk'),
(gen_random_uuid()::text,'Adalberto Carrasquilla','MID','PAN','wk'),
(gen_random_uuid()::text,'Aníbal Godoy','MID','PAN','wk'),
(gen_random_uuid()::text,'Édgar Bárcenas','MID','PAN','wk'),
(gen_random_uuid()::text,'Fidel Escobar','VER','PAN','wk'),
(gen_random_uuid()::text,'Éric Davis','VER','PAN','wk'),
(gen_random_uuid()::text,'Harold Cummings','VER','PAN','wk'),
(gen_random_uuid()::text,'Roderick Miller','VER','PAN','wk'),
(gen_random_uuid()::text,'Luis Mejía','DOE','PAN','wk'),
(gen_random_uuid()::text,'Orlando Mosquera','DOE','PAN','wk'),

-- Algerije (ALG) - ook in WK poule J
(gen_random_uuid()::text,'Riyad Mahrez','AAN','ALG','wk'),
(gen_random_uuid()::text,'Amine Gouiri','AAN','ALG','wk'),
(gen_random_uuid()::text,'Mohamed Amine Amoura','AAN','ALG','wk'),
(gen_random_uuid()::text,'Anis Hadj Moussa','AAN','ALG','wk'),
(gen_random_uuid()::text,'Nadhir Ben Bouali','AAN','ALG','wk'),
(gen_random_uuid()::text,'Farès Chaïbi','MID','ALG','wk'),
(gen_random_uuid()::text,'Hicham Boudaoui','MID','ALG','wk'),
(gen_random_uuid()::text,'Houssem Aouar','MID','ALG','wk'),
(gen_random_uuid()::text,'Ramiz Zerrouki','MID','ALG','wk'),
(gen_random_uuid()::text,'Ismael Bennacer','MID','ALG','wk'),
(gen_random_uuid()::text,'Ibrahim Maza','MID','ALG','wk'),
(gen_random_uuid()::text,'Ramy Bensebaini','VER','ALG','wk'),
(gen_random_uuid()::text,'Aïssa Mandi','VER','ALG','wk'),
(gen_random_uuid()::text,'Rayan Aït-Nouri','VER','ALG','wk'),
(gen_random_uuid()::text,'Jaouen Hadjam','VER','ALG','wk'),
(gen_random_uuid()::text,'Rafik Belghali','VER','ALG','wk'),
(gen_random_uuid()::text,'Luca Zidane','DOE','ALG','wk'),
(gen_random_uuid()::text,'Oussama Benbot','DOE','ALG','wk')

ON CONFLICT (naam, team, soort) DO NOTHING;
