-- Verwijder en herinsert alle teams waarvoor een bevestigde lijst bestaat
-- Gebruik uitsluitend de bevestigde namen — geen voornamen verzinnen

DELETE FROM "Speler" WHERE soort = 'wk' AND team IN (
  'ENG','ESP','FRA','GER','BEL','IRN','NOR','IRQ',
  'COD','GHA','HAI','JOR','CZE','ZAF','TUN','CRO','UZB'
);

-- Engeland (ENG)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Pickford', 'ENG', 'DOE', 'wk'),
(gen_random_uuid(), 'D.Henderson', 'ENG', 'DOE', 'wk'),
(gen_random_uuid(), 'Trafford', 'ENG', 'DOE', 'wk'),
(gen_random_uuid(), 'Konsa', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Stones', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Guéhi', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Livramento', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Burn', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'R.James', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Spence', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Quansah', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'O''Reilly', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Rice', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Anderson', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Bellingham', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'J.Henderson', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Mainoo', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Rogers', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Saka', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Kane', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Rashford', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Gordon', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Watkins', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Madueke', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Eze', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Toney', 'ENG', 'AAN', 'wk');

-- Spanje (ESP)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Simón', 'ESP', 'DOE', 'wk'),
(gen_random_uuid(), 'Raya', 'ESP', 'DOE', 'wk'),
(gen_random_uuid(), 'J.Garcia', 'ESP', 'DOE', 'wk'),
(gen_random_uuid(), 'Cucurella', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Grimaldo', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Cubarsí', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Laporte', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Pubill', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'E.García', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Llorente', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Porro', 'ESP', 'VER', 'wk'),
(gen_random_uuid(), 'Pedri', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Fabián', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Zubimendi', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Gavi', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Rodri', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Baena', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Merino', 'ESP', 'MID', 'wk'),
(gen_random_uuid(), 'Oyarzabal', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'D.Olmo', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Nico Williams', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Pino', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'F.Torres', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Borja Iglesias', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Víctor Muñoz', 'ESP', 'AAN', 'wk'),
(gen_random_uuid(), 'Lamine Yamal', 'ESP', 'AAN', 'wk');

-- Frankrijk (FRA)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Samba', 'FRA', 'DOE', 'wk'),
(gen_random_uuid(), 'Maignan', 'FRA', 'DOE', 'wk'),
(gen_random_uuid(), 'Risser', 'FRA', 'DOE', 'wk'),
(gen_random_uuid(), 'Gusto', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Digne', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Upamecano', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Koundé', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'I.Konaté', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Saliba', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'T.Hernandez', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'L.Hernandez', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Lacroix', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Kanté', 'FRA', 'MID', 'wk'),
(gen_random_uuid(), 'Rabiot', 'FRA', 'MID', 'wk'),
(gen_random_uuid(), 'Tchouaméni', 'FRA', 'MID', 'wk'),
(gen_random_uuid(), 'Koné', 'FRA', 'MID', 'wk'),
(gen_random_uuid(), 'Zaïre-Emery', 'FRA', 'MID', 'wk'),
(gen_random_uuid(), 'Mbappé', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Dembélé', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Thuram', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Barcola', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Olise', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Akliouche', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Doué', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Cherki', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Mateta', 'FRA', 'AAN', 'wk');

-- Duitsland (GER)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Baumann', 'GER', 'DOE', 'wk'),
(gen_random_uuid(), 'Neuer', 'GER', 'DOE', 'wk'),
(gen_random_uuid(), 'Nübel', 'GER', 'DOE', 'wk'),
(gen_random_uuid(), 'Kimmich', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Schlotterbeck', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Raum', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Tah', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Anton', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Rüdiger', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'N.Brown', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Thiaw', 'GER', 'VER', 'wk'),
(gen_random_uuid(), 'Musiala', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Wirtz', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Stiller', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Pavlovic', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Goretzka', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Sané', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Nmecha', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Amiri', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Gross', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Ouédraogo', 'GER', 'MID', 'wk'),
(gen_random_uuid(), 'Havertz', 'GER', 'AAN', 'wk'),
(gen_random_uuid(), 'Undav', 'GER', 'AAN', 'wk'),
(gen_random_uuid(), 'Leweling', 'GER', 'AAN', 'wk'),
(gen_random_uuid(), 'Woltemade', 'GER', 'AAN', 'wk'),
(gen_random_uuid(), 'Beier', 'GER', 'AAN', 'wk');

-- België (BEL)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Courtois', 'BEL', 'DOE', 'wk'),
(gen_random_uuid(), 'Lammens', 'BEL', 'DOE', 'wk'),
(gen_random_uuid(), 'Penders', 'BEL', 'DOE', 'wk'),
(gen_random_uuid(), 'Castagne', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Debast', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'De Cuyper', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'K.De Winter', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Mechele', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Meunier', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Ngoy', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Seys', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'Theate', 'BEL', 'VER', 'wk'),
(gen_random_uuid(), 'De Bruyne', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Onana', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Raskin', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Tielemans', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Vanaken', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'Witsel', 'BEL', 'MID', 'wk'),
(gen_random_uuid(), 'De Ketelaere', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Doku', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Fernandez-Pardo', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Lukaku', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Lukebakio', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Moreira', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Saelemaekers', 'BEL', 'AAN', 'wk'),
(gen_random_uuid(), 'Trossard', 'BEL', 'AAN', 'wk');

-- Iran (IRN)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Beiranvand', 'IRN', 'DOE', 'wk'),
(gen_random_uuid(), 'Hosseini', 'IRN', 'DOE', 'wk'),
(gen_random_uuid(), 'Niazmand', 'IRN', 'DOE', 'wk'),
(gen_random_uuid(), 'Eiri', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Hajsafi', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Hardani', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Kanaani', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Khalilzadeh', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Mohammadi', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Nemati', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Rezaeian', 'IRN', 'VER', 'wk'),
(gen_random_uuid(), 'Cheshmi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Ezatolahi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Ghaedi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Ghoddos', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Ghorbani', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Jahanbakhsh', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Mohebi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Razzaghinia', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Torabi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Yousefi', 'IRN', 'MID', 'wk'),
(gen_random_uuid(), 'Alipour', 'IRN', 'AAN', 'wk'),
(gen_random_uuid(), 'Dargahi', 'IRN', 'AAN', 'wk'),
(gen_random_uuid(), 'Hosseinzadeh', 'IRN', 'AAN', 'wk'),
(gen_random_uuid(), 'Taremi', 'IRN', 'AAN', 'wk'),
(gen_random_uuid(), 'Moghanlou', 'IRN', 'AAN', 'wk');

-- Noorwegen (NOR)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Nyland', 'NOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Selvik', 'NOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Tangvik', 'NOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Ryerson', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'M.H.Pedersen', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Wolfe', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Bjørkan', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Ajer', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Heggem', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Østigård', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Langas', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Falchener', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Ødegaard', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Berge', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Aursnes', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'P.Berg', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Thorstvedt', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Thorsby', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Aasgaard', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Haaland', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Sørloth', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Strand Larsen', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Nusa', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Bobb', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Schjelderup', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Hauge', 'NOR', 'AAN', 'wk');

-- Irak (IRQ)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Talib', 'IRQ', 'DOE', 'wk'),
(gen_random_uuid(), 'J.Hassan', 'IRQ', 'DOE', 'wk'),
(gen_random_uuid(), 'A.Basil', 'IRQ', 'DOE', 'wk'),
(gen_random_uuid(), 'H.Ali', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Younis', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Yahya', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Saadoon', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Tahseen', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Sulaka', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Hashim', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Doski', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Ismail', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Putros', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Al-Ammari', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Yakob', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Iqbal', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Sher', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Bayesh', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Qasem', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Amyn', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Farji', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'A.Jassim', 'IRQ', 'AAN', 'wk'),
(gen_random_uuid(), 'Al-Hamadi', 'IRQ', 'AAN', 'wk'),
(gen_random_uuid(), 'A.Yousef', 'IRQ', 'AAN', 'wk'),
(gen_random_uuid(), 'A.Hussein', 'IRQ', 'AAN', 'wk'),
(gen_random_uuid(), 'Mohanad Ali', 'IRQ', 'AAN', 'wk');

-- DR Congo (COD)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Epolo', 'COD', 'DOE', 'wk'),
(gen_random_uuid(), 'Fayulu', 'COD', 'DOE', 'wk'),
(gen_random_uuid(), 'Mpasi', 'COD', 'DOE', 'wk'),
(gen_random_uuid(), 'Batubinsika', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'G.Kalulu', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Kapuadi', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'J.Kayembe', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Masuaku', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Mbemba', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Tuanzebe', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Wan-Bissaka', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Bongonda', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Cipenga', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Elia', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Kakuta', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'E.Kayembe', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Mbuku', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Moutoussamy', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Mukau', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Pickel', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Sadiki', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Tshibola', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Bakambu', 'COD', 'AAN', 'wk'),
(gen_random_uuid(), 'Banza', 'COD', 'AAN', 'wk'),
(gen_random_uuid(), 'Mayele', 'COD', 'AAN', 'wk'),
(gen_random_uuid(), 'Wissa', 'COD', 'AAN', 'wk');

-- Ghana (GHA)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Ati-Zigi', 'GHA', 'DOE', 'wk'),
(gen_random_uuid(), 'Anang', 'GHA', 'DOE', 'wk'),
(gen_random_uuid(), 'B.Asare', 'GHA', 'DOE', 'wk'),
(gen_random_uuid(), 'Seidu', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Adjetey', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Mumin', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'G.Mensah', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'A.R.Baba', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Opoku', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Peprah Oppong', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Luckassen', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Senaya', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Yirenkyi', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Partey', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Sibo', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Owusu', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Boakye', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Semenyo', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Fatawu', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'J.Ayew', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Thomas-Asante', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Bonsu Baah', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'I.Williams', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Sulemana', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Nuamah', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Adu', 'GHA', 'AAN', 'wk');

-- Haïti (HAI)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Placide', 'HAI', 'DOE', 'wk'),
(gen_random_uuid(), 'Arcus', 'HAI', 'DOE', 'wk'),
(gen_random_uuid(), 'Thermoncy', 'HAI', 'DOE', 'wk'),
(gen_random_uuid(), 'Ade', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Delcroix', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Sainte', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Etienne Jr', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Deedson', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Alexandre Pierre', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Duke Lacroix', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Casimir', 'HAI', 'VER', 'wk'),
(gen_random_uuid(), 'Bellegarde', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'L.Pierre', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Providence', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Joseph', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Jean-Jacques', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'J.K.Duverne', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Duverger', 'HAI', 'MID', 'wk'),
(gen_random_uuid(), 'Isidor', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Fortune', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Pierrot', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Paugain', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'D.Simon', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'W.Pierre', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Experience', 'HAI', 'AAN', 'wk'),
(gen_random_uuid(), 'Nazon', 'HAI', 'AAN', 'wk');

-- Jordanië (JOR)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Abulaila', 'JOR', 'DOE', 'wk'),
(gen_random_uuid(), 'A.Al-Fakhouri', 'JOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Bani Attiah', 'JOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Nasib', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Haddad', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Al-Rosan', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Obaid', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Al-Arab', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Abualnadi', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Abu Dahab', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Banawi', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'M.Abu Taha', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Abu Hasheesh', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Al-Rawabdeh', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Al-Rashdan', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Saadeh', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Ayed', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Al-Mardi', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Jamous', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Al-Dawoud', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Al-Tamari', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'O.Al-Fakhouri', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Abu Zrayq', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Azaizeh', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Sabra', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Olwan', 'JOR', 'AAN', 'wk');

-- Tsjechië (CZE)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Horníček', 'CZE', 'DOE', 'wk'),
(gen_random_uuid(), 'Kovář', 'CZE', 'DOE', 'wk'),
(gen_random_uuid(), 'Staněk', 'CZE', 'DOE', 'wk'),
(gen_random_uuid(), 'Coufal', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Doudera', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Holeš', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Hranáč', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Chaloupek', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Jurásek', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Krejčí', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Zelený', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Zimá', 'CZE', 'VER', 'wk'),
(gen_random_uuid(), 'Červ', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Darida', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Provod', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Sadílek', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Sochurek', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Sojka', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Souček', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Šulc', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Višinský', 'CZE', 'MID', 'wk'),
(gen_random_uuid(), 'Hložek', 'CZE', 'AAN', 'wk'),
(gen_random_uuid(), 'Chorý', 'CZE', 'AAN', 'wk'),
(gen_random_uuid(), 'Chytil', 'CZE', 'AAN', 'wk'),
(gen_random_uuid(), 'Kuchta', 'CZE', 'AAN', 'wk'),
(gen_random_uuid(), 'Schick', 'CZE', 'AAN', 'wk');

-- Zuid-Afrika (ZAF)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Williams', 'ZAF', 'DOE', 'wk'),
(gen_random_uuid(), 'Goss', 'ZAF', 'DOE', 'wk'),
(gen_random_uuid(), 'Chaine', 'ZAF', 'DOE', 'wk'),
(gen_random_uuid(), 'Mudau', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Sibisi', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Okon', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Ndamane', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Modiba', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Kabini', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Matuludi', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Makhanya', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Sebelebele', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Cross', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Mbokazi', 'ZAF', 'VER', 'wk'),
(gen_random_uuid(), 'Mokoena', 'ZAF', 'MID', 'wk'),
(gen_random_uuid(), 'Mbatha', 'ZAF', 'MID', 'wk'),
(gen_random_uuid(), 'Sithole', 'ZAF', 'MID', 'wk'),
(gen_random_uuid(), 'Adams', 'ZAF', 'MID', 'wk'),
(gen_random_uuid(), 'Appollis', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Rayners', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Moremi', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Mofokeng', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Makgopa', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Zwane', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Foster', 'ZAF', 'AAN', 'wk'),
(gen_random_uuid(), 'Maseko', 'ZAF', 'AAN', 'wk');

-- Tunesië (TUN)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Ben Hessen', 'TUN', 'DOE', 'wk'),
(gen_random_uuid(), 'Chamakh', 'TUN', 'DOE', 'wk'),
(gen_random_uuid(), 'Dahmen', 'TUN', 'DOE', 'wk'),
(gen_random_uuid(), 'Abdi', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Arous', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Ben Hamida', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Bronn', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Chikhaoui', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Neffati', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Rekik', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Talbi', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Valery', 'TUN', 'VER', 'wk'),
(gen_random_uuid(), 'Ben Ouanes', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'A.Ben Slimane', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Gharbi', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Khedira', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Hadj Mahmoud', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Mejbri', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Skhiri', 'TUN', 'MID', 'wk'),
(gen_random_uuid(), 'Achouri', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Ayari', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Chaouat', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Elloumi', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Mastouri', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Saad', 'TUN', 'AAN', 'wk'),
(gen_random_uuid(), 'Tounekti', 'TUN', 'AAN', 'wk');

-- Kroatië (CRO)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Livaković', 'CRO', 'DOE', 'wk'),
(gen_random_uuid(), 'Kotarski', 'CRO', 'DOE', 'wk'),
(gen_random_uuid(), 'Pandur', 'CRO', 'DOE', 'wk'),
(gen_random_uuid(), 'Gvardiol', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Ćaleta-Car', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Šutalo', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Stanišić', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Pongračić', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Erlić', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Vušković', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Modrić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Kovačić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'M.Pašalić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Vlašić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'L.Sučić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Baturina', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Jakić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'P.Sučić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Moro', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Fruk', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Perišić', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Kramarić', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Budimir', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Marco Pašalić', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Musa', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Matanović', 'CRO', 'AAN', 'wk');

-- Oezbekistan (UZB)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Yusupov', 'UZB', 'DOE', 'wk'),
(gen_random_uuid(), 'Nematov', 'UZB', 'DOE', 'wk'),
(gen_random_uuid(), 'Ergashev', 'UZB', 'DOE', 'wk'),
(gen_random_uuid(), 'Khusanov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Alijonov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Sayfiev', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Ashurmatov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Nasrullaev', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Eshmurodov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Abdullaev', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Karimov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Ulmasaliev', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Urozov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Mozgovoy', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Shukurov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Iskanderov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Hamrobekov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Masharipov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Urunov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Khamdamov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Ganiev', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Fayzullaev', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Esanov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Shomurodov', 'UZB', 'AAN', 'wk'),
(gen_random_uuid(), 'Amonov', 'UZB', 'AAN', 'wk'),
(gen_random_uuid(), 'Sergeev', 'UZB', 'AAN', 'wk');
