-- ============================================================
-- GROEP I: FRA, SEN, IRQ, NOR
-- ============================================================

-- Frankrijk (FRA)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Mike Maignan', 'FRA', 'DOE', 'wk'),
(gen_random_uuid(), 'Brice Samba', 'FRA', 'DOE', 'wk'),
(gen_random_uuid(), 'Gautier Larsonneur', 'FRA', 'DOE', 'wk'),
(gen_random_uuid(), 'Jules Koundé', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'William Saliba', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Dayot Upamecano', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Ibrahima Konaté', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Théo Hernandez', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Lucas Hernandez', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Jonathan Clauss', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Ferland Mendy', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'Benoît Badiashile', 'FRA', 'VER', 'wk'),
(gen_random_uuid(), 'N''Golo Kanté', 'FRA', 'MID', 'wk'),
(gen_random_uuid(), 'Aurélien Tchouaméni', 'FRA', 'MID', 'wk'),
(gen_random_uuid(), 'Warren Zaïre-Emery', 'FRA', 'MID', 'wk'),
(gen_random_uuid(), 'Manu Koné', 'FRA', 'MID', 'wk'),
(gen_random_uuid(), 'Adrien Rabiot', 'FRA', 'MID', 'wk'),
(gen_random_uuid(), 'Kylian Mbappé', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Ousmane Dembélé', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Marcus Thuram', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Bradley Barcola', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Michael Olise', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Mathys Tel', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Desire Doué', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Rayan Cherki', 'FRA', 'AAN', 'wk'),
(gen_random_uuid(), 'Jean-Philippe Mateta', 'FRA', 'AAN', 'wk');

-- Senegal (SEN)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Edouard Mendy', 'SEN', 'DOE', 'wk'),
(gen_random_uuid(), 'Mory Diaw', 'SEN', 'DOE', 'wk'),
(gen_random_uuid(), 'Yehvann Diouf', 'SEN', 'DOE', 'wk'),
(gen_random_uuid(), 'Kalidou Koulibaly', 'SEN', 'VER', 'wk'),
(gen_random_uuid(), 'Abdoulaye Seck', 'SEN', 'VER', 'wk'),
(gen_random_uuid(), 'Moussa Niakhate', 'SEN', 'VER', 'wk'),
(gen_random_uuid(), 'Ismail Jakobs', 'SEN', 'VER', 'wk'),
(gen_random_uuid(), 'Mamadou Sarr', 'SEN', 'VER', 'wk'),
(gen_random_uuid(), 'Antoine Mendy', 'SEN', 'VER', 'wk'),
(gen_random_uuid(), 'Ilay Camara', 'SEN', 'VER', 'wk'),
(gen_random_uuid(), 'El Hadji Malick Diouf', 'SEN', 'VER', 'wk'),
(gen_random_uuid(), 'Idrissa Gana Gueye', 'SEN', 'MID', 'wk'),
(gen_random_uuid(), 'Pape Matar Sarr', 'SEN', 'MID', 'wk'),
(gen_random_uuid(), 'Pape Gueye', 'SEN', 'MID', 'wk'),
(gen_random_uuid(), 'Lamine Camara', 'SEN', 'MID', 'wk'),
(gen_random_uuid(), 'Habib Diarra', 'SEN', 'MID', 'wk'),
(gen_random_uuid(), 'Pathe Ciss', 'SEN', 'MID', 'wk'),
(gen_random_uuid(), 'Nampalys Mendy', 'SEN', 'MID', 'wk'),
(gen_random_uuid(), 'Sadio Mané', 'SEN', 'AAN', 'wk'),
(gen_random_uuid(), 'Ismaila Sarr', 'SEN', 'AAN', 'wk'),
(gen_random_uuid(), 'Iliman Ndiaye', 'SEN', 'AAN', 'wk'),
(gen_random_uuid(), 'Nicolas Jackson', 'SEN', 'AAN', 'wk'),
(gen_random_uuid(), 'Bamba Dieng', 'SEN', 'AAN', 'wk'),
(gen_random_uuid(), 'Cherif Ndiaye', 'SEN', 'AAN', 'wk'),
(gen_random_uuid(), 'Assane Diao', 'SEN', 'AAN', 'wk'),
(gen_random_uuid(), 'Souleymane Aw', 'SEN', 'AAN', 'wk');

-- Irak (IRQ)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Jalal Hassan', 'IRQ', 'DOE', 'wk'),
(gen_random_uuid(), 'Dhurgham Ismail', 'IRQ', 'DOE', 'wk'),
(gen_random_uuid(), 'Ahmed Basil', 'IRQ', 'DOE', 'wk'),
(gen_random_uuid(), 'Ali Adnan', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Rebin Sulaka', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Hussein Ali', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Amjad Atwan', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Alaa Abbas', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Mustafa Tahsin', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Ahmad Hamad', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Sherko Karimi', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Saad Natiq', 'IRQ', 'VER', 'wk'),
(gen_random_uuid(), 'Yaser Kasim', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Bashar Resan', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Humam Tariq', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Amyn Yahya', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Ahmad Al-Azzawi', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Ali Faez', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Ibrahim Bayesh', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Safaa Hadi', 'IRQ', 'MID', 'wk'),
(gen_random_uuid(), 'Aymen Hussein', 'IRQ', 'AAN', 'wk'),
(gen_random_uuid(), 'Mohanad Ali', 'IRQ', 'AAN', 'wk'),
(gen_random_uuid(), 'Ahmed Al-Hamadi', 'IRQ', 'AAN', 'wk'),
(gen_random_uuid(), 'Ahmad Jassim', 'IRQ', 'AAN', 'wk'),
(gen_random_uuid(), 'Ali Jasim', 'IRQ', 'AAN', 'wk'),
(gen_random_uuid(), 'Doğukan Sinik', 'IRQ', 'AAN', 'wk');

-- Noorwegen (NOR)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Ørjan Nyland', 'NOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Markus Selvik', 'NOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Marcus Tangvik', 'NOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Julian Ryerson', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Marcus Holmgren Pedersen', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Birger Meling', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'David Bjørkan', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Kristoffer Ajer', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Leo Østigård', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Isak Langas', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Andreas Hanche-Olsen', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Stian Gregersen', 'NOR', 'VER', 'wk'),
(gen_random_uuid(), 'Martin Ødegaard', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Sander Berge', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Fredrik Aursnes', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Kristian Thorstvedt', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Morten Thorsby', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Tobias Aasgaard', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Petter Berg', 'NOR', 'MID', 'wk'),
(gen_random_uuid(), 'Erling Haaland', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Alexander Sørloth', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Jørgen Strand Larsen', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Antonio Nusa', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Oscar Bobb', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Gustav Isaksen', 'NOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Noah Solskjaer', 'NOR', 'AAN', 'wk');

-- ============================================================
-- GROEP J: ARG, ALG, AUT, JOR
-- ============================================================

-- Argentinië (ARG)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Emiliano Martínez', 'ARG', 'DOE', 'wk'),
(gen_random_uuid(), 'Juan Musso', 'ARG', 'DOE', 'wk'),
(gen_random_uuid(), 'Gerónimo Rulli', 'ARG', 'DOE', 'wk'),
(gen_random_uuid(), 'Cristian Romero', 'ARG', 'VER', 'wk'),
(gen_random_uuid(), 'Lisandro Martínez', 'ARG', 'VER', 'wk'),
(gen_random_uuid(), 'Nicolás Otamendi', 'ARG', 'VER', 'wk'),
(gen_random_uuid(), 'Leonardo Balerdi', 'ARG', 'VER', 'wk'),
(gen_random_uuid(), 'Nahuel Molina', 'ARG', 'VER', 'wk'),
(gen_random_uuid(), 'Nicolás Tagliafico', 'ARG', 'VER', 'wk'),
(gen_random_uuid(), 'Gonzalo Montiel', 'ARG', 'VER', 'wk'),
(gen_random_uuid(), 'Facundo Medina', 'ARG', 'VER', 'wk'),
(gen_random_uuid(), 'Alexis Mac Allister', 'ARG', 'MID', 'wk'),
(gen_random_uuid(), 'Enzo Fernández', 'ARG', 'MID', 'wk'),
(gen_random_uuid(), 'Rodrigo De Paul', 'ARG', 'MID', 'wk'),
(gen_random_uuid(), 'Exequiel Palacios', 'ARG', 'MID', 'wk'),
(gen_random_uuid(), 'Giovani Lo Celso', 'ARG', 'MID', 'wk'),
(gen_random_uuid(), 'Leandro Paredes', 'ARG', 'MID', 'wk'),
(gen_random_uuid(), 'Valentín Barco', 'ARG', 'MID', 'wk'),
(gen_random_uuid(), 'Lionel Messi', 'ARG', 'AAN', 'wk'),
(gen_random_uuid(), 'Lautaro Martínez', 'ARG', 'AAN', 'wk'),
(gen_random_uuid(), 'Julián Álvarez', 'ARG', 'AAN', 'wk'),
(gen_random_uuid(), 'Thiago Almada', 'ARG', 'AAN', 'wk'),
(gen_random_uuid(), 'Nicolás González', 'ARG', 'AAN', 'wk'),
(gen_random_uuid(), 'Nico Paz', 'ARG', 'AAN', 'wk'),
(gen_random_uuid(), 'Giuliano Simeone', 'ARG', 'AAN', 'wk'),
(gen_random_uuid(), 'Alejandro Garnacho', 'ARG', 'AAN', 'wk');

-- Algerije (ALG)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Rais M''Bolhi', 'ALG', 'DOE', 'wk'),
(gen_random_uuid(), 'Oussama Benbot', 'ALG', 'DOE', 'wk'),
(gen_random_uuid(), 'Luca Zidane', 'ALG', 'DOE', 'wk'),
(gen_random_uuid(), 'Ramy Bensebaïni', 'ALG', 'VER', 'wk'),
(gen_random_uuid(), 'Aïssa Mandi', 'ALG', 'VER', 'wk'),
(gen_random_uuid(), 'Rayan Aït-Nouri', 'ALG', 'VER', 'wk'),
(gen_random_uuid(), 'Jaouen Hadjam', 'ALG', 'VER', 'wk'),
(gen_random_uuid(), 'Rafik Belghali', 'ALG', 'VER', 'wk'),
(gen_random_uuid(), 'Samir Chergui', 'ALG', 'VER', 'wk'),
(gen_random_uuid(), 'Zinedine Belaïd', 'ALG', 'VER', 'wk'),
(gen_random_uuid(), 'Mohamed Amine Tougaï', 'ALG', 'VER', 'wk'),
(gen_random_uuid(), 'Achraf Abada', 'ALG', 'VER', 'wk'),
(gen_random_uuid(), 'Houssem Aouar', 'ALG', 'MID', 'wk'),
(gen_random_uuid(), 'Farès Chaïbi', 'ALG', 'MID', 'wk'),
(gen_random_uuid(), 'Ibrahim Maza', 'ALG', 'MID', 'wk'),
(gen_random_uuid(), 'Hicham Boudaoui', 'ALG', 'MID', 'wk'),
(gen_random_uuid(), 'Nabil Bentaleb', 'ALG', 'MID', 'wk'),
(gen_random_uuid(), 'Ramiz Zerrouki', 'ALG', 'MID', 'wk'),
(gen_random_uuid(), 'Yacine Titraoui', 'ALG', 'MID', 'wk'),
(gen_random_uuid(), 'Riyad Mahrez', 'ALG', 'AAN', 'wk'),
(gen_random_uuid(), 'Mohamed Amine Amoura', 'ALG', 'AAN', 'wk'),
(gen_random_uuid(), 'Amine Gouiri', 'ALG', 'AAN', 'wk'),
(gen_random_uuid(), 'Anis Hadj Moussa', 'ALG', 'AAN', 'wk'),
(gen_random_uuid(), 'Farès Ghedjemis', 'ALG', 'AAN', 'wk'),
(gen_random_uuid(), 'Nadir Benbouali', 'ALG', 'AAN', 'wk'),
(gen_random_uuid(), 'Adil Boulbina', 'ALG', 'AAN', 'wk');

-- Oostenrijk (AUT)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Patrick Pentz', 'AUT', 'DOE', 'wk'),
(gen_random_uuid(), 'Alexander Schlager', 'AUT', 'DOE', 'wk'),
(gen_random_uuid(), 'Florian Wiegele', 'AUT', 'DOE', 'wk'),
(gen_random_uuid(), 'David Alaba', 'AUT', 'VER', 'wk'),
(gen_random_uuid(), 'Kevin Danso', 'AUT', 'VER', 'wk'),
(gen_random_uuid(), 'Marco Friedl', 'AUT', 'VER', 'wk'),
(gen_random_uuid(), 'Philipp Lienhart', 'AUT', 'VER', 'wk'),
(gen_random_uuid(), 'Phillipp Mwene', 'AUT', 'VER', 'wk'),
(gen_random_uuid(), 'Stefan Posch', 'AUT', 'VER', 'wk'),
(gen_random_uuid(), 'Alexander Prass', 'AUT', 'VER', 'wk'),
(gen_random_uuid(), 'Michael Svoboda', 'AUT', 'VER', 'wk'),
(gen_random_uuid(), 'David Affengruber', 'AUT', 'VER', 'wk'),
(gen_random_uuid(), 'Marcel Sabitzer', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Konrad Laimer', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Xaver Schlager', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Nicolas Seiwald', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Christoph Baumgartner', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Romano Schmid', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Patrick Wimmer', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Paul Wanner', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Florian Grillitsch', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Carney Chukwuemeka', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Alessandro Schöpf', 'AUT', 'MID', 'wk'),
(gen_random_uuid(), 'Marko Arnautović', 'AUT', 'AAN', 'wk'),
(gen_random_uuid(), 'Michael Gregoritsch', 'AUT', 'AAN', 'wk'),
(gen_random_uuid(), 'Saša Kalajdžić', 'AUT', 'AAN', 'wk');

-- Jordanië (JOR)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Amer Shafi', 'JOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Ayman Al-Fakhouri', 'JOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Mohammad Abu Alias', 'JOR', 'DOE', 'wk'),
(gen_random_uuid(), 'Yazan Haddad', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Ahmad Al-Rosan', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Baha Obaid', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Mahmoud Al-Arab', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Emad Abualnadi', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Ali Abu Dahab', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Firas Nasib', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Mohammed Abu Taha', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Omar Abu Hasheesh', 'JOR', 'VER', 'wk'),
(gen_random_uuid(), 'Moath Al-Rashdan', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Mahmoud Saadeh', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Mahmoud Al-Mardi', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Ahmad Jamous', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Khaled Al-Dawoud', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Islam Batran', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Yazan Al-Naimat', 'JOR', 'MID', 'wk'),
(gen_random_uuid(), 'Musa Al-Tamari', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Omar Al-Fakhouri', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Yazan Abu Zrayq', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Osama Azaizeh', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Hamza Sabra', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Ahmad Ghanim', 'JOR', 'AAN', 'wk'),
(gen_random_uuid(), 'Salam Al-Aqrabawi', 'JOR', 'AAN', 'wk');

-- ============================================================
-- GROEP K: COL, COD, POR, UZB
-- ============================================================

-- Colombia (COL)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'David Ospina', 'COL', 'DOE', 'wk'),
(gen_random_uuid(), 'Álvaro Montero', 'COL', 'DOE', 'wk'),
(gen_random_uuid(), 'Camilo Vargas', 'COL', 'DOE', 'wk'),
(gen_random_uuid(), 'Daniel Muñoz', 'COL', 'VER', 'wk'),
(gen_random_uuid(), 'Santiago Arias', 'COL', 'VER', 'wk'),
(gen_random_uuid(), 'Davinson Sánchez', 'COL', 'VER', 'wk'),
(gen_random_uuid(), 'Jhon Lucumí', 'COL', 'VER', 'wk'),
(gen_random_uuid(), 'Yerry Mina', 'COL', 'VER', 'wk'),
(gen_random_uuid(), 'Willer Ditta', 'COL', 'VER', 'wk'),
(gen_random_uuid(), 'Deiver Machado', 'COL', 'VER', 'wk'),
(gen_random_uuid(), 'Johan Mojica', 'COL', 'VER', 'wk'),
(gen_random_uuid(), 'James Rodríguez', 'COL', 'MID', 'wk'),
(gen_random_uuid(), 'Jefferson Lerma', 'COL', 'MID', 'wk'),
(gen_random_uuid(), 'Jhon Arias', 'COL', 'MID', 'wk'),
(gen_random_uuid(), 'Jorge Carrascal', 'COL', 'MID', 'wk'),
(gen_random_uuid(), 'Juan Fernando Quintero', 'COL', 'MID', 'wk'),
(gen_random_uuid(), 'Richard Ríos', 'COL', 'MID', 'wk'),
(gen_random_uuid(), 'Kevin Castaño', 'COL', 'MID', 'wk'),
(gen_random_uuid(), 'Jaminton Campaz', 'COL', 'MID', 'wk'),
(gen_random_uuid(), 'Gustavo Puerta', 'COL', 'MID', 'wk'),
(gen_random_uuid(), 'Juan Portilla', 'COL', 'MID', 'wk'),
(gen_random_uuid(), 'Luis Díaz', 'COL', 'AAN', 'wk'),
(gen_random_uuid(), 'Jhon Córdoba', 'COL', 'AAN', 'wk'),
(gen_random_uuid(), 'Juan Camilo Hernández', 'COL', 'AAN', 'wk'),
(gen_random_uuid(), 'Carlos Gómez', 'COL', 'AAN', 'wk'),
(gen_random_uuid(), 'Luis Sinisterra', 'COL', 'AAN', 'wk');

-- DR Congo (COD)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Hervé Epolo', 'COD', 'DOE', 'wk'),
(gen_random_uuid(), 'Joris Kayembe', 'COD', 'DOE', 'wk'),
(gen_random_uuid(), 'Carlos Mpasi', 'COD', 'DOE', 'wk'),
(gen_random_uuid(), 'Aaron Wan-Bissaka', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Chancel Mbemba', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Arthur Masuaku', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Samuel Bastubinsika', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Pierre Kalulu', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Bryan Kapuadi', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Axel Tuanzebe', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Glody Lilepo', 'COD', 'VER', 'wk'),
(gen_random_uuid(), 'Gael Kakuta', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Jonathan Moutoussamy', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Julien Pickel', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Christopher Mbuku', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Théo Bongonda', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Emmanuel Lassina Traoré', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Fabrice Olinga', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Sébastien Thill', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Marcel Lewis', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Silas Mvumpa', 'COD', 'MID', 'wk'),
(gen_random_uuid(), 'Yoane Wissa', 'COD', 'AAN', 'wk'),
(gen_random_uuid(), 'Cédric Bakambu', 'COD', 'AAN', 'wk'),
(gen_random_uuid(), 'Simon Banza', 'COD', 'AAN', 'wk'),
(gen_random_uuid(), 'Fiston Mayele', 'COD', 'AAN', 'wk'),
(gen_random_uuid(), 'Ike Ugbo', 'COD', 'AAN', 'wk');

-- Portugal (POR)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Diogo Costa', 'POR', 'DOE', 'wk'),
(gen_random_uuid(), 'José Sá', 'POR', 'DOE', 'wk'),
(gen_random_uuid(), 'Ricardo Velho', 'POR', 'DOE', 'wk'),
(gen_random_uuid(), 'Rúben Dias', 'POR', 'VER', 'wk'),
(gen_random_uuid(), 'Gonçalo Inácio', 'POR', 'VER', 'wk'),
(gen_random_uuid(), 'João Cancelo', 'POR', 'VER', 'wk'),
(gen_random_uuid(), 'Nuno Mendes', 'POR', 'VER', 'wk'),
(gen_random_uuid(), 'Diogo Dalot', 'POR', 'VER', 'wk'),
(gen_random_uuid(), 'Nélson Semedo', 'POR', 'VER', 'wk'),
(gen_random_uuid(), 'Tomás Araújo', 'POR', 'VER', 'wk'),
(gen_random_uuid(), 'Renato Veiga', 'POR', 'VER', 'wk'),
(gen_random_uuid(), 'Vitinha', 'POR', 'MID', 'wk'),
(gen_random_uuid(), 'João Neves', 'POR', 'MID', 'wk'),
(gen_random_uuid(), 'Bruno Fernandes', 'POR', 'MID', 'wk'),
(gen_random_uuid(), 'Rúben Neves', 'POR', 'MID', 'wk'),
(gen_random_uuid(), 'Matheus Nunes', 'POR', 'MID', 'wk'),
(gen_random_uuid(), 'Bernardo Silva', 'POR', 'MID', 'wk'),
(gen_random_uuid(), 'Samú Costa', 'POR', 'MID', 'wk'),
(gen_random_uuid(), 'Cristiano Ronaldo', 'POR', 'AAN', 'wk'),
(gen_random_uuid(), 'Gonçalo Ramos', 'POR', 'AAN', 'wk'),
(gen_random_uuid(), 'Pedro Neto', 'POR', 'AAN', 'wk'),
(gen_random_uuid(), 'Rafael Leão', 'POR', 'AAN', 'wk'),
(gen_random_uuid(), 'João Félix', 'POR', 'AAN', 'wk'),
(gen_random_uuid(), 'Francisco Conceição', 'POR', 'AAN', 'wk'),
(gen_random_uuid(), 'Trincão', 'POR', 'AAN', 'wk'),
(gen_random_uuid(), 'Gonçalo Guedes', 'POR', 'AAN', 'wk');

-- Oezbekistan (UZB)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Utkir Yusupov', 'UZB', 'DOE', 'wk'),
(gen_random_uuid(), 'Dilshod Nematov', 'UZB', 'DOE', 'wk'),
(gen_random_uuid(), 'Eldor Ergashev', 'UZB', 'DOE', 'wk'),
(gen_random_uuid(), 'Abdukodir Khusanov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Umid Alijonov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Khojiakbar Alijonov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Jasur Ashurmatov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Shamsiddin Nasrullaev', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Muhammadali Eshmurodov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Sardor Abdullaev', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Otabek Shukurov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Doston Tursunov', 'UZB', 'VER', 'wk'),
(gen_random_uuid(), 'Jaloliddin Masharipov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Islom Tukhtahujaev', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Bobir Abdixoliqov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Azizbek Haydarov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Akbar Iskanderov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Odil Ahmedov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Jamshid Iskanderov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Sanjar Tursunov', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Alisher Fayzullaev', 'UZB', 'MID', 'wk'),
(gen_random_uuid(), 'Eldor Shomurodov', 'UZB', 'AAN', 'wk'),
(gen_random_uuid(), 'Dostonbek Khamdamov', 'UZB', 'AAN', 'wk'),
(gen_random_uuid(), 'Ilkhom Zaripov', 'UZB', 'AAN', 'wk'),
(gen_random_uuid(), 'Oybek Bokiev', 'UZB', 'AAN', 'wk'),
(gen_random_uuid(), 'Abbosbek Fayzullaev', 'UZB', 'AAN', 'wk');

-- ============================================================
-- GROEP L: ENG, CRO, GHA, PAN
-- ============================================================

-- Engeland (ENG)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Jordan Pickford', 'ENG', 'DOE', 'wk'),
(gen_random_uuid(), 'Dean Henderson', 'ENG', 'DOE', 'wk'),
(gen_random_uuid(), 'James Trafford', 'ENG', 'DOE', 'wk'),
(gen_random_uuid(), 'Ezri Konsa', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'John Stones', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Marc Guéhi', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Trent Alexander-Arnold', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Dan Burn', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Reece James', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Jarrad Branthwaite', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Levi Colwill', 'ENG', 'VER', 'wk'),
(gen_random_uuid(), 'Declan Rice', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Jude Bellingham', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Jordan Henderson', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Kobbie Mainoo', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Morgan Gibbs-White', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Adam Wharton', 'ENG', 'MID', 'wk'),
(gen_random_uuid(), 'Bukayo Saka', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Harry Kane', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Marcus Rashford', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Anthony Gordon', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Ollie Watkins', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Noni Madueke', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Eberechi Eze', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Phil Foden', 'ENG', 'AAN', 'wk'),
(gen_random_uuid(), 'Cole Palmer', 'ENG', 'AAN', 'wk');

-- Kroatië (CRO)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Dominik Livaković', 'CRO', 'DOE', 'wk'),
(gen_random_uuid(), 'Ivica Ivušić', 'CRO', 'DOE', 'wk'),
(gen_random_uuid(), 'Ivo Grbić', 'CRO', 'DOE', 'wk'),
(gen_random_uuid(), 'Joško Gvardiol', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Dario Špikić', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Josip Šutalo', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Josip Stanišić', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Marin Pongračić', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Martin Erlić', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Domagoj Vida', 'CRO', 'VER', 'wk'),
(gen_random_uuid(), 'Luka Modrić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Mateo Kovačić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Marcelo Brozović', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Nikola Vlašić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Lovro Majer', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Martin Baturina', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Luka Sučić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Petar Sučić', 'CRO', 'MID', 'wk'),
(gen_random_uuid(), 'Ivan Perišić', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Andrej Kramarić', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Ante Budimir', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Marko Pjaca', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Dario Uremović', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Stipe Biuk', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Roko Šimić', 'CRO', 'AAN', 'wk'),
(gen_random_uuid(), 'Dario Matanović', 'CRO', 'AAN', 'wk');

-- Ghana (GHA)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Lawrence Ati-Zigi', 'GHA', 'DOE', 'wk'),
(gen_random_uuid(), 'Ibrahim Danlad', 'GHA', 'DOE', 'wk'),
(gen_random_uuid(), 'Manaf Nurudeen', 'GHA', 'DOE', 'wk'),
(gen_random_uuid(), 'Alidu Seidu', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Alexander Djiku', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Baba Rahman', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Daniel Amartey', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Gideon Mensah', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Tariq Lamptey', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Dennis Odoi', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Kasim Adams', 'GHA', 'VER', 'wk'),
(gen_random_uuid(), 'Thomas Partey', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Antoine Semenyo', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Salis Abdul Samed', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Elisha Owusu', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Daniel Kofi Kyereh', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Mohammed Kudus', 'GHA', 'MID', 'wk'),
(gen_random_uuid(), 'Abdul Fatawu', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Jordan Ayew', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Brandon Thomas-Asante', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Iñaki Williams', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Kamaldeen Sulemana', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Ernest Nuamah', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Felix Afena-Gyan', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Kwadwo Baah', 'GHA', 'AAN', 'wk'),
(gen_random_uuid(), 'Osman Bukari', 'GHA', 'AAN', 'wk');

-- Panama (PAN)
INSERT INTO "Speler" (id, naam, team, positie, soort) VALUES
(gen_random_uuid(), 'Luis Mejía', 'PAN', 'DOE', 'wk'),
(gen_random_uuid(), 'Orlando Mosquera', 'PAN', 'DOE', 'wk'),
(gen_random_uuid(), 'César Samudio', 'PAN', 'DOE', 'wk'),
(gen_random_uuid(), 'Amir Murillo', 'PAN', 'VER', 'wk'),
(gen_random_uuid(), 'Fidel Escobar', 'PAN', 'VER', 'wk'),
(gen_random_uuid(), 'Eric Davis', 'PAN', 'VER', 'wk'),
(gen_random_uuid(), 'José Córdoba', 'PAN', 'VER', 'wk'),
(gen_random_uuid(), 'César Blackman', 'PAN', 'VER', 'wk'),
(gen_random_uuid(), 'Andrés Andrade', 'PAN', 'VER', 'wk'),
(gen_random_uuid(), 'Edgardo Fariña', 'PAN', 'VER', 'wk'),
(gen_random_uuid(), 'Jorge Gutiérrez', 'PAN', 'VER', 'wk'),
(gen_random_uuid(), 'Jiovani Ramos', 'PAN', 'VER', 'wk'),
(gen_random_uuid(), 'Roderick Miller', 'PAN', 'VER', 'wk'),
(gen_random_uuid(), 'Aníbal Godoy', 'PAN', 'MID', 'wk'),
(gen_random_uuid(), 'Adalberto Carrasquilla', 'PAN', 'MID', 'wk'),
(gen_random_uuid(), 'Carlos Harvey', 'PAN', 'MID', 'wk'),
(gen_random_uuid(), 'Cristian Martínez', 'PAN', 'MID', 'wk'),
(gen_random_uuid(), 'José Luis Rodríguez', 'PAN', 'MID', 'wk'),
(gen_random_uuid(), 'César Yanis', 'PAN', 'MID', 'wk'),
(gen_random_uuid(), 'Yoel Bárcenas', 'PAN', 'MID', 'wk'),
(gen_random_uuid(), 'Alberto Quintero', 'PAN', 'MID', 'wk'),
(gen_random_uuid(), 'Azarías Londoño', 'PAN', 'MID', 'wk'),
(gen_random_uuid(), 'Ismael Díaz', 'PAN', 'AAN', 'wk'),
(gen_random_uuid(), 'Cecilio Waterman', 'PAN', 'AAN', 'wk'),
(gen_random_uuid(), 'José Fajardo', 'PAN', 'AAN', 'wk'),
(gen_random_uuid(), 'Tomás Rodríguez', 'PAN', 'AAN', 'wk');
